/**
 * Matematikos programa 1–10 klasėms.
 *
 * ŠIS FAILAS YRA DUOMENYS, NE LOGIKA — kaip ir `lib/temos.ts`.
 * Surašyta pagal `uzdaviniu-temos.md`. Stambieji punktai (1., 2., 3.) yra
 * programos skyriai; jie rodomi paryškinti. `potemes` — smulkesnis skirstymas.
 *
 * `generatorius` nurodo raktą iš `lib/generatoriai/index.ts`. Jei jo nėra,
 * tema svetainėje rodoma, bet uždavinių kol kas negeneruoja — taip matyti,
 * kur biblioteką verta pildyti toliau.
 */

export type Lygis = 1 | 2 | 3

/**
 * Potemė. Paprasčiausiu atveju tai tik pavadinimas — tada ji paveldi savo
 * temos generatorių. Objekto forma naudojama tada, kai potemei tinka kitas
 * generatorius nei visai temai (pvz. 8 kl. „Kvadratinė ir kubinė šaknys"
 * temoje „Skaičiai ir skaičiavimai").
 */
export type Potema =
  | string
  | {
      pavadinimas: string
      generatorius?: string
      lygis?: Lygis
    }

export type ProgramosTema = {
  /** Stambiojo punkto numeris klasėje: 1., 2., 3. */
  numeris: number
  pavadinimas: string
  potemes?: Potema[]
  generatorius?: string
  /** Sunkumo lygis, kuriuo tema generuojama pagal nutylėjimą. */
  lygis?: Lygis
}

export type ProgramosKlase = {
  klase: number
  temos: ProgramosTema[]
}

/** Potemė su galutiniu numeriu ir generatoriumi — jau paveldėtu iš temos. */
export type IsskleistaPotema = {
  /** „3.2" pavidalu. */
  numeris: string
  pavadinimas: string
  generatorius?: string
  lygis: Lygis
}

/**
 * Potemės su numeriais ir generatoriais. Potemė be savo generatoriaus
 * paveldi temos generatorių, tad paspaudus bet kurią gaunami uždaviniai.
 */
export function potemes(tema: ProgramosTema): IsskleistaPotema[] {
  return (tema.potemes ?? []).map((p, i) => {
    const objektas = typeof p === 'string' ? { pavadinimas: p } : p
    return {
      numeris: `${tema.numeris}.${i + 1}`,
      pavadinimas: objektas.pavadinimas,
      generatorius: objektas.generatorius ?? tema.generatorius,
      lygis: objektas.lygis ?? tema.lygis ?? 2,
    }
  })
}

export const programa: ProgramosKlase[] = [
  {
    klase: 1,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Natūralieji skaičiai iki 100 ir skaičius 0',
        potemes: [
          'Skaičiai nuo 0 iki 100, skaičių palyginimas',
          'Sudėtis, skliaustai',
          'Atimtis',
          { pavadinimas: 'Finansiniai skaičiavimai. Eurai ir centai', generatorius: 'pinigai', lygis: 1 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 1,
      },
      {
        numeris: 2,
        pavadinimas: 'Modeliai ir sąryšiai',
        potemes: [
          'Dėsningumai. Sekos',
          { pavadinimas: 'Algoritmai ir programavimas', generatorius: 'algoritmai', lygis: 1 },
        ],
        generatorius: 'sekos',
        lygis: 1,
      },
      {
        numeris: 3,
        pavadinimas: 'Matavimų skalės ir vienetai',
        potemes: [
          { pavadinimas: 'Masė, laikas', generatorius: 'laikas', lygis: 1 },
          'Ilgis, atstumas',
          { pavadinimas: 'Konstravimas, transformacijos', generatorius: 'simetrija', lygis: 1 },
          { pavadinimas: 'Plokštumos figūros', generatorius: 'figuros', lygis: 1 },
          { pavadinimas: 'Erdvės figūros', generatorius: 'erdvines-figuros', lygis: 1 },
        ],
        generatorius: 'matavimo-vienetai',
        lygis: 1,
      },
      {
        numeris: 4,
        pavadinimas: 'Duomenys ir tikimybės',
        potemes: ['Duomenys ir jų interpretavimas'],
        generatorius: 'diagramos',
        lygis: 1,
      },
    ],
  },

  {
    klase: 2,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Natūralieji ir sveikieji skaičiai. Skaičiai nuo 0 iki 1000',
        potemes: [
          'Skaičiai ir skaitmenys',
          'Vienaženkliai, dviženkliai ir triženkliai skaičiai. Skaičių skyriai',
          'Skaičių rikiavimas',
          'Skaičių kaimynai',
          'Skaičių palyginimas',
        ],
        generatorius: 'skaiciu-palyginimas',
        lygis: 1,
      },
      {
        numeris: 2,
        pavadinimas: 'Sudėtis, atimtis',
        potemes: [
          'Skaičių nuo 1 iki 1000 sudėtis',
          'Skaičių nuo 1 iki 1000 atimtis',
          'Kaip spręsti dviejų žingsnių uždavinius',
          'Skaitinės lygybės ir nelygybės',
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Daugyba, dalyba',
        potemes: [
          'Kas yra daugyba. Kaip atlikti daugybos veiksmus',
          'Daugybos lentelė',
          'Kas yra dalyba',
          'Lyginiai ir nelyginiai skaičiai',
          'Kaip spręsti uždavinius',
          { pavadinimas: 'Veiksmų tvarka skaitiniame reiškinyje', generatorius: 'veiksmu-tvarka', lygis: 1 },
        ],
        generatorius: 'sveikieji',
        lygis: 1,
      },
      {
        numeris: 4,
        pavadinimas: 'Trupmenos ir dalys',
        potemes: [
          'Kas yra daikto dalis',
          'Kaip apskaičiuoti pusę, trečdalį, ketvirtadalį ir aštuntadalį',
          'Kaip rasti visą daiktų skaičių, kai žinoma jų dalis',
        ],
        generatorius: 'dalies-radimas',
        lygis: 1,
      },
      {
        numeris: 5,
        pavadinimas: 'Finansiniai skaičiavimai',
        potemes: [
          'Kas yra pinigai. Kam jie reikalingi',
          'Kas yra banknotas ir moneta',
          'Monetos vertė',
        ],
        generatorius: 'pinigai',
        lygis: 1,
      },
      {
        numeris: 6,
        pavadinimas: 'Dėsningumai. Sekos',
        potemes: [
          'Kas yra seka. Kas yra skaičių seka',
          'Kaip sudaroma objektų seka',
          'Kaip skaičių sekoje rasti trūkstamą jos narį',
        ],
        generatorius: 'sekos',
        lygis: 1,
      },
      {
        numeris: 7,
        pavadinimas: 'Algoritmai ir programavimas',
        potemes: ['Kas yra komanda', 'Komandos (nurodymai)', 'Pasirinkimo komanda'],
        generatorius: 'algoritmai',
        lygis: 1,
      },
      {
        numeris: 8,
        pavadinimas: 'Matavimo skalės ir vienetai',
        potemes: ['Masė', 'Temperatūra'],
        generatorius: 'matavimo-vienetai',
        lygis: 1,
      },
      {
        numeris: 9,
        pavadinimas: 'Masė, laikas, temperatūra',
        potemes: ['Laikas'],
        generatorius: 'laikas',
        lygis: 1,
      },
      {
        numeris: 10,
        pavadinimas: 'Ilgis, plotas, tūris',
        potemes: ['Ilgis (mm, cm, m, km). Kaip nubrėžti atkarpą', 'Plotas (langeliais)', 'Tūris'],
        generatorius: 'matavimo-vienetai',
        lygis: 2,
      },
      {
        numeris: 11,
        pavadinimas: 'Konstravimas. Transformacijos',
        potemes: ['Kaip rasti kelią plane pagal komandas', 'Simetriškos figūros'],
        generatorius: 'simetrija',
        lygis: 1,
      },
      {
        numeris: 12,
        pavadinimas: 'Figūros. Plokščiosios figūros',
        potemes: [
          'Plokščiosios figūros',
          'Kraštinės, kampai, viršūnės',
          { pavadinimas: 'Laužės', generatorius: 'lauzes', lygis: 1 },
          { pavadinimas: 'Simetriškos figūros', generatorius: 'simetrija', lygis: 1 },
        ],
        generatorius: 'figuros',
        lygis: 1,
      },
      {
        numeris: 13,
        pavadinimas: 'Erdvinės figūros',
        potemes: ['Erdvinės figūros', 'Ryšiai tarp dvimačių ir trimačių figūrų'],
        generatorius: 'erdvines-figuros',
        lygis: 1,
      },
      {
        numeris: 14,
        pavadinimas: 'Duomenys ir jų interpretavimas',
        potemes: [
          'Pirminiai ir antriniai duomenys',
          'Duomenų dažnių lentelė',
          'Stulpelinė diagrama',
          'Piktogramos',
        ],
        generatorius: 'diagramos',
        lygis: 2,
      },
    ],
  },

  {
    klase: 3,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Natūralieji skaičiai iki 10 000',
        potemes: [
          { pavadinimas: 'Skaičių skaitymas, rašymas, palyginimas, apvalinimas', generatorius: 'apvalinimas', lygis: 2 },
          { pavadinimas: 'Sudėtis ir atimtis', generatorius: 'sudetis-atimtis', lygis: 2 },
          'Daugyba iš vienaženklio skaičiaus',
          'Dalyba iš vienaženklio skaičiaus. Dalyba su liekana',
          { pavadinimas: 'Skaitiniai reiškiniai', generatorius: 'veiksmu-tvarka', lygis: 2 },
          { pavadinimas: 'Sekos, algoritmai', generatorius: 'sekos', lygis: 2 },
        ],
        generatorius: 'sveikieji',
        lygis: 2,
      },
      {
        numeris: 2,
        pavadinimas: 'Trupmeniniai skaičiai nuo 0 iki 1',
        potemes: [
          'Trupmenos samprata. Trupmenų vaizdavimas, palyginimas',
          'Dydžio, skaičiaus dalies ir visumos radimas',
        ],
        generatorius: 'dalies-radimas',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Matavimai',
        potemes: [
          { pavadinimas: 'Ilgio vienetai: cm, dm, m', generatorius: 'matavimo-vienetai', lygis: 1 },
          'Perimetro sąvoka. Daugiakampio perimetro skaičiavimas',
          { pavadinimas: 'Laiko vienetai: sek., min., val.', generatorius: 'laikas', lygis: 2 },
        ],
        generatorius: 'perimetras',
        lygis: 1,
      },
      {
        numeris: 4,
        pavadinimas: 'Raidiniai reiškiniai',
        potemes: [
          'Raidinio reiškinio samprata',
          'Raidinio reiškinio reikšmės',
          'Raidinio reiškinio sudarymas',
        ],
        generatorius: 'raidiniai-reiskiniai',
        lygis: 1,
      },
      {
        numeris: 5,
        pavadinimas: 'Lygtys',
        potemes: ['Lygties samprata', 'Lygčių sprendimas', 'Lygties sudarymas'],
        generatorius: 'tiesines-lygtys',
        lygis: 1,
      },
      {
        numeris: 6,
        pavadinimas: 'Plokštumos figūros',
        potemes: [
          { pavadinimas: 'Tiesės ir atkarpos', generatorius: 'lauzes', lygis: 2 },
          { pavadinimas: 'Kampai', generatorius: 'kampai', lygis: 1 },
          'Stačiakampis, kvadratas',
          { pavadinimas: 'Apskritimas ir skritulys', generatorius: 'apskritimas', lygis: 1 },
          { pavadinimas: 'Tiesės atžvilgiu simetriškos figūros', generatorius: 'simetrija', lygis: 1 },
        ],
        generatorius: 'perimetras',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Erdvės figūros',
        potemes: ['Stačiakampis gretasienis ir kubas', 'Prizmės', 'Piramidės'],
        generatorius: 'erdvines-figuros',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Duomenys ir jų interpretavimas. Tikėtinumas',
        potemes: ['Duomenų rinkimas', 'Duomenų vaizdavimas. Stulpelinės diagramos', 'Tikėtinumas'],
        generatorius: 'diagramos',
        lygis: 2,
      },
    ],
  },

  {
    klase: 4,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Natūralieji ir sveikieji skaičiai. Skaičiai nuo 0 iki 1 000 000',
        potemes: [
          'Skaičiai. Jų svarba kasdieniame gyvenime',
          { pavadinimas: 'Skirtingų skaičių dydžių palyginimas', generatorius: 'skaiciu-palyginimas', lygis: 3 },
          'Didelių skaičių trumpinimo žymėjimas',
          'Natūralieji skaičiai',
          { pavadinimas: 'Skaičių suapvalinimas', generatorius: 'apvalinimas', lygis: 3 },
          'Natūralieji ir sveikieji skaičiai',
        ],
        generatorius: 'apvalinimas',
        lygis: 1,
      },
      {
        numeris: 2,
        pavadinimas: 'Sudėtis, atimtis, daugyba, dalyba',
        potemes: [
          'Sudėtis. Sudėties veiksmų eilutė',
          'Atimtis iš didesnio skaičiaus',
          'Dalijimas',
          'Daugyba',
          'Kelių žingsnių uždavinių sprendimas',
        ],
        generatorius: 'sveikieji',
        lygis: 3,
      },
      {
        numeris: 3,
        pavadinimas: 'Trupmenos ir dalys',
        potemes: [
          'Paprastosios trupmenos ir jos dalys',
          'Taisyklingos ir netaisyklingos paprastosios trupmenos',
          'Paprastųjų trupmenų palyginimas',
          'Natūraliojo skaičiaus užrašymas trupmena',
          'Mišriojo skaičiaus sąvoka',
        ],
        generatorius: 'bendravardiklinimas',
        lygis: 3,
      },
      {
        numeris: 4,
        pavadinimas: 'Veiksmai su trupmenomis',
        potemes: [
          'Mišriųjų skaičių apvalinimas iki sveikųjų',
          { pavadinimas: 'Trupmenos su vardikliu 10, 100, 1000 dešimtainiais', generatorius: 'desimtaines', lygis: 3 },
          { pavadinimas: 'Trupmenos su vienodais vardikliais', generatorius: 'trupmenu-sudetis', lygis: 1 },
          { pavadinimas: 'Mišriosios trupmenos', generatorius: 'trupmenu-sudetis', lygis: 3 },
          'Dešimtainės trupmenos',
          { pavadinimas: 'Dešimtainiai skaičiai kainose', generatorius: 'pinigai', lygis: 1 },
        ],
        generatorius: 'desimtaines',
        lygis: 1,
      },
      {
        numeris: 5,
        pavadinimas: 'Finansiniai skaičiavimai',
        potemes: [
          'Nurodytos pinigų sumos palyginimas',
          'Nurodytos pinigų sumos sudėtis',
          'Nurodytos pinigų sumos atimtis',
          'Finansinio planavimo pagrindų taikymas',
        ],
        generatorius: 'pinigai',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Dėsningumai',
        potemes: [
          'Trupmenų arba dešimtainių skaičių sekų pratęsimas',
          'Sekos su daugėjančiais arba mažėjančiais elementais',
          'Sekos, gautos suliejus dvi sekas į vieną',
        ],
        generatorius: 'sekos',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Algoritmai ir programavimas',
        potemes: ['Kartojimo komandos', 'Komandų sekos'],
        generatorius: 'algoritmai',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Algebra. Lygtys',
        potemes: [
          'Iš žodinio uždavinio sąlygos ar schemos lygties sudarymas',
          'Situacijų nagrinėjimas skirtingomis lygtimis',
        ],
        generatorius: 'tiesines-lygtys',
        lygis: 1,
      },
      {
        numeris: 9,
        pavadinimas: 'Raidiniai reiškiniai',
        potemes: [
          'Raidinio reiškinio sąvoka',
          'Raidinių reiškinių sudarymas iš žodinio uždavinio',
        ],
        generatorius: 'raidiniai-reiskiniai',
        lygis: 2,
      },
      {
        numeris: 10,
        pavadinimas: 'Matavimo skalės ir vienetai. Masė, laikas, temperatūra, greitis',
        potemes: [
          { pavadinimas: 'Įvairių matavimo prietaisų rodmenys', generatorius: 'matavimo-vienetai', lygis: 2 },
          'Kelio ir greičio sąvokos',
          'Kelio, laiko, greičio sąryšis',
          'Kelio, laiko, greičio apskaičiavimas',
        ],
        generatorius: 'greitis',
        lygis: 1,
      },
      {
        numeris: 11,
        pavadinimas: 'Plotas, tūris',
        potemes: [
          { pavadinimas: 'Figūros plotas ir ploto vienetai', generatorius: 'plotas-turis', lygis: 1 },
          { pavadinimas: 'Tūris', generatorius: 'plotas-turis', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 1,
      },
      {
        numeris: 12,
        pavadinimas: 'Konstravimas. Transformacijos',
        potemes: [
          'Objektų padėties plokštumoje nusakymas',
          { pavadinimas: 'Objektų judėjimas plokštumoje', generatorius: 'simetrija', lygis: 3 },
          { pavadinimas: 'Ornamentai', generatorius: 'ornamentai', lygis: 1 },
          { pavadinimas: 'Objekto posūkis apie duotą tašką', generatorius: 'simetrija', lygis: 2 },
        ],
        generatorius: 'koordinates',
        lygis: 1,
      },
      {
        numeris: 13,
        pavadinimas: 'Figūros. Plokščiosios figūros',
        potemes: [
          { pavadinimas: 'Trikampiai pagal kraštinių ilgius', generatorius: 'figuros', lygis: 1 },
          'Trikampiai pagal kampus',
          { pavadinimas: 'Lygios geometrinės figūros', generatorius: 'figuros', lygis: 2 },
        ],
        generatorius: 'kampai',
        lygis: 1,
      },
      {
        numeris: 14,
        pavadinimas: 'Erdvinės figūros',
        potemes: [
          { pavadinimas: 'Kubas ir stačiakampis gretasienis', generatorius: 'erdvines-figuros', lygis: 1 },
          { pavadinimas: 'Erdvinės figūros', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Erdvinės figūros iš įvairių pusių', generatorius: 'plotas-turis', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 2,
      },
      {
        numeris: 15,
        pavadinimas: 'Duomenys ir interpretavimas',
        potemes: [
          'Statistinis tyrimas',
          { pavadinimas: 'Diagramų skaitymas', generatorius: 'diagramos', lygis: 2 },
        ],
        generatorius: 'vidurkis',
        lygis: 1,
      },
      {
        numeris: 16,
        pavadinimas: 'Tikimybės ir interpretavimas',
        potemes: ['Bandymas. Bandymo baigtis', 'Baigties tikimybė užrašoma trupmena'],
        generatorius: 'tikimybe',
        lygis: 1,
      },
    ],
  },

  {
    klase: 5,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Natūralieji skaičiai',
        potemes: [
          { pavadinimas: 'Skaičius ir skaitmuo', lygis: 1 },
          { pavadinimas: 'Skaičiaus skaitmenų skyrių lentelė', lygis: 1 },
          { pavadinimas: 'Skaitmens reikšmė', lygis: 1 },
          { pavadinimas: 'Rašome natūraliuosius skaičius', lygis: 2 },
          { pavadinimas: 'Skaičių tiesė', generatorius: 'koordinates', lygis: 2 },
          { pavadinimas: 'Palyginame natūraliuosius skaičius', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Apvaliname iki dešimčių', generatorius: 'apvalinimas', lygis: 2 },
          { pavadinimas: 'Apvaliname iki nurodyto skyriaus', generatorius: 'apvalinimas', lygis: 2 },
          { pavadinimas: 'Romėniškieji skaitmenys', lygis: 2 },
          { pavadinimas: 'Rašome skaičius romėniškaisiais skaitmenimis', lygis: 2 },
        ],
        generatorius: 'skaitmenys',
        lygis: 2,
      },
      {
        numeris: 2,
        pavadinimas: 'Veiksmai su natūraliaisiais skaičiais',
        potemes: [
          { pavadinimas: 'Skaičių sudėtis. Sudėties perstatomumo dėsnis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Sudėties jungiamumo dėsnis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Skaičių atimtis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Atimties dėsniai', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Skaičių daugyba. Daugybos perstatomumo dėsnis', lygis: 2 },
          { pavadinimas: 'Daugybos jungiamumo dėsnis', lygis: 2 },
          { pavadinimas: 'Daugybos skirstomumo dėsnis', lygis: 2 },
          { pavadinimas: 'Skaičių dalyba. Dalyba kampu', lygis: 2 },
          { pavadinimas: 'Dalybos dėsniai. Pagrindinė dalmens savybė', lygis: 2 },
          { pavadinimas: 'Sumos (skirtumo) dalijimas iš natūraliojo skaičiaus', lygis: 2 },
          { pavadinimas: 'Kelio formulė', generatorius: 'greitis', lygis: 2 },
          { pavadinimas: 'Judėjimas iš tos pačios vietos', generatorius: 'greitis', lygis: 2 },
          { pavadinimas: 'Judėjimas iš skirtingų vietų', generatorius: 'greitis', lygis: 2 },
        ],
        generatorius: 'sveikieji',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Dalumas',
        potemes: [
          { pavadinimas: 'Dalijame iš 10 ir iš 100', lygis: 1 },
          { pavadinimas: 'Dalijame iš 5 ir iš 2', lygis: 1 },
          { pavadinimas: 'Dalijame iš 9 ir iš 3', lygis: 1 },
          { pavadinimas: 'Dalijame iš 4', lygis: 1 },
          { pavadinimas: 'Skaičiaus dalikliai', generatorius: 'dalumas', lygis: 2 },
          { pavadinimas: 'Pirminiai ir sudėtiniai skaičiai', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Skaidome pirminiais dauginamaisiais', lygis: 2 },
          { pavadinimas: 'Didžiausiasis bendrasis daliklis', generatorius: 'dalumas', lygis: 2 },
          { pavadinimas: 'Skaičiaus kartotiniai', generatorius: 'dalumas', lygis: 2 },
          { pavadinimas: 'Mažiausiasis bendrasis kartotinis', generatorius: 'dalumas', lygis: 2 },
        ],
        generatorius: 'dalumo-pozymiai',
        lygis: 2,
      },
      {
        numeris: 4,
        pavadinimas: 'Trupmeniniai skaičiai',
        potemes: [
          { pavadinimas: 'Taisyklingosios ir netaisyklingosios paprastosios trupmenos', lygis: 2 },
          { pavadinimas: 'Netaisyklingoji trupmena ir mišrusis skaičius', lygis: 2 },
          { pavadinimas: 'Pagrindinė paprastosios trupmenos savybė', lygis: 2 },
          { pavadinimas: 'Dešimtainiai skaičiai', generatorius: 'desimtaines', lygis: 2 },
          { pavadinimas: 'Lygūs dešimtainiai skaičiai', generatorius: 'desimtaines', lygis: 2 },
          { pavadinimas: 'Paprastoji trupmena ir dešimtainis skaičius', lygis: 2 },
          { pavadinimas: 'Procentai', generatorius: 'procentai', lygis: 2 },
          { pavadinimas: 'Paprastosios trupmenos, dešimtainiai skaičiai ir procentai', generatorius: 'procentai', lygis: 2 },
          { pavadinimas: 'Skaičiaus dalies radimas', generatorius: 'dalies-radimas', lygis: 2 },
          { pavadinimas: 'Skaičiaus radimas, kai žinoma jo dalis', generatorius: 'bendravardiklinimas', lygis: 2 },
          { pavadinimas: 'Finansiniai skaičiavimai: pirkimas, pardavimas ir nuolaidos', generatorius: 'palukanos', lygis: 2 },
        ],
        generatorius: 'trupmenu-sudetis',
        lygis: 2,
      },
      {
        numeris: 5,
        pavadinimas: 'Veiksmai su paprastosiomis trupmenomis ir mišriaisiais skaičiais',
        potemes: [
          { pavadinimas: 'Palyginame', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Sudedame paprastąsias trupmenas', lygis: 2 },
          { pavadinimas: 'Sudedame mišriuosius skaičius', lygis: 2 },
          { pavadinimas: 'Atimame paprastąją trupmeną', lygis: 2 },
          { pavadinimas: 'Natūraliųjų ir mišriųjų skaičių atimtis', lygis: 2 },
          { pavadinimas: 'Mišriųjų skaičių atimtis', lygis: 2 },
          { pavadinimas: 'Bendravardikliname', generatorius: 'bendravardiklinimas', lygis: 1 },
          { pavadinimas: 'Palyginame', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Sudedame', lygis: 2 },
          { pavadinimas: 'Atimame', lygis: 2 },
          { pavadinimas: 'Paprastosios trupmenos ir natūraliojo skaičiaus daugyba', generatorius: 'trupmenu-daugyba', lygis: 2 },
          { pavadinimas: 'Mišriojo ir natūraliojo skaičių daugyba', generatorius: 'sveikieji', lygis: 2 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Veiksmai su dešimtainiais skaičiais',
        potemes: [
          { pavadinimas: 'Palyginame', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Apvaliname iki vienetų', lygis: 2 },
          { pavadinimas: 'Apvaliname iki nurodyto skyriaus', lygis: 2 },
          { pavadinimas: 'Sudedame', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Atimame', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Dešimtainio ir natūraliojo skaičių daugyba', generatorius: 'desimtaines', lygis: 2 },
          { pavadinimas: 'Dauginame iš 10, 100, 1000, ...', generatorius: 'sveikieji', lygis: 2 },
        ],
        generatorius: 'apvalinimas',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Reiškiniai. Lygtys',
        potemes: [
          { pavadinimas: 'Skaitinis reiškinys ir jo reikšmė', generatorius: 'veiksmu-tvarka', lygis: 2 },
          { pavadinimas: 'Raidinis reiškinys', lygis: 2 },
          { pavadinimas: 'Raidinio reiškinio reikšmės', lygis: 2 },
          { pavadinimas: 'Dauginame ir dalijame iš skaičiaus', lygis: 2 },
          { pavadinimas: 'Panašieji nariai, jų sutraukimas', lygis: 3 },
          { pavadinimas: 'Skaitinių lygybių savybės', generatorius: 'tiesines-lygtys', lygis: 1 },
          { pavadinimas: 'Lygtis ir jos sprendinys', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Lygties sprendimas', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Tekstinių uždavinių sprendimas sudarant lygtis', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Skaičių sekos ir įvesties–išvesties lentelės', generatorius: 'rekurencios-sekos', lygis: 2 },
        ],
        generatorius: 'raidiniai-reiskiniai',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Kampai',
        potemes: [
          { pavadinimas: 'Kampas ir jo elementai', lygis: 2 },
          { pavadinimas: 'Kuris kampas didesnis?', lygis: 2 },
          { pavadinimas: 'Ištiestinis ir statusis kampai', lygis: 2 },
          { pavadinimas: 'Smailusis ir bukasis kampai', lygis: 2 },
          { pavadinimas: 'Pilnasis ir priešpilnis kampai', lygis: 2 },
          { pavadinimas: 'Laipsnis', lygis: 2 },
          { pavadinimas: 'Kampų palyginimas', lygis: 2 },
          { pavadinimas: 'Ištiestinio, stačiojo ir smailiojo kampų dydžiai', lygis: 2 },
          { pavadinimas: 'Bukojo, pilnojo ir priešpilnio kampų dydžiai', lygis: 2 },
          { pavadinimas: 'Matlankis. Matuojame kampus', generatorius: 'konstravimas', lygis: 2 },
          { pavadinimas: 'Braižome kampą. Kampo pusiaukampinė', generatorius: 'konstravimas', lygis: 1 },
          { pavadinimas: 'Gretutiniai kampai', lygis: 2 },
          { pavadinimas: 'Kryžminiai kampai', lygis: 2 },
        ],
        generatorius: 'kampai',
        lygis: 2,
      },
      {
        numeris: 9,
        pavadinimas: 'Trikampiai ir keturkampiai',
        potemes: [
          { pavadinimas: 'Daugiakampis', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Trikampio kampai', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Daugiakampio kampai', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Ilgio matavimo vienetai', generatorius: 'matavimo-vienetai', lygis: 2 },
          { pavadinimas: 'Trikampio perimetras', generatorius: 'perimetras', lygis: 2 },
          { pavadinimas: 'Keturkampio perimetras', generatorius: 'perimetras', lygis: 2 },
          { pavadinimas: 'Ploto matavimo vienetai', lygis: 2 },
          { pavadinimas: 'Stačiakampio ir kvadrato plotai', lygis: 2 },
          { pavadinimas: 'Stačiojo trikampio plotas', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 2,
      },
      {
        numeris: 10,
        pavadinimas: 'Simetrija. Posūkis. Postūmis',
        potemes: [
          { pavadinimas: 'Tiesės atžvilgiu simetriškos figūros', lygis: 2 },
          { pavadinimas: 'Figūros, turinčios simetrijos ašį', lygis: 2 },
          { pavadinimas: 'Posūkis apie tašką', lygis: 2 },
          { pavadinimas: 'Taško atžvilgiu simetriškos figūros', lygis: 2 },
          { pavadinimas: 'Figūros, turinčios simetrijos centrą', lygis: 2 },
          { pavadinimas: 'Lygiagretusis postūmis', lygis: 2 },
          { pavadinimas: 'Lygiagretainis, rombas, trapecija', generatorius: 'figuros', lygis: 2 },
        ],
        generatorius: 'simetrija',
        lygis: 2,
      },
      {
        numeris: 11,
        pavadinimas: 'Erdviniai kūnai',
        potemes: [
          { pavadinimas: 'Vaizduojame', generatorius: 'erdvines-figuros', lygis: 1 },
          { pavadinimas: 'Matmenys. Išklotinė', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Stačiakampio gretasienio paviršiaus plotas', lygis: 2 },
          { pavadinimas: 'Kubo paviršiaus plotas', lygis: 2 },
          { pavadinimas: 'Tūris', lygis: 2 },
          { pavadinimas: 'Stačiakampio gretasienio tūris', lygis: 2 },
          { pavadinimas: 'Kubo tūris', lygis: 2 },
          { pavadinimas: 'Talpa', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 2,
      },
      {
        numeris: 12,
        pavadinimas: 'Duomenys ir tikimybės',
        potemes: [
          { pavadinimas: 'Kokybiniai ir kiekybiniai duomenys', lygis: 2 },
          { pavadinimas: 'Imtis, imties vidurkis', lygis: 2 },
          { pavadinimas: 'Bandymas ir jo baigtys', generatorius: 'tikimybe', lygis: 2 },
          { pavadinimas: 'Įvykio tikimybė', generatorius: 'tikimybe', lygis: 2 },
        ],
        generatorius: 'vidurkis',
        lygis: 2,
      },
    ],
  },

  {
    klase: 6,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Skaičiai',
        potemes: [
          { pavadinimas: 'Skaičiai skaičių tiesėje', lygis: 2 },
          { pavadinimas: 'Vienas kitam priešingieji skaičiai', generatorius: 'saknu-ivertinimas', lygis: 2 },
          { pavadinimas: 'Skaičių palyginimas', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Natūralieji, sveikieji, racionalieji skaičiai', generatorius: 'saknu-ivertinimas', lygis: 2 },
          { pavadinimas: 'Koordinačių plokštuma', lygis: 2 },
        ],
        generatorius: 'koordinates',
        lygis: 2,
      },
      {
        numeris: 2,
        pavadinimas: 'Racionaliųjų skaičių sudėtis ir atimtis',
        potemes: [
          { pavadinimas: 'Sudedame skaičius su vienodais ženklais', lygis: 2 },
          { pavadinimas: 'Sudedame skaičius su skirtingais ženklais', lygis: 2 },
          { pavadinimas: 'Atimame', lygis: 2 },
          { pavadinimas: 'Algebrinė suma', lygis: 2 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Neneigiamųjų paprastųjų trupmenų daugyba ir dalyba',
        potemes: [
          { pavadinimas: 'Paprastosios trupmenos ir natūraliojo skaičiaus daugyba', lygis: 2 },
          { pavadinimas: 'Dauginame paprastąsias trupmenas', lygis: 2 },
          { pavadinimas: 'Paprastąją trupmeną dalijame iš natūraliojo skaičiaus', generatorius: 'trupmenu-sudetis', lygis: 2 },
          { pavadinimas: 'Dalijame iš paprastosios trupmenos', lygis: 2 },
        ],
        generatorius: 'trupmenu-daugyba',
        lygis: 2,
      },
      {
        numeris: 4,
        pavadinimas: 'Neneigiamųjų dešimtainių skaičių daugyba ir dalyba',
        potemes: [
          { pavadinimas: 'Dešimtainį skaičių dauginame iš natūraliojo', lygis: 2 },
          { pavadinimas: 'Dauginame dešimtainius skaičius', lygis: 2 },
          { pavadinimas: 'Dešimtainį skaičių dalijame iš natūraliojo', lygis: 2 },
          { pavadinimas: 'Periodinės trupmenos', generatorius: 'trupmenu-sudetis', lygis: 2 },
          { pavadinimas: 'Dalijame dešimtainius skaičius', lygis: 2 },
        ],
        generatorius: 'desimtaines',
        lygis: 2,
      },
      {
        numeris: 5,
        pavadinimas: 'Teigiamųjų ir neigiamųjų skaičių daugyba ir dalyba',
        potemes: [
          { pavadinimas: 'Dauginame', lygis: 2 },
          { pavadinimas: 'Dalijame', lygis: 2 },
          { pavadinimas: 'Dauginame ir dalijame', lygis: 2 },
          { pavadinimas: 'Taikome skirstomumo dėsnį', lygis: 2 },
          { pavadinimas: 'Skaičiuojame skaitinių reiškinių reikšmes', generatorius: 'veiksmu-tvarka', lygis: 2 },
        ],
        generatorius: 'sveikieji',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Procentai. Proporcija',
        potemes: [
          { pavadinimas: 'Trupmenos, dešimtainiai skaičiai, procentai', lygis: 2 },
          { pavadinimas: 'Ieškome skaičiaus dalies', generatorius: 'dalies-radimas', lygis: 2 },
          { pavadinimas: 'Ieškome viso skaičiaus', lygis: 2 },
          { pavadinimas: 'Pagrindinė proporcijos savybė', generatorius: 'proporcijos', lygis: 2 },
          { pavadinimas: 'Procentų uždavinių sprendimas sudarant proporciją', lygis: 2 },
          { pavadinimas: 'Dalijimas proporcingai', generatorius: 'proporcijos', lygis: 2 },
          { pavadinimas: 'Finansiniai skaičiavimai: nuolaidos, vieneto tarifai, biudžetas ir mokesčiai', generatorius: 'palukanos', lygis: 2 },
        ],
        generatorius: 'procentai',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Tiesioginis proporcingumas',
        potemes: [
          { pavadinimas: 'Formulės, lentelės', lygis: 2 },
          { pavadinimas: 'Grafikai', generatorius: 'funkcijos', lygis: 2 },
          { pavadinimas: 'Tiesiogiai proporcingi dydžiai', lygis: 2 },
          { pavadinimas: 'Tiesiogiai proporcingų dydžių priklausomybės grafikas', generatorius: 'funkcijos', lygis: 2 },
        ],
        generatorius: 'proporcijos',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Reiškiniai. Lygtys',
        potemes: [
          { pavadinimas: 'Raidinio reiškinio koeficientas', lygis: 2 },
          { pavadinimas: 'Panašiųjų narių sutraukimas', lygis: 2 },
          { pavadinimas: 'Atskliautimas', lygis: 2 },
          { pavadinimas: 'Sprendžiame paprastas lygtis', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Sprendžiame sudėtingesnes lygtis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Sprendžiame lygtis su skliaustais', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Tekstinių uždavinių sprendimas sudarant lygtis', generatorius: 'tiesines-lygtys', lygis: 2 },
        ],
        generatorius: 'raidiniai-reiskiniai',
        lygis: 2,
      },
      {
        numeris: 9,
        pavadinimas: 'Lygios plokštumos figūros',
        potemes: [
          { pavadinimas: 'Lygios plokštumos figūros', lygis: 2 },
          { pavadinimas: 'Trikampio kraštinės ir kampai', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Trikampių lygumo požymis pagal dvi kraštines ir kampą tarp jų', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Trikampių lygumo požymis pagal kraštinę ir du kampus prie jos', lygis: 2 },
          { pavadinimas: 'Trikampių lygumo požymis pagal tris kraštines', lygis: 2 },
          { pavadinimas: 'Braižome kampą, lygų duotam kampui', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Braižome trikampį, lygų duotam trikampiui', lygis: 2 },
          { pavadinimas: 'Trikampio nelygybė', generatorius: 'nelygybes', lygis: 2 },
        ],
        generatorius: 'figuros',
        lygis: 2,
      },
      {
        numeris: 10,
        pavadinimas: 'Panašiosios plokštumos figūros',
        potemes: [
          { pavadinimas: 'Didiname ir mažiname', lygis: 2 },
          { pavadinimas: 'Mastelis', generatorius: 'proporcijos', lygis: 2 },
          { pavadinimas: 'Panašiosios plokštumos figūros', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Trikampių panašumo požymiai', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Figūrų didinimas, mažinimas ir figūrų sekos', generatorius: 'rekurencios-sekos', lygis: 2 },
          { pavadinimas: 'Metrinė matavimo sistema ir vienetų keitimas', lygis: 2 },
        ],
        generatorius: 'trigonometrija',
        lygis: 2,
      },
      {
        numeris: 11,
        pavadinimas: 'Duomenys',
        potemes: [
          { pavadinimas: 'Dažnių lentelė', lygis: 2 },
          { pavadinimas: 'Stulpelinė diagrama', lygis: 2 },
          { pavadinimas: 'Linijinė diagrama', lygis: 2 },
          { pavadinimas: 'Imties vidurkis', generatorius: 'vidurkis', lygis: 2 },
          { pavadinimas: 'Imties mediana', generatorius: 'vidurkis', lygis: 2 },
          { pavadinimas: 'Imties moda', generatorius: 'vidurkis', lygis: 2 },
        ],
        generatorius: 'diagramos',
        lygis: 2,
      },
      {
        numeris: 12,
        pavadinimas: 'Tikimybės',
        potemes: [
          { pavadinimas: 'Galimybių medis', lygis: 2 },
          { pavadinimas: 'Galimybių lentelė', lygis: 2 },
          { pavadinimas: 'Daugybos taisyklė', lygis: 2 },
          { pavadinimas: 'Įvykis', generatorius: 'tikimybe', lygis: 2 },
          { pavadinimas: 'Įvykio tikimybė', generatorius: 'tikimybe', lygis: 2 },
          { pavadinimas: 'Įvykiui priešingas įvykis ir jo tikimybė', generatorius: 'tikimybe', lygis: 2 },
        ],
        generatorius: 'kombinatorika',
        lygis: 2,
      },
    ],
  },

  {
    klase: 7,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Teiginiai',
        potemes: [
          { pavadinimas: 'Teisingi ir klaidingi teiginiai', generatorius: 'logika' },
          { pavadinimas: 'Aksioma, apibrėžimas, teorema', generatorius: 'logika' },
          { pavadinimas: 'Įrodymas', generatorius: 'logika' },
        ],
      },
      {
        numeris: 2,
        pavadinimas: 'Laipsniai',
        potemes: [
          { pavadinimas: 'Keliame kvadratu ir kubu', lygis: 2 },
          { pavadinimas: 'Laipsnis su natūraliuoju rodikliu', lygis: 2 },
          { pavadinimas: 'Dauginame ir dalijame laipsnius su vienodais pagrindais', lygis: 2 },
          { pavadinimas: 'Dauginame ir dalijame laipsnius su vienodais rodikliais', lygis: 2 },
          { pavadinimas: 'Laipsnį keliame laipsniu', lygis: 2 },
          { pavadinimas: 'Laipsnis su sveikuoju neigiamuoju rodikliu', lygis: 2 },
          { pavadinimas: 'Laipsnio su sveikuoju neigiamuoju rodikliu savybės', lygis: 2 },
          { pavadinimas: 'Standartinė skaičiaus išraiška', lygis: 2 },
        ],
        generatorius: 'laipsniai',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Procentai',
        potemes: [
          { pavadinimas: 'Ieškome, kiek procentų pakito dydis', lygis: 2 },
          { pavadinimas: 'Ieškome dydžio, kai žinoma jo pradinė vertė ir pokytis procentais', lygis: 2 },
          { pavadinimas: 'Paprastosios palūkanos', generatorius: 'palukanos', lygis: 2 },
          { pavadinimas: 'Sudėtinės palūkanos', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Sudėtiniai procentai', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Biudžetas, finansiniai tikslai ir paskolų pasiūlymų palyginimas', generatorius: 'palukanos', lygis: 2 },
        ],
        generatorius: 'procentai',
        lygis: 2,
      },
      {
        numeris: 4,
        pavadinimas: 'Nelygybės',
        potemes: [
          { pavadinimas: 'Skaičių palyginimas', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Skaičių intervalai', lygis: 2 },
          { pavadinimas: 'Prie (iš) abiejų nelygybės pusių pridedame (atimame) tą patį skaičių', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Abi nelygybės puses dauginame (dalijame) iš to paties skaičiaus', lygis: 2 },
          { pavadinimas: 'Nelygybės sprendinys', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Sprendžiame vieno žingsnio nelygybes', lygis: 2 },
          { pavadinimas: 'Sprendžiame paprastas nelygybes', lygis: 2 },
          { pavadinimas: 'Sprendžiame sudėtingesnes nelygybes', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Dviejų nelygybių su vienu nežinomuoju sistema', lygis: 2 },
          { pavadinimas: 'Dvigubųjų nelygybių sprendimas', lygis: 2 },
          { pavadinimas: 'Sprendžiame tekstinius uždavinius', lygis: 2 },
        ],
        generatorius: 'nelygybes',
        lygis: 2,
      },
      {
        numeris: 5,
        pavadinimas: 'Atvirkštinis proporcingumas',
        potemes: [
          { pavadinimas: 'Tarpusavyje susiję dydžiai', lygis: 2 },
          { pavadinimas: 'Atvirkščiai proporcingi dydžiai', generatorius: 'atvirkstinis', lygis: 2 },
          { pavadinimas: 'Atvirkščiai proporcingų dydžių priklausomybės grafikas', generatorius: 'atvirkstinis', lygis: 2 },
          { pavadinimas: 'Tekstinių uždavinių sprendimas', lygis: 2 },
        ],
        generatorius: 'proporcijos',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Tiesės',
        potemes: [
          { pavadinimas: 'Taškas ir tiesė', lygis: 2 },
          { pavadinimas: 'Susikertančiosios tiesės', lygis: 2 },
          { pavadinimas: 'Lygiagrečiosios tiesės', lygis: 2 },
          { pavadinimas: 'Dviejų tiesių lygiagretumo požymiai', lygis: 2 },
          { pavadinimas: 'Kampų, susidariusių dvi lygiagrečiąsias tieses perkirtus kirstine, savybės', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Konstravimas ir transformacijos koordinačių plokštumoje', generatorius: 'simetrija', lygis: 2 },
        ],
        generatorius: 'trigonometrija',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Trikampiai ir keturkampiai',
        potemes: [
          { pavadinimas: 'Trikampių rūšys', lygis: 2 },
          { pavadinimas: 'Trikampio aukštinės', lygis: 2 },
          { pavadinimas: 'Trikampio pusiaukraštinės', lygis: 2 },
          { pavadinimas: 'Trikampio pusiaukampinės', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Lygiagretainis', lygis: 2 },
          { pavadinimas: 'Stačiakampis', generatorius: 'trigonometrija', lygis: 2 },
          { pavadinimas: 'Rombas', lygis: 2 },
          { pavadinimas: 'Kvadratas', generatorius: 'trigonometrija', lygis: 2 },
          { pavadinimas: 'Trapecija', lygis: 2 },
          { pavadinimas: 'Lygiašonė ir stačioji trapecijos', lygis: 2 },
          { pavadinimas: 'Daugiakampiai koordinačių plokštumoje', lygis: 2 },
        ],
        generatorius: 'figuros',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Trikampių ir keturkampių plotai',
        potemes: [
          { pavadinimas: 'Stačiakampio, kvadrato ir stačiojo trikampio plotų formulės', lygis: 2 },
          { pavadinimas: 'Trikampio ploto formulė', lygis: 2 },
          { pavadinimas: 'Lygiagretainio ploto formulė', lygis: 2 },
          { pavadinimas: 'Rombo ploto formulė', lygis: 2 },
          { pavadinimas: 'Trapecijos ploto formulė', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 2,
      },
      {
        numeris: 9,
        pavadinimas: 'Apskritimas ir skritulys',
        potemes: [
          { pavadinimas: 'Apskritimas', lygis: 2 },
          { pavadinimas: 'Apskritimo ilgis', lygis: 2 },
          { pavadinimas: 'Apskritimo lankas ir jo ilgis', lygis: 2 },
          { pavadinimas: 'Skritulys. Skritulio ir jo dalies plotai', lygis: 2 },
        ],
        generatorius: 'apskritimas',
        lygis: 2,
      },
      {
        numeris: 10,
        pavadinimas: 'Stačioji prizmė ir taisyklingoji piramidė',
        potemes: [
          { pavadinimas: 'Tiesės ir plokštumos erdvėje', lygis: 2 },
          { pavadinimas: 'Stačioji prizmė', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Stačiosios prizmės tūris', lygis: 2 },
          { pavadinimas: 'Piramidė', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Taisyklingoji piramidė ir jos tūris', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 2,
      },
      {
        numeris: 11,
        pavadinimas: 'Ritinys ir kūgis',
        potemes: [
          { pavadinimas: 'Ritinys', lygis: 2 },
          { pavadinimas: 'Ritinio paviršiaus plotas ir tūris', lygis: 2 },
          { pavadinimas: 'Kūgis', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Kūgio paviršiaus plotas ir tūris', generatorius: 'plotas-turis', lygis: 2 },
        ],
        generatorius: 'apskritimas',
        lygis: 2,
      },
      {
        numeris: 12,
        pavadinimas: 'Duomenys',
        potemes: [
          { pavadinimas: 'Statistinis tyrimas. Populiacija', lygis: 2 },
          { pavadinimas: 'Imtis. Paprastoji atsitiktinė imtis', lygis: 2 },
          { pavadinimas: 'Sisteminė, sluoksninė, lizdinė atsitiktinės imtys', lygis: 2 },
          { pavadinimas: 'Statistinis kintamasis', lygis: 2 },
          { pavadinimas: 'Duomenų pateikimas skrituline diagrama', generatorius: 'apskritimas', lygis: 2 },
        ],
        generatorius: 'vidurkis',
        lygis: 2,
      },
    ],
  },

  {
    klase: 8,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Kvadratinė ir kubinė šaknys',
        potemes: [
          { pavadinimas: 'Kvadratinė šaknis', generatorius: 'saknys', lygis: 2 },
          { pavadinimas: 'Kubinė šaknis', generatorius: 'saknys', lygis: 3 },
          { pavadinimas: 'Iracionalieji skaičiai', lygis: 3 },
          { pavadinimas: 'Palyginame', generatorius: 'skaiciu-palyginimas', lygis: 3 },
          { pavadinimas: 'Sudedame ir atimame', generatorius: 'sudetis-atimtis', lygis: 3 },
          { pavadinimas: 'Šaknis iš sandaugos', lygis: 3 },
          { pavadinimas: 'Šaknis iš trupmenos', lygis: 3 },
          { pavadinimas: 'Iškeliame prieš šaknies ženklą, įkeliame į pošaknį', lygis: 3 },
          { pavadinimas: 'Skaitinių reiškinių su šaknimis pertvarkiai', lygis: 3 },
          { pavadinimas: 'Raidinių reiškinių su šaknimis pertvarkiai', lygis: 3 },
        ],
        generatorius: 'saknu-ivertinimas',
        lygis: 3,
      },
      {
        numeris: 2,
        pavadinimas: 'Skaičių aibės',
        potemes: [
          { pavadinimas: 'Skaičių aibės', lygis: 3 },
          { pavadinimas: 'Skaičių aibės poaibis', lygis: 3 },
          { pavadinimas: 'Realieji skaičiai', lygis: 3 },
          { pavadinimas: 'Veiksmai su realiaisiais skaičiais', lygis: 3 },
        ],
        generatorius: 'saknu-ivertinimas',
        lygis: 3,
      },
      {
        numeris: 3,
        pavadinimas: 'Finansiniai skaičiavimai',
        potemes: [
          { pavadinimas: 'Valiutų kursai', lygis: 3 },
          { pavadinimas: 'Paprastosios ir sudėtinės palūkanos', generatorius: 'sudetis-atimtis', lygis: 3 },
          { pavadinimas: 'Paprastosios palūkanos ir grafikai', lygis: 3 },
          { pavadinimas: 'Pirkimas išsimokėtinai', lygis: 3 },
          { pavadinimas: 'Mažėjančiosios palūkanos', lygis: 3 },
        ],
        generatorius: 'palukanos',
        lygis: 3,
      },
      {
        numeris: 4,
        pavadinimas: 'Reiškiniai',
        potemes: [
          { pavadinimas: 'Vienanaris ir daugianaris', generatorius: 'raidiniai-reiskiniai', lygis: 3 },
          { pavadinimas: 'Atskliautimas', generatorius: 'raidiniai-reiskiniai', lygis: 3 },
          { pavadinimas: 'Daugianarių daugyba', generatorius: 'raidiniai-reiskiniai', lygis: 3 },
          { pavadinimas: 'Dvinario kėlimas kvadratu', lygis: 3 },
          { pavadinimas: 'Dviejų narių sumos dauginimas iš tų narių skirtumo', lygis: 3 },
          { pavadinimas: 'Bendrojo dauginamojo iškėlimas prieš skliaustus', lygis: 3 },
          { pavadinimas: 'Skaidymas dauginamaisiais grupavimo būdu', lygis: 3 },
          { pavadinimas: 'Skaidymas dauginamaisiais taikant greitosios daugybos formules', lygis: 3 },
          { pavadinimas: 'Dvinario kvadrato išskyrimas', lygis: 3 },
        ],
        generatorius: 'greitosios-formules',
        lygis: 3,
      },
      {
        numeris: 5,
        pavadinimas: 'Tiesinių lygčių sistemos',
        potemes: [
          { pavadinimas: 'Tiesinė lygtis su dviem nežinomaisiais', generatorius: 'tiesines-lygtys', lygis: 3 },
          { pavadinimas: 'Tiesinės lygties su dviem nežinomaisiais grafikas', generatorius: 'funkcijos', lygis: 3 },
          { pavadinimas: 'Tiesinių lygčių su dviem nežinomaisiais sistema', lygis: 3 },
          { pavadinimas: 'Tiesinių lygčių sistemos sprendinių skaičius', lygis: 3 },
          { pavadinimas: 'Sprendžiame tiesinių lygčių sistemas keitimo būdu', lygis: 3 },
          { pavadinimas: 'Sprendžiame tiesinių lygčių sistemas sulyginimo būdu', lygis: 3 },
          { pavadinimas: 'Sprendžiame tiesinių lygčių sistemas sudėties būdu', generatorius: 'sudetis-atimtis', lygis: 3 },
          { pavadinimas: 'Judėjimo uždaviniai', lygis: 3 },
          { pavadinimas: 'Įvairūs tekstiniai uždaviniai', lygis: 3 },
          { pavadinimas: 'Tiesinis sąryšis: lentelė, formulė ir grafikas', generatorius: 'funkcijos', lygis: 3 },
        ],
        generatorius: 'lygciu-sistemos',
        lygis: 3,
      },
      {
        numeris: 6,
        pavadinimas: 'Vektoriai',
        potemes: [
          { pavadinimas: 'Vektoriaus sąvoka', lygis: 3 },
          { pavadinimas: 'Vektorių lygumas', lygis: 3 },
          { pavadinimas: 'Vektorių sudėtis', generatorius: 'sudetis-atimtis', lygis: 3 },
          { pavadinimas: 'Vektorių atimtis', generatorius: 'sudetis-atimtis', lygis: 3 },
          { pavadinimas: 'Vektoriaus daugyba iš skaičiaus', lygis: 3 },
        ],
        generatorius: 'vektoriai',
        lygis: 3,
      },
      {
        numeris: 7,
        pavadinimas: 'Plokštumos figūros',
        potemes: [
          { pavadinimas: 'Pitagoro teorema', generatorius: 'pitagoras', lygis: 3 },
          { pavadinimas: 'Atvirkštinė Pitagoro teorema', generatorius: 'atvirkstinis', lygis: 3 },
          { pavadinimas: 'Atstumas tarp dviejų koordinačių plokštumos taškų', generatorius: 'pitagoras', lygis: 3 },
          { pavadinimas: 'Stačiojo trikampio statinis, esantis prieš 30° kampą', generatorius: 'kampai', lygis: 3 },
          { pavadinimas: 'Lygiašonis ir lygiakraštis trikampiai', lygis: 3 },
          { pavadinimas: 'Trikampio vidurio linija', lygis: 3 },
          { pavadinimas: 'Trapecijos vidurio linija', lygis: 3 },
        ],
        generatorius: 'figuros',
        lygis: 3,
      },
      {
        numeris: 8,
        pavadinimas: 'Erdviniai kūnai',
        potemes: [
          { pavadinimas: 'Stačioji prizmė', lygis: 3 },
          { pavadinimas: 'Taisyklingoji piramidė', lygis: 3 },
          { pavadinimas: 'Ritinys', generatorius: 'apskritimas', lygis: 3 },
          { pavadinimas: 'Kūgis', lygis: 3 },
          { pavadinimas: 'Rutulys ir sfera', lygis: 3 },
          { pavadinimas: 'Objekto vaizdai iš viršaus, priekio ir šono bei mastelis', generatorius: 'proporcijos', lygis: 3 },
        ],
        generatorius: 'erdvines-figuros',
        lygis: 3,
      },
      {
        numeris: 9,
        pavadinimas: 'Duomenys',
        potemes: [
          { pavadinimas: 'Empirinis skirstinys', generatorius: 'sklaida', lygis: 3 },
          { pavadinimas: 'Sukauptasis ir sukauptasis santykinis dažniai', lygis: 3 },
          { pavadinimas: 'Sugrupuotų duomenų stulpelinė diagrama', lygis: 3 },
          { pavadinimas: 'Histograma', lygis: 3 },
          { pavadinimas: 'Imties skaitinės charakteristikos', generatorius: 'vidurkis', lygis: 3 },
          { pavadinimas: 'Kvartiliai', generatorius: 'sklaida', lygis: 3 },
          { pavadinimas: 'Stačiakampė diagrama su „ūsais“', lygis: 3 },
        ],
        generatorius: 'diagramos',
        lygis: 3,
      },
      {
        numeris: 10,
        pavadinimas: 'Progimnazijos kurso kartojimo medžiaga',
        potemes: [
          { pavadinimas: 'Skaičių aibės', generatorius: 'saknu-ivertinimas', lygis: 3 },
          { pavadinimas: 'Skaičių dalumas', generatorius: 'dalumo-pozymiai', lygis: 3 },
          { pavadinimas: 'Aritmetiniai veiksmai su skaičiais', generatorius: 'skaitmenys', lygis: 3 },
          { pavadinimas: 'Paprastosios trupmenos', generatorius: 'trupmenu-sudetis', lygis: 3 },
          { pavadinimas: 'Proporcingumas', generatorius: 'proporcijos', lygis: 3 },
          { pavadinimas: 'Procentai', generatorius: 'procentai', lygis: 3 },
          { pavadinimas: 'Laipsniai. Šaknys', generatorius: 'laipsniai', lygis: 3 },
          { pavadinimas: 'Raidininiai reiškiniai', generatorius: 'raidiniai-reiskiniai', lygis: 3 },
          { pavadinimas: 'Lygtys, lygčių sistemos', generatorius: 'lygciu-sistemos', lygis: 3 },
          { pavadinimas: 'Nelygybės, nelygybių sistemos', generatorius: 'nelygybes', lygis: 3 },
          { pavadinimas: 'Kampai', generatorius: 'kampai', lygis: 3 },
          { pavadinimas: 'Trikampiai', lygis: 3 },
          { pavadinimas: 'Keturkampiai. Daugiakampiai', lygis: 3 },
          { pavadinimas: 'Apskritimas. Skritulys', generatorius: 'apskritimas', lygis: 3 },
          { pavadinimas: 'Vektoriai', generatorius: 'vektoriai', lygis: 3 },
          { pavadinimas: 'Simetrija. Posūkis. Postūmis', generatorius: 'simetrija', lygis: 3 },
          { pavadinimas: 'Erdviniai kūnai', generatorius: 'erdvines-figuros', lygis: 3 },
          { pavadinimas: 'Rinkinių skaičius. Statistika', generatorius: 'kombinatorika', lygis: 3 },
          { pavadinimas: 'Tikimybės', generatorius: 'tikimybe', lygis: 3 },
        ],
        generatorius: 'pupp',
        lygis: 3,
      },
    ],
  },

  {
    klase: 9,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Funkcijos, sekos',
        potemes: [
          { pavadinimas: 'Tarpusavyje susiję dydžiai', lygis: 3 },
          { pavadinimas: 'Funkcija ir jos grafikas', lygis: 3 },
          { pavadinimas: 'Funkcijos savybės', lygis: 3 },
          { pavadinimas: 'Skaičių seka', generatorius: 'rekurencios-sekos', lygis: 3 },
          { pavadinimas: 'Skaičių sekos, išreikštos rekurentiškai', generatorius: 'rekurencios-sekos', lygis: 3 },
          { pavadinimas: 'Funkcijos apibrėžimo ir reikšmių sritys', lygis: 3 },
        ],
        generatorius: 'funkcijos',
        lygis: 3,
      },
      {
        numeris: 2,
        pavadinimas: 'Tiesinė funkcija',
        potemes: [
          { pavadinimas: 'Tiesioginio proporcingumo funkcija', lygis: 3 },
          { pavadinimas: 'Tiesinė funkcija', lygis: 3 },
          { pavadinimas: 'Tiesinės funkcijos savybės', lygis: 3 },
          { pavadinimas: 'Dviejų tiesių tarpusavio padėtis', lygis: 3 },
        ],
        generatorius: 'funkcijos',
        lygis: 3,
      },
      {
        numeris: 3,
        pavadinimas: 'Kvadratinė lygtis',
        potemes: [
          { pavadinimas: 'Kvadratinės lygties samprata', lygis: 3 },
          { pavadinimas: 'Nepilnosios kvadratinės lygtys', generatorius: 'kvadratines-lygtys', lygis: 3 },
          { pavadinimas: 'Pilnoji kvadratinė lygtis', generatorius: 'tiesines-lygtys', lygis: 3 },
          { pavadinimas: 'Kvadratinės lygties sprendinių formulės', generatorius: 'kvadratines-lygtys', lygis: 3 },
          { pavadinimas: 'Kvadratinio trinario skaidymas dauginamaisiais', generatorius: 'greitosios-formules', lygis: 3 },
          { pavadinimas: 'Vijeto teorema', lygis: 3 },
        ],
        generatorius: 'vijeto',
        lygis: 3,
      },
      {
        numeris: 4,
        pavadinimas: 'Kvadratinė funkcija',
        potemes: [
          { pavadinimas: 'Kvadratinės funkcijos samprata', lygis: 3 },
          { pavadinimas: 'Grafiko transformacijos', generatorius: 'funkcijos', lygis: 3 },
          { pavadinimas: 'Kvadratinės funkcijos grafikas ir savybės', lygis: 3 },
        ],
        generatorius: 'kvadratines-lygtys',
        lygis: 3,
      },
      {
        numeris: 5,
        pavadinimas: 'Trupmeniniai racionalieji reiškiniai',
        potemes: [
          { pavadinimas: 'Trupmeninio racionaliojo reiškinio samprata', generatorius: 'trupmenu-sudetis', lygis: 3 },
          { pavadinimas: 'Trupmeninių racionaliųjų reiškinių daugyba, dalyba ir kėlimas laipsniu', generatorius: 'laipsniai', lygis: 3 },
          { pavadinimas: 'Trupmeninių racionaliųjų reiškinių sudėtis ir atimtis', lygis: 3 },
          { pavadinimas: 'Sudėtingesnių uždavinių sprendimas', lygis: 3 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 3,
      },
      {
        numeris: 6,
        pavadinimas: 'Lygčių sistemos',
        potemes: [
          { pavadinimas: 'Lygčių sistemų sprendimas algebriniais būdais', lygis: 3 },
          { pavadinimas: 'Lygčių sistemų sprendimas grafiniu būdu', lygis: 3 },
          { pavadinimas: 'Sudėtingesnių lygčių sistemų sprendimas', generatorius: 'sudetis-atimtis', lygis: 3 },
        ],
        generatorius: 'lygciu-sistemos',
        lygis: 3,
      },
      {
        numeris: 7,
        pavadinimas: 'Įvadas į trigonometriją',
        potemes: [
          { pavadinimas: 'Smailiojo kampo sinusas, kosinusas ir tangentas', lygis: 3 },
          { pavadinimas: 'Trigonometrinių santykių reikšmės', lygis: 3 },
          { pavadinimas: 'Skaičiuojame skaičiuotuvu', lygis: 3 },
          { pavadinimas: 'Trigonometrinės formulės', lygis: 3 },
          { pavadinimas: 'Stačiųjų trikampių sprendimas', generatorius: 'figuros', lygis: 3 },
        ],
        generatorius: 'trigonometrija',
        lygis: 3,
      },
      {
        numeris: 8,
        pavadinimas: 'Apskritimas ir skritulys',
        potemes: [
          { pavadinimas: 'Apskritimo liestinė ir kirstinė', lygis: 3 },
          { pavadinimas: 'Apskritimo centrinis ir įbrėžtinis kampai', lygis: 3 },
          { pavadinimas: 'Apskritimo stygų savybės', lygis: 3 },
          { pavadinimas: 'Skritulio išpjova ir nuopjova', lygis: 3 },
          { pavadinimas: 'Kirstinių, liestinių, stygų proporcingos atkarpos ir sudaromi kampai', generatorius: 'kampai', lygis: 3 },
        ],
        generatorius: 'apskritimas',
        lygis: 3,
      },
      {
        numeris: 9,
        pavadinimas: 'Duomenys ir jų interpretavimas',
        potemes: [
          { pavadinimas: 'Sklaidos diagrama', generatorius: 'diagramos', lygis: 3 },
          { pavadinimas: 'Tiesinė koreliacija', lygis: 3 },
          { pavadinimas: 'Tiesė sklaidos diagramo', generatorius: 'diagramos', lygis: 3 },
          { pavadinimas: 'Imties dydžio ir atsitiktinumo įtaka išvadoms', lygis: 3 },
          { pavadinimas: 'Koreliacija nėra priežastinis ryšys', lygis: 3 },
        ],
        generatorius: 'vidurkis',
        lygis: 3,
      },
    ],
  },

  {
    klase: 10,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Trupmeninė racionalioji lygtis',
        potemes: [
          { pavadinimas: 'Trupmeninės racionaliosios lygties samprata', generatorius: 'trupmenu-sudetis', lygis: 3 },
          { pavadinimas: 'Lygčių sprendimas taikant trupmenos, lygios nuliui, savybę', lygis: 3 },
          { pavadinimas: 'Kiti trupmeninių lygčių sprendimo būdai', lygis: 3 },
          { pavadinimas: 'Judėjimo uždaviniai', lygis: 3 },
          { pavadinimas: 'Darbo uždaviniai', lygis: 3 },
          { pavadinimas: 'Mišiniai', generatorius: 'misiniai', lygis: 3 },
        ],
        generatorius: 'tiesines-lygtys',
        lygis: 3,
      },
      {
        numeris: 2,
        pavadinimas: 'Trigonometrijos pagrindai',
        potemes: [
          { pavadinimas: 'Posūkio kampo sinusas, kosinusas ir tangentas', lygis: 3 },
          { pavadinimas: 'Sinuso, kosinuso ir tangento reikšmės', lygis: 3 },
          { pavadinimas: 'Trikampio ploto skaičiavimo formulė', generatorius: 'plotas-turis', lygis: 3 },
          { pavadinimas: 'Sinusų teorema', lygis: 3 },
          { pavadinimas: 'Kosinusų teorema', lygis: 3 },
        ],
        generatorius: 'trigonometrija',
        lygis: 3,
      },
      {
        numeris: 3,
        pavadinimas: 'Lygčių su dviem nežinomaisiais sistemos',
        potemes: [
          { pavadinimas: 'Lygčių su dviem nežinomaisiais sistema ir jos sprendiniai', lygis: 3 },
          { pavadinimas: 'Atvirkštinio proporcingumo funkcija', generatorius: 'atvirkstinis', lygis: 3 },
          { pavadinimas: 'Lygčių sistemų sprendimas grafiniu būdu', lygis: 3 },
          { pavadinimas: 'Lygčių sistemų sprendimas algebriniais būdais', lygis: 3 },
          { pavadinimas: 'Uždavinių sprendimas, sudarant lygčių sistemas', lygis: 3 },
          { pavadinimas: 'Lygčių sistemų sprendimas, įvedant keitinius', lygis: 3 },
        ],
        generatorius: 'lygciu-sistemos',
        lygis: 3,
      },
      {
        numeris: 4,
        pavadinimas: 'Nelygybės ir jų sistemos',
        potemes: [
          { pavadinimas: 'Kvadratinės nelygybės samprata', lygis: 3 },
          { pavadinimas: 'Kvadratinės nelygybės sprendimas, remiantis parabolės savybėmis', lygis: 3 },
          { pavadinimas: 'Kvadratinės nelygybės keitimas nelygybių sistemomis', lygis: 3 },
          { pavadinimas: 'Kvadratinių nelygybių taikymas', lygis: 3 },
          { pavadinimas: 'Nelygybių sistemos ir dvigubosios nelygybės', lygis: 3 },
          { pavadinimas: 'Trupmeninių nelygybių sprendimas', lygis: 3 },
        ],
        generatorius: 'nelygybes',
        lygis: 3,
      },
      {
        numeris: 5,
        pavadinimas: 'Dėsningumai, santykiai ir procentai',
        potemes: [
          { pavadinimas: 'Probleminės situacijos ir trūkstamos informacijos nustatymas', lygis: 3 },
          { pavadinimas: 'Proporcingoji dalyba į dvi nelygias dalis', generatorius: 'sveikieji', lygis: 3 },
          { pavadinimas: 'Fibonačio skaičių seka', lygis: 3 },
          { pavadinimas: 'Aukso pjūvio skaičius ir aukso pjūvio seka', lygis: 3 },
          { pavadinimas: 'Sudėtiniai procentai', generatorius: 'sudetis-atimtis', lygis: 3 },
          { pavadinimas: 'Džiovinimo ir drėkinimo uždaviniai', lygis: 3 },
          { pavadinimas: 'Lydiniai, mišiniai, tirpalai ir koncentracija', generatorius: 'misiniai', lygis: 3 },
        ],
        generatorius: 'rekurencios-sekos',
        lygis: 3,
      },
      {
        numeris: 6,
        pavadinimas: 'Plokštumos figūros',
        potemes: [
          { pavadinimas: 'Panašiųjų figūrų perimetrų ir plotų santykiai', generatorius: 'perimetras', lygis: 3 },
          { pavadinimas: 'Trikampio pusiaukampinių savybės', generatorius: 'kampai', lygis: 3 },
          { pavadinimas: 'Trikampio pusiaukraštinių savybės', lygis: 3 },
          { pavadinimas: 'Į trikampį įbrėžtas apskritimas', generatorius: 'apskritimas', lygis: 3 },
          { pavadinimas: 'Apie trikampį apibrėžtas apskritimas', generatorius: 'apskritimas', lygis: 3 },
          { pavadinimas: 'Trikampio ploto formulės S = rp ir S = abc/(4R)', generatorius: 'plotas-turis', lygis: 3 },
          { pavadinimas: 'Įbrėžtiniai ir apibrėžtiniai keturkampiai', lygis: 3 },
          { pavadinimas: 'Geometrinių teiginių įrodymas', generatorius: 'trigonometrija', lygis: 3 },
        ],
        generatorius: 'figuros',
        lygis: 3,
      },
      {
        numeris: 7,
        pavadinimas: 'Duomenys ir jų interpretavimas',
        potemes: [
          { pavadinimas: 'Populiacija, imtis ir pagrįstos išvados', generatorius: 'vidurkis', lygis: 3 },
          { pavadinimas: 'Duomenų kintamumas ir pasiskirstymas', generatorius: 'vidurkis', lygis: 3 },
          { pavadinimas: 'Dispersija ir standartinis nuokrypis', lygis: 3 },
          { pavadinimas: 'Normalusis, simetriškasis ir asimetriškasis skirstiniai', generatorius: 'simetrija', lygis: 3 },
          { pavadinimas: 'Duomenų centro ir sklaidos charakteristikų interpretavimas', lygis: 3 },
          { pavadinimas: 'Statistinis patikimumas', lygis: 3 },
        ],
        generatorius: 'sklaida',
        lygis: 3,
      },
      {
        numeris: 8,
        pavadinimas: 'Rinkiniai, kombinatorika ir tikimybės',
        potemes: [
          { pavadinimas: 'Kelių elementų rinkiniai', lygis: 3 },
          { pavadinimas: 'Elementų tvarka rinkinyje', lygis: 3 },
          { pavadinimas: 'Rinkinių skaičiaus apskaičiavimas', lygis: 3 },
          { pavadinimas: 'Kombinatorikos sudėties taisyklė', generatorius: 'sudetis-atimtis', lygis: 3 },
          { pavadinimas: 'Kombinatorikos daugybos taisyklė', lygis: 3 },
          { pavadinimas: 'Teorinė ir eksperimentinė tikimybė', generatorius: 'tikimybe', lygis: 3 },
          { pavadinimas: 'Ilgalaikis santykinis dažnis', generatorius: 'diagramos', lygis: 3 },
        ],
        generatorius: 'kombinatorika',
        lygis: 3,
      },
    ],
  },
]

/** Kiek programos temų jau turi uždavinių generatorių. */
export function padengimas(): { isViso: number; suGeneratoriumi: number } {
  const visos = programa.flatMap((k) => k.temos)
  return {
    isViso: visos.length,
    suGeneratoriumi: visos.filter((t) => t.generatorius).length,
  }
}
