/**
 * Matematikos programa 1–10 klasėms.
 *
 * ŠIS FAILAS YRA DUOMENYS, NE LOGIKA — kaip ir `lib/temos.ts`.
 * Surašyta pagal `uzdaviniu-temos.md`. Stambieji punktai (1., 2., 3.) yra
 * programos skyriai; jie rodomi paryškinti. `potemes` — smulkesnis skirstymas.
 *
 * `generatorius` nurodo raktą iš `lib/generatoriai/index.ts`. Jei jo nėra,
 * tema svetainėje rodoma, bet uždavinių kol kas negeneruoja — taip matyti,
 * kur biblioteką verta pildyti toliau.
 */

import type { Sritis } from './generatoriai/sritis'

export type Lygis = 1 | 2
export type { Sritis }

/**
 * Potemė. Paprasčiausiu atveju tai tik pavadinimas — tada ji paveldi savo
 * temos generatorių. Objekto forma naudojama tada, kai potemei tinka kitas
 * generatorius nei visai temai (pvz. 8 kl. „Kvadratinė ir kubinė šaknys"
 * temoje „Skaičiai ir skaičiavimai").
 */
export type Potema =
  | string
  | {
      pavadinimas: string
      generatorius?: string
      lygis?: Lygis
      /** Siauresnė sritis nei temos — pvz. potemė vien apie dešimtis. */
      sritis?: Sritis
    }

export type ProgramosTema = {
  /** Stambiojo punkto numeris klasėje: 1., 2., 3. */
  numeris: number
  pavadinimas: string
  potemes?: Potema[]
  generatorius?: string
  /** Sunkumo lygis, kuriuo tema generuojama pagal nutylėjimą. */
  lygis?: Lygis
  /**
   * Skaičių sritis, už kurios negali atsidurti nė vienas temos skaičius.
   *
   * Riba temos *pavadinime* („Skaičiai nuo 0 iki 100") generatoriui nieko
   * nereiškia — jam reikia lauko. Nenurodžius galioja klasės numatytoji
   * sritis iš `SRITIS_PAGAL_KLASE`; 5–10 klasėse ribos netaikomos.
   */
  sritis?: Sritis
}

export type ProgramosKlase = {
  klase: number
  temos: ProgramosTema[]
}

/** Potemė su galutiniu numeriu ir generatoriumi — jau paveldėtu iš temos. */
export type IsskleistaPotema = {
  /** „3.2" pavidalu. */
  numeris: string
  pavadinimas: string
  generatorius?: string
  lygis: Lygis
  /** Paveldėta potemė → tema; `undefined` reiškia klasės numatytąją. */
  sritis?: Sritis
}

/**
 * Potemės su numeriais, generatoriais ir sritimis. Potemė be savo
 * generatoriaus paveldi temos generatorių, tad paspaudus bet kurią gaunami
 * uždaviniai; taip pat paveldima ir sritis.
 */
export function potemes(tema: ProgramosTema): IsskleistaPotema[] {
  return (tema.potemes ?? []).map((p, i) => {
    const objektas = typeof p === 'string' ? { pavadinimas: p } : p
    return {
      numeris: `${tema.numeris}.${i + 1}`,
      pavadinimas: objektas.pavadinimas,
      generatorius: objektas.generatorius ?? tema.generatorius,
      lygis: objektas.lygis ?? tema.lygis ?? 2,
      sritis: ('sritis' in objektas ? objektas.sritis : undefined) ?? tema.sritis,
    }
  })
}

export const programa: ProgramosKlase[] = [
  {
    klase: 1,
    temos: [
      {
        numeris: 1,
        sritis: { min: 0, max: 20 },
        pavadinimas: 'Žingsnis į pirmąją klasę',
        potemes: [
          { pavadinimas: 'Kur yra daiktas?', generatorius: 'vieta' },
          { pavadinimas: 'Kaip surikiuoti daiktai?', generatorius: 'daiktu-rikiavimas' },
          { pavadinimas: 'Pagal kokią taisyklę išrikiuoti skaičiai?', generatorius: 'sekos' },
          // Keturios potemės anksčiau dalijosi vienu `skaiciu-palyginimas`
          // generatoriumi ir todėl nė viena negaudavo savo turinio.
          { pavadinimas: 'Kaip rašyti skaičius nuo 0 iki 4?', generatorius: 'skaiciu-rasymas', lygis: 1 },
          { pavadinimas: 'Kaip rašyti skaičius nuo 5 iki 9?', generatorius: 'skaiciu-rasymas', lygis: 2 },
          { pavadinimas: 'Lygu ar nelygu?', generatorius: 'lygu-nelygu' },
          { pavadinimas: 'Daugiau ar mažiau?', generatorius: 'daugiau-maziau' },
        ],
        generatorius: 'skaiciu-palyginimas',
        lygis: 1,
      },
      {
        numeris: 2,
        sritis: { min: 0, max: 9 },
        pavadinimas: 'Sudėtis ir atimtis nuo 0 iki 9',
        potemes: [
          'Kiek yra iš viso?',
          'Kaip sudėti du skaičius?',
          'Kas yra dėmuo ir suma?',
          'Kaip sudėti tris dėmenis?',
          'Kaip spręsti sudėties uždavinius?',
          'Kiek liko?',
          'Kaip atimti skaičių?',
          'Kas yra turinys, atėminys ir skirtumas?',
          'Kaip spręsti atimties uždavinius?',
          'Koks sudėties ir atimties veiksmų ryšys?',
          'Kokio skaičiaus trūksta?',
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 1,
      },
      {
        numeris: 3,
        sritis: { min: 0, max: 20 },
        pavadinimas: 'Dviženkliai skaičiai iki 20',
        potemes: [
          'Kaip sudaryti skaičių 10?',
          { pavadinimas: 'Kaip skaičiuoti iki 20?', generatorius: 'skaiciu-palyginimas' },
          { pavadinimas: 'Kas yra gretimi skaičiai?', generatorius: 'gretimi-skaiciai' },
          { pavadinimas: 'Kas yra dešimtys ir vienetai?', generatorius: 'skaitmenys' },
          { pavadinimas: 'Kaip palyginti dviženklius skaičius?', generatorius: 'skaiciu-palyginimas' },
          'Kaip sudėti skaičius nuo 0 iki 20?',
          'Kaip sudėti skaičius sudarant naują dešimtį?',
          'Kaip atimti skaičius, mažesnius už 20?',
          'Kaip atimti skaičius, mažesnius už 20, išardant dešimtį?',
          'Kas yra tekstinis uždavinys?',
          'Kaip skaičių padidinti arba sumažinti keliais vienetais?',
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 1,
      },
      {
        numeris: 4,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Matavimas ir braižymas',
        potemes: [
          'Kuo matuoti ilgį?',
          'Kas yra centimetras?',
          { pavadinimas: 'Kaip matuoti ilgį?', generatorius: 'lauzes' },
          'Kaip spręsti ilgio matavimo uždavinius?',
          { pavadinimas: 'Kas yra taškas, atkarpa, tiesė ir spindulys?', generatorius: 'figuros' },
          { pavadinimas: 'Kuo skiriasi piešinys ir brėžinys?', generatorius: 'figuros' },
          { pavadinimas: 'Kaip matuoti ir brėžti atkarpas?', generatorius: 'lauzes' },
          { pavadinimas: 'Kaip perskaityti simboliais užrašytą kelią?', generatorius: 'algoritmai' },
          { pavadinimas: 'Kaip nusakomas kelias?', generatorius: 'algoritmai' },
        ],
        generatorius: 'matavimo-vienetai',
        lygis: 1,
      },
      {
        numeris: 5,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Skaičiai nuo 0 iki 100',
        potemes: [
          { pavadinimas: 'Kaip skaičiuoti dešimtimis?', generatorius: 'sekos' },
          { pavadinimas: 'Kokie yra skaičiaus skyriai?', generatorius: 'skaitmenys' },
          // Šios trys anksčiau dalijosi vienu `skaiciu-palyginimas` generatoriumi,
          // todėl visos trys duodavo tą patį palyginimo uždavinį.
          { pavadinimas: 'Kaip skaičiai išrikiuoti šimtalangėje?', generatorius: 'simtalange' },
          { pavadinimas: 'Kaip skaičiai išrikiuoti skaičių tiesėje?', generatorius: 'skaiciu-tiese' },
          'Kaip palyginti skaičius?',
          { pavadinimas: 'Kokius pinigus naudojame Lietuvoje?', generatorius: 'pinigai' },
          { pavadinimas: 'Kokia pinigų vertė?', generatorius: 'pinigai' },
        ],
        generatorius: 'skaiciu-palyginimas',
        lygis: 1,
      },
      {
        numeris: 6,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Tyrinėju reiškinį „Ženklai“',
        potemes: [
          'Kodėl svarbu suprasti ženklus?',
          'Kokius ženklus žmonės vartojo prieš tūkstančius metų?',
          'Kokią informaciją perduoda skaičiai?',
        ],
        generatorius: 'skaitmenys',
        lygis: 1,
      },
      {
        numeris: 7,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Duomenys',
        potemes: [
          'Kas vadinama duomenimis?',
          'Kaip skaityti piktogramą?',
          'Kaip skaityti stulpelinę diagramą?',
          'Kaip nubraižyti stulpelinę diagramą?',
          'Kaip atliekamas tyrimas?',
          'Kaip aš atlieku tyrimą?',
        ],
        generatorius: 'diagramos',
        lygis: 1,
      },
      {
        numeris: 8,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Sudėtis ir atimtis iki 100',
        potemes: [
          'Kaip sudėti dviženklį ir vienaženklį skaičius?',
          'Kiek vienetų trūksta iki pilnos dešimties?',
          'Kaip sudėti eilute dviženklį ir vienaženklį skaičius peržengiant dešimtį?',
          'Kaip sudėti stulpeliu dviženklį ir vienaženklį skaičius peržengiant dešimtį?',
          { pavadinimas: 'Kaip sudėti du dviženklius skaičius?', lygis: 2 },
          'Kaip iš dviženklio skaičiaus atimti vienaženklį?',
          'Kaip atimti eilute iš dviženklio skaičiaus vienaženklį išardant dešimtį?',
          'Kaip atimti stulpeliu iš dviženklio skaičiaus vienaženklį išardant dešimtį?',
          { pavadinimas: 'Kaip atimti dviženklį skaičių?', lygis: 2 },
          'Kaip vaizduoti tekstinius sudėties uždavinius?',
          'Kaip vaizduoti tekstinius atimties uždavinius?',
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 1,
      },
      {
        numeris: 9,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Matai',
        potemes: [
          { pavadinimas: 'Ką rodo laikrodis?', generatorius: 'laikas' },
          { pavadinimas: 'Kiek valandų trunka para?', generatorius: 'laikas' },
          { pavadinimas: 'Kiek laiko užtruko...?', generatorius: 'laikas' },
          { pavadinimas: 'Kam užteks pinigų?', generatorius: 'pinigai' },
          'Kas yra metras?',
          'Kaip spręsti uždavinius su ilgio matavimo vienetu metru?',
          'Kas yra kilogramas?',
          'Sunkesnis ar lengvesnis?',
        ],
        generatorius: 'matavimo-vienetai',
        lygis: 1,
      },
      {
        numeris: 10,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Tyrinėju reiškinį „Miškas“',
        potemes: [
          // Anksčiau sėklos ir aukštis ėjo per `matavimo-vienetai` (kilometrai,
          // litrai), o amžius — per `sudetis-atimtis`, tad „medžio amžius"
          // duodavo uždavinių apie žuvytes akvariume.
          { pavadinimas: 'Kokia medžio sėklos masė?', generatorius: 'misko-sekla' },
          { pavadinimas: 'Kaip išmatuoti medžio aukštį?', generatorius: 'medzio-aukstis' },
          { pavadinimas: 'Kaip apskaičiuoti medžio amžių?', generatorius: 'medzio-amzius' },
        ],
        generatorius: 'medzio-aukstis',
        lygis: 1,
      },
      {
        numeris: 11,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Kompiuterinių programų kūrimas',
        potemes: [
          'Kas yra komanda?',
          'Kas yra algoritmas?',
          { pavadinimas: 'IR ar ARBA?', generatorius: 'logika' },
          'Kaip sukurti programą „Blue-Bot“ robotui?',
          'Kaip naudoti programą „ScratchJr“?',
        ],
        generatorius: 'algoritmai',
        lygis: 1,
      },
      {
        numeris: 12,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Kartojimas',
        potemes: [
          { pavadinimas: 'Skaičiai iki 100', generatorius: 'skaiciu-palyginimas' },
          'Sudėtis ir atimtis',
          { pavadinimas: 'Ilgis ir laikas', generatorius: 'laikas' },
          { pavadinimas: 'Masė ir pinigai', generatorius: 'pinigai' },
          { pavadinimas: 'Figūros', generatorius: 'figuros' },
          { pavadinimas: 'Duomenys', generatorius: 'diagramos' },
          'Tekstiniai uždaviniai',
          { pavadinimas: 'Algoritmai ir programavimas', generatorius: 'algoritmai' },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 1,
      },
    ],
  },
  {
    klase: 2,
    temos: [
      {
        numeris: 1,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Skaičiai ir skaičiavimai nuo 0 iki 100',
        potemes: [
          { pavadinimas: 'Ką jau žinau apie skaičius nuo 0 iki 100?', generatorius: 'skaiciu-palyginimas' },
          { pavadinimas: 'Pagal kokią taisyklę sudaryta seka?', generatorius: 'sekos' },
          'Kurį sudėties būdą pasirinksi?',
          'Kurį atimties būdą pasirinksi?',
          'Kaip rasti nežinomą skaičių?',
          { pavadinimas: 'Kaip eilute sudėti du dviženklius skaičius peržengiant dešimtį?', lygis: 2 },
          { pavadinimas: 'Kaip stulpeliu sudėti du dviženklius skaičius peržengiant dešimtį?', lygis: 2 },
          { pavadinimas: 'Kaip iš pilnų dešimčių atimti dviženklį skaičių išardant dešimtį?', lygis: 2 },
          { pavadinimas: 'Kaip eilute iš dviženklio skaičiaus atimti dviženklį išskaidant atėminį?', lygis: 2 },
          { pavadinimas: 'Kaip stulpeliu iš dviženklio skaičiaus atimti dviženklį išardant dešimtį?', lygis: 2 },
          'Kaip spręsti tekstinius sudėties uždavinius?',
          'Kaip spręsti tekstinius atimties uždavinius?',
          'Kaip sukurti ir pavaizduoti tekstinį uždavinį?',
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 1,
      },
      {
        numeris: 2,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Daugyba',
        potemes: [
          'Kas yra daugyba?',
          'Kaip vienodų dėmenų sudėtį pakeisti daugyba?',
          'Kaip dauginti iš 2?',
          'Kaip dauginti iš 3?',
          { pavadinimas: 'Kiek kartų padidėja sekos narys?', generatorius: 'sekos' },
          'Kaip dauginti iš 4?',
          'Kaip dauginti iš 5?',
          'Kaip dauginti iš 0 ir iš 1?',
          'Kaip dauginti iš 10?',
          'Kaip naudotis daugybos lentele?',
          'Kaip spręsti daugybos uždavinius?',
          'Kaip sukurti matematinį žaidimą?',
        ],
        generatorius: 'sveikieji',
        lygis: 1,
      },
      {
        numeris: 3,
        sritis: { min: 0, max: 100 },
        pavadinimas: 'Dalyba',
        potemes: [
          'Kas yra dalyba?',
          'Koks daugybos ir dalybos veiksmų ryšys?',
          'Kaip dalyti iš 2?',
          { pavadinimas: 'Kaip rasti pusę?', generatorius: 'dalies-radimas' },
          'Kaip dalyti iš 3 ir 4?',
          'Kas yra talpos dalyba?',
          { pavadinimas: 'Kaip rasti trečdalį ir ketvirtadalį?', generatorius: 'dalies-radimas' },
          { pavadinimas: 'Kas yra lyginiai ir nelyginiai skaičiai?', generatorius: 'dalumo-pozymiai', lygis: 1 },
          'Kaip dalyti iš 5?',
          { pavadinimas: 'Kiek kainuoja viena prekė?', generatorius: 'pinigai' },
          'Kaip sumažinti skaičių kelis kartus?',
        ],
        generatorius: 'sveikieji',
        lygis: 1,
      },
      {
        numeris: 4,
        // Kampų laipsniai iškrenta iš skaičiavimo srities: pilnas kampas yra
        // 360°, nors antrokas skaičiuoja iki 100. Riba čia yra kampo, o ne
        // skaičiavimo riba.
        sritis: { min: 0, max: 360 },
        pavadinimas: 'Plokščiosios figūros',
        potemes: [
          { pavadinimas: 'Kas yra laužtė?', generatorius: 'lauzes' },
          { pavadinimas: 'Kas yra kampas?', generatorius: 'kampai', lygis: 1 },
          'Kokias figūras vadiname daugiakampiais?',
          'Ką vadiname taisyklinguoju daugiakampiu?',
          { pavadinimas: 'Kas yra simetrija ir simetrijos ašis?', generatorius: 'simetrija' },
          { pavadinimas: 'Kaip vaizduojamos horizontalioji ir vertikalioji simetrijos ašys?', generatorius: 'simetrija' },
          { pavadinimas: 'Kaip atpažinti ir nubraižyti simetriškas figūras?', generatorius: 'simetrija' },
          { pavadinimas: 'Kaip atpažinti ir formuluoti teiginius?', generatorius: 'logika', lygis: 1 },
          { pavadinimas: 'Kaip rasti kelią plane pagal komandas?', generatorius: 'algoritmai' },
          { pavadinimas: 'Kaip sukurti planą?', generatorius: 'koordinates', lygis: 1 },
        ],
        generatorius: 'figuros',
        lygis: 1,
      },
      {
        numeris: 5,
        // Vienintelė pradinių klasių tema, kurioje neigiami skaičiai yra ne
        // klaida, o pati esmė: termometras rodo ir šaltį.
        sritis: { min: -50, max: 1000 },
        pavadinimas: 'Termometras',
        potemes: [
          'Ką matuojame termometru?',
          { pavadinimas: 'Kiek šilumos ar šalčio rodo termometras?', generatorius: 'neigiami', lygis: 1 },
          { pavadinimas: 'Kaip rinkti duomenis apie orus?', generatorius: 'diagramos' },
        ],
        generatorius: 'matavimo-vienetai',
        lygis: 1,
      },
      {
        numeris: 6,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Tyrinėju reiškinį „Laikas“',
        potemes: [
          'Kaip atsirado laikrodžiai?',
          'Kaip pasigaminti smėlio laikrodį?',
          'Ką galima nuveikti per minutę?',
          'Kiek minučių trunka pusė valandos? Ketvirtis valandos?',
          { pavadinimas: 'Kaip nusakyti laiką minučių tikslumu?', lygis: 2 },
          { pavadinimas: 'Kaip atlikti tyrimą, susijusį su laiku?', generatorius: 'diagramos' },
        ],
        generatorius: 'laikas',
        lygis: 1,
      },
      {
        numeris: 7,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Daugyba ir dalyba',
        potemes: [
          'Kaip dauginti ir dalyti iš 6?',
          'Kaip dauginti ir dalyti iš 7?',
          'Kaip parašyti ir atlikti dalybos veiksmą kampu?',
          'Kaip dauginti ir dalyti iš 8 ir 9?',
          { pavadinimas: 'Kaip rasti aštuntadalį?', generatorius: 'dalies-radimas' },
          'Kiek kartų daugiau? Kiek kartų mažiau?',
          { pavadinimas: 'Kaip dalyti 0? Kaip dalyti iš 1 ir 10?', lygis: 1 },
          { pavadinimas: 'Ką vadiname skaitine lygybe ir nelygybe?', generatorius: 'skaiciu-palyginimas' },
          { pavadinimas: 'Kokia tvarka reikia atlikti veiksmus skaitiniame reiškinyje?', generatorius: 'veiksmu-tvarka', lygis: 1 },
          { pavadinimas: 'Kaip apskaičiuoti reiškinio su skliaustais reikšmę?', generatorius: 'veiksmu-tvarka' },
          { pavadinimas: 'Kaip rasti visą daiktų skaičių, kai žinoma jų dalis?', generatorius: 'dalies-radimas' },
        ],
        generatorius: 'sveikieji',
        lygis: 2,
      },
      {
        numeris: 8,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Skaičiai iki 1000',
        potemes: [
          { pavadinimas: 'Kaip skaityti ir užrašyti skaičius iki 1000?', generatorius: 'skaitmenys', lygis: 1 },
          { pavadinimas: 'Kokia yra triženklių skaičių sandara?', generatorius: 'skaitmenys', lygis: 1 },
          { pavadinimas: 'Kaip stambinti ir smulkinti pinigus?', generatorius: 'pinigai' },
          { pavadinimas: 'Pagal kokią taisyklę sudaryta triženklių skaičių seka?', generatorius: 'sekos' },
          'Kaip sudėti skaičius iki 1000?',
          'Kaip sudėti skaičius iki 1000 sudarant naują apvalią dešimtį, šimtą?',
          'Kaip sudėti skaičius iki 1000 peržengiant dešimtį, šimtą?',
          'Kaip schema vaizduoti dviejų žingsnių uždavinį?',
          'Kaip užrašyti dviejų žingsnių uždavinio sprendimą?',
          'Kaip atimti skaičius iki 1000?',
          'Kaip atimti skaičius iki 1000 iš apvalių dešimčių, šimtų?',
          'Kaip atimti skaičius iki 1000 išardant dešimtį ir šimtą?',
          'Kaip sukurti dviejų žingsnių tekstinį uždavinį?',
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 9,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Ilgio matavimas',
        potemes: [
          'Kas matuojama metrais, centimetrais?',
          'Kas matuojama milimetrais?',
          'Kaip smulkinti ir stambinti ilgio matavimo vienetus?',
          { pavadinimas: 'Kaip nubraižyti figūrą?', generatorius: 'figuros', lygis: 1 },
          { pavadinimas: 'Kaip išmatuoti plotą langeliais?', generatorius: 'plotas-turis', lygis: 1 },
          { pavadinimas: 'Kaip apskaičiuoti figūros dalį?', generatorius: 'dalies-radimas' },
          { pavadinimas: 'Kas yra erdvės figūros?', generatorius: 'erdvines-figuros', lygis: 1 },
          'Kas matuojama kilometrais?',
          'Kaip spręsti uždavinius su ilgio matavimo vienetais?',
          { pavadinimas: 'Kaip atlikti tyrimą su ilgio matavimo vienetais?', generatorius: 'diagramos' },
          'Kokį atstumą nuskrieja skraidyklė?',
        ],
        generatorius: 'matavimo-vienetai',
        lygis: 2,
      },
      {
        numeris: 10,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Masės ir talpos matavimas. Algoritmai',
        potemes: [
          'Kas matuojama gramais?',
          'Kokią masę rodo svarstyklės?',
          'Kas matuojama tonomis?',
          'Kaip spręsti uždavinius su masės matavimo vienetais?',
          { pavadinimas: 'Kaip atlikti tyrimą su masės matavimo vienetais?', generatorius: 'diagramos' },
          'Kokie yra talpos matavimo vienetai?',
          'Kaip spręsti uždavinius su talpos matavimo vienetais?',
          { pavadinimas: 'Ką vadiname pasirinkimo komanda?', generatorius: 'algoritmai', lygis: 1 },
          { pavadinimas: 'Kaip sukurti ir vykdyti nuorodų algoritmą?', generatorius: 'algoritmai', lygis: 1 },
          { pavadinimas: 'Kaip kurti programą su „ScratchJr“?', generatorius: 'algoritmai', lygis: 1 },
        ],
        generatorius: 'matavimo-vienetai',
        lygis: 2,
      },
      {
        numeris: 11,
        // Vandens ir ledo temperatūra — neigiami skaičiai čia yra tema, ne klaida.
        sritis: { min: -50, max: 10000 },
        pavadinimas: 'Tyrinėju reiškinį „Vanduo“',
        potemes: [
          { pavadinimas: 'Kiek vandens sudaro ...?', generatorius: 'dalies-radimas' },
          'Kiek vandens išgaravo?',
          { pavadinimas: 'Kokia gali būti vandens temperatūra?', generatorius: 'neigiami', lygis: 1 },
          { pavadinimas: 'Kada vanduo tampa ledu?', generatorius: 'neigiami', lygis: 1 },
          { pavadinimas: 'Kaip apibendrinti duomenis remiantis stebėjimo lentele?', generatorius: 'diagramos' },
        ],
        generatorius: 'matavimo-vienetai',
        lygis: 2,
      },
    ],
  },
  {
    klase: 3,
    temos: [
      {
        numeris: 1,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Skaičiavimai iki 1000. Paprastosios trupmenos',
        potemes: [
          { pavadinimas: 'Ką žinau apie skaičius nuo 0 iki 1000?', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Kokios būna sekos?', generatorius: 'sekos' },
          'Kaip įvairiais būdais sudėti skaičius iki 1000?',
          'Kaip įvairiais būdais atimti skaičius iki 1000?',
          'Kaip lengviau sudėti ir atimti skaičius iki 1000?',
          'Kaip pasitikrinti skaičiavimų rezultatus?',
          { pavadinimas: 'Kada reikalinga daugyba arba dalyba?', generatorius: 'sveikieji' },
          { pavadinimas: 'Kaip moku daugybos lentelę?', generatorius: 'sveikieji', lygis: 1 },
          'Kaip spręsti tekstinius uždavinius su skaičiais iki 1000?',
          { pavadinimas: 'Kas yra paprastoji trupmena?', generatorius: 'dalies-radimas' },
          { pavadinimas: 'Kaip rasti skaičiaus dalį?', generatorius: 'dalies-radimas' },
          { pavadinimas: 'Kaip apskaičiuoti skaičiaus dalį, kai skaitiklis yra didesnis už 1?', generatorius: 'dalies-radimas', lygis: 2 },
          { pavadinimas: 'Kaip spręsti tekstinius uždavinius su trupmenomis?', generatorius: 'dalies-radimas' },
          { pavadinimas: 'Kaip pasigaminti picą?', generatorius: 'dalies-radimas' },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 2,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Sudėtis ir atimtis iki 10 000',
        potemes: [
          { pavadinimas: 'Kaip perskaityti ir užrašyti skaičius iki 10 000?', generatorius: 'skaitmenys', lygis: 2 },
          { pavadinimas: 'Kaip sudaryti skaičiai iki 10 000?', generatorius: 'skaitmenys', lygis: 2 },
          { pavadinimas: 'Kaip apvalinti skaičius?', generatorius: 'apvalinimas', lygis: 2 },
          'Kaip sudėti skaičius iki 10 000, kai nesusidaro naujas tūkstantis?',
          'Kaip sudėti skaičius iki 10 000, kai susidaro naujas tūkstantis?',
          'Kaip atimti skaičius iki 10 000, kai nereikia išardyti dešimties, šimto, tūkstančio?',
          'Kaip atimti skaičius iki 10 000, kai reikia išardyti dešimtį?',
          'Kaip atimti skaičius iki 10 000, kai reikia išardyti šimtą?',
          'Kaip atimti skaičius iki 10 000, kai reikia išardyti tūkstantį?',
          'Kaip spręsti tekstinius uždavinius sudedant ir atimant skaičius iki 10 000?',
          { pavadinimas: 'Kaip panaudoti elektroninių parduotuvių duomenis kuriant tekstinį uždavinį?', generatorius: 'pinigai', lygis: 2 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 3,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Geometrinės figūros',
        potemes: [
          { pavadinimas: 'Kokių būna kampų?', generatorius: 'kampai', lygis: 1 },
          { pavadinimas: 'Kokios tiesės, atkarpos yra susikertančios, statmenos, lygiagrečios?', generatorius: 'konstravimas', lygis: 1 },
          { pavadinimas: 'Kas yra apskritimo centras ir spindulys?', generatorius: 'apskritimas', lygis: 1 },
          { pavadinimas: 'Kas yra apskritimo skersmuo?', generatorius: 'apskritimas', lygis: 1 },
          { pavadinimas: 'Kokia gali būti figūrų tarpusavio padėtis?', generatorius: 'vieta', lygis: 2 },
          'Kaip galima suskaidyti plokštumos figūrą arba sujungti kelias figūras?',
          { pavadinimas: 'Kaip nubraižyti figūrą simetrišką tiesės atžvilgiu?', generatorius: 'simetrija', lygis: 2 },
          { pavadinimas: 'Kaip pavaizduoti objekto postūmį?', generatorius: 'simetrija', lygis: 2 },
          { pavadinimas: 'Kokie yra stačiakampio gretasienio elementai?', generatorius: 'erdvines-figuros', lygis: 1 },
          { pavadinimas: 'Kas yra prizmė ir piramidė?', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Kaip galima suskaidyti erdvės figūrą arba sujungti kelias figūras?', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Kaip sukurti aikštės maketą?', generatorius: 'koordinates', lygis: 1 },
        ],
        generatorius: 'figuros',
        lygis: 2,
      },
      {
        numeris: 4,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Daugiakampio perimetras',
        potemes: [
          { pavadinimas: 'Kas yra decimetras?', generatorius: 'matavimo-vienetai', lygis: 2 },
          { pavadinimas: 'Kaip smulkinti ir stambinti ilgio matavimo vienetus?', generatorius: 'matavimo-vienetai', lygis: 2 },
          'Kas yra daugiakampio perimetras?',
          { pavadinimas: 'Kaip apskaičiuoti taisyklingojo daugiakampio perimetrą?', generatorius: 'figuros', lygis: 2 },
          'Kaip galima skirtingais būdais apskaičiuoti stačiakampio perimetrą?',
          'Kaip nubraižyti daugiakampį ir apskaičiuoti jo perimetrą?',
          { pavadinimas: 'Kaip apskaičiuoti taisyklingojo daugiakampio kraštinės ilgį, kai žinomas jo perimetras?', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Kaip apskaičiuoti nežinomos stačiakampio kraštinės ilgį, kai žinomas jo perimetras?', lygis: 2 },
          'Kaip pasigaminti matematinį stalo žaidimą?',
        ],
        generatorius: 'perimetras',
        lygis: 1,
      },
      {
        numeris: 5,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Laikas',
        potemes: [
          'Kaip apskaičiuoti įvykio trukmę?',
          'Kaip naudotis tvarkaraščiu?',
          'Kaip naudotis kalendoriumi?',
        ],
        generatorius: 'laikas',
        lygis: 2,
      },
      {
        numeris: 6,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Tyrinėju reiškinį „Pinigai“',
        potemes: [
          'Kodėl pinigai turi skirtingą vertę?',
          'Kur išleidžiami pinigai?',
          'Kokios yra būtinosios išlaidos?',
          'Kaip apskaičiuoti išlaidas?',
          { pavadinimas: 'Kiek atpigo prekė?', generatorius: 'procentai', lygis: 1 },
          'Kaip galime daugiau sutaupyti?',
          'Kas sudaro paslaugos kainą?',
        ],
        generatorius: 'pinigai',
        lygis: 2,
      },
      {
        numeris: 7,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Daugyba ir dalyba iki 10 000',
        potemes: [
          'Kaip dauginti iš apvalių dešimčių, šimtų, tūkstančių?',
          'Kaip dauginti dviženklį skaičių iš vienaženklio?',
          { pavadinimas: 'Kaip dauginti triženklį ir keturženklį skaičių iš vienaženklio?', lygis: 2 },
          'Kaip dalyti iš apvalių dešimčių, šimtų, tūkstančių?',
          { pavadinimas: 'Kas yra dalyba su liekana?', generatorius: 'dalumas', lygis: 2 },
          'Kaip dviženklį skaičių dalyti iš vienaženklio?',
          { pavadinimas: 'Kaip triženklį skaičių dalyti iš vienaženklio?', lygis: 2 },
          { pavadinimas: 'Kaip keturženklį skaičių dalyti iš vienaženklio?', lygis: 2 },
          'Kada dalmenyje reikia rašyti nulį?',
          { pavadinimas: 'Kiek kartų padidėja ar sumažėja sekos narys?', generatorius: 'sekos', lygis: 2 },
          'Kaip pritaikyti daugybą ir dalybą sprendžiant tekstinius uždavinius?',
          'Kaip spręsti tekstinį uždavinį skirtingais būdais?',
          'Kaip sukurti daugybos ir dalybos žaidimą?',
        ],
        generatorius: 'sveikieji',
        lygis: 2,
      },
      {
        numeris: 8,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Lygtys ir raidiniai reiškiniai',
        potemes: [
          'Kas yra lygtis?',
          'Kaip sprendžiant lygtį rasti nežinomą dėmenį?',
          'Kaip sprendžiant lygtį rasti nežinomą turinį ar atėminį?',
          'Kaip sprendžiant lygtį rasti nežinomą daugiklį?',
          'Kaip sprendžiant lygtį rasti nežinomą dalinį ar daliklį?',
          'Kaip pagal piešinį, modelį ar schemą sudaryti lygtį?',
          { pavadinimas: 'Kaip parašyti raidinį reiškinį ir apskaičiuoti jo reikšmę?', generatorius: 'raidiniai-reiskiniai', lygis: 1 },
          { pavadinimas: 'Kaip pagal uždavinio sąlygą parašyti raidinį reiškinį?', generatorius: 'raidiniai-reiskiniai', lygis: 1 },
          { pavadinimas: 'Kaip pagal piešinį ar schemą parašyti raidinį reiškinį?', generatorius: 'raidiniai-reiskiniai', lygis: 1 },
          { pavadinimas: 'Kaip sukurti kompoziciją iš figūrų?', generatorius: 'ornamentai', lygis: 1 },
        ],
        generatorius: 'tiesines-lygtys',
        lygis: 1,
      },
      {
        numeris: 9,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Trupmenos. Tekstinių uždavinių sprendimas',
        potemes: [
          'Kaip pavaizduoti trupmenas skaičių tiesėje?',
          { pavadinimas: 'Kaip palyginti trupmenas?', generatorius: 'bendravardiklinimas', lygis: 1 },
          { pavadinimas: 'Kokios trupmenos yra lygios?', generatorius: 'bendravardiklinimas', lygis: 1 },
          'Kaip spręsti uždavinius, kai duomenys pateikti trupmenomis su matavimo vienetais?',
          { pavadinimas: 'Kaip spręsti visumos radimo uždavinius, kai žinomos kelios dalys?', lygis: 2 },
          'Kaip pasirinkti tinkamą uždavinio sprendimo būdą?',
          { pavadinimas: 'Kaip pagrįsti uždavinio atsakymą remiantis sprendimu?', generatorius: 'logika', lygis: 1 },
          'Kaip keliais skirtingais būdais išspręsti tekstinį uždavinį?',
          'Kaip pasigaminti trupmenų modelį?',
        ],
        generatorius: 'dalies-radimas',
        lygis: 2,
      },
      {
        numeris: 10,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Duomenys. Algoritmai',
        potemes: [
          'Kokia gali būti diagramos padalos vertė?',
          'Kaip pasirinkti tinkamą diagramos padalos vertę?',
          'Kaip grupuoti duomenis pagal nurodytą požymį?',
          { pavadinimas: 'Kaip įvardyti įvykio tikėtinumą?', generatorius: 'tikimybe', lygis: 1 },
          { pavadinimas: 'Kiek skirtingų algoritmų galima sukurti tam pačiam rezultatui gauti?', generatorius: 'algoritmai', lygis: 2 },
          { pavadinimas: 'Kaip patikrinti algoritmo teisingumą?', generatorius: 'algoritmai', lygis: 2 },
          { pavadinimas: 'Kaip naudotis programa „XLogo“?', generatorius: 'algoritmai', lygis: 2 },
        ],
        generatorius: 'diagramos',
        lygis: 2,
      },
      {
        numeris: 11,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Tyrinėju reiškinį „Knyga“',
        potemes: [
          'Kaip keitėsi knyga?',
          { pavadinimas: 'Kiek knygų perskaitėme trečioje klasėje?', generatorius: 'diagramos', lygis: 2 },
          { pavadinimas: 'Kokios yra knygos rekordininkės?', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Kodėl skiriasi knygų tiražai?', generatorius: 'skaiciu-palyginimas', lygis: 2 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
    ],
  },
  {
    klase: 4,
    temos: [
      {
        numeris: 1,
        sritis: { min: 0, max: 100000 },
        pavadinimas: 'Skaičiai ir skaičiavimai iki 100 000',
        potemes: [
          { pavadinimas: 'Ką žinau apie skaičius iki 10 000?', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          'Kaip moku sudėti ir atimti skaičius iki 10 000?',
          { pavadinimas: 'Kaip moku dauginti ir dalyti skaičius iki 10 000?', generatorius: 'sveikieji', lygis: 2 },
          'Kaip moku spręsti tekstinius uždavinius?',
          { pavadinimas: 'Kaip stulpeliu dauginti dviženklius skaičius?', generatorius: 'sveikieji', lygis: 2 },
          { pavadinimas: 'Kaip dauginti triženklį skaičių iš dviženklio?', generatorius: 'sveikieji', lygis: 2 },
          { pavadinimas: 'Kaip sudaryti skaičiai iki 100 000?', generatorius: 'skaitmenys', lygis: 2 },
          'Kaip sudėti skaičius iki 100 000?',
          'Kaip atimti skaičius iki 100 000?',
          { pavadinimas: 'Kaip dauginti skaičius iki 100 000?', generatorius: 'sveikieji', lygis: 2 },
          { pavadinimas: 'Kaip dalyti skaičius iki 100 000?', generatorius: 'sveikieji', lygis: 2 },
          { pavadinimas: 'Kaip nustatyti sekos sudarymo taisykles, kai sulietos dvi sekos?', generatorius: 'sekos', lygis: 2 },
          { pavadinimas: 'Kokia tvarka atlikti veiksmus skaitiniame reiškinyje?', generatorius: 'veiksmu-tvarka', lygis: 2 },
          { pavadinimas: 'Kaip spręsti tekstinį uždavinį sudarant skaitinį reiškinį?', generatorius: 'veiksmu-tvarka', lygis: 2 },
          { pavadinimas: 'Kaip kompiuterine programa sukurti užduotį?', generatorius: 'algoritmai', lygis: 2 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 2,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Mišrieji ir dešimtainiai skaičiai',
        potemes: [
          { pavadinimas: 'Ką žinau apie trupmenas?', generatorius: 'dalies-radimas', lygis: 2 },
          { pavadinimas: 'Kaip moku spręsti tekstinius uždavinius su trupmenomis?', generatorius: 'dalies-radimas', lygis: 2 },
          { pavadinimas: 'Kas yra mišrieji skaičiai?', generatorius: 'trupmenu-sudetis', lygis: 1 },
          { pavadinimas: 'Kaip skaičių tiesėje pavaizduoti mišrųjį skaičių?', generatorius: 'trupmenu-sudetis', lygis: 1 },
          { pavadinimas: 'Kaip apvalinti mišriuosius skaičius?', generatorius: 'apvalinimas', lygis: 2 },
          { pavadinimas: 'Kaip sudėti ir atimti trupmenas?', generatorius: 'trupmenu-sudetis', lygis: 1 },
          { pavadinimas: 'Kaip sudėti ir atimti mišriuosius skaičius?', generatorius: 'trupmenu-sudetis', lygis: 2 },
          { pavadinimas: 'Kas yra dešimtainiai skaičiai?', lygis: 1 },
          { pavadinimas: 'Kaip trupmeną užrašyti dešimtainiu skaičiumi, o dešimtainį skaičių – trupmena?', lygis: 2 },
          { pavadinimas: 'Kaip užrašyti ir apskaičiuoti prekių kainą dešimtainiais skaičiais?', generatorius: 'pinigai', lygis: 2 },
          { pavadinimas: 'Kaip atlikti daugybos ir dalybos veiksmus, kai prekių kainos nurodytos dešimtainiais skaičiais?', generatorius: 'pinigai', lygis: 2 },
          { pavadinimas: 'Kaip sudaryti seką iš dešimtainių skaičių?', generatorius: 'sekos', lygis: 2 },
          { pavadinimas: 'Kaip apskaičiuoti gaminio savikainą?', generatorius: 'pinigai', lygis: 2 },
        ],
        generatorius: 'desimtaines',
        lygis: 2,
      },
      {
        numeris: 3,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Plokščiosios figūros. Plotas',
        potemes: [
          { pavadinimas: 'Ką žinau apie plokščiąsias figūras?', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Kaip sudarytos objektų sekos?', generatorius: 'ornamentai', lygis: 2 },
          { pavadinimas: 'Ką vadiname lygiomis figūromis?', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Kaip vadinami trikampiai pagal kraštinių ilgius?', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Kaip vadinami trikampiai pagal kampų rūšis?', generatorius: 'kampai', lygis: 1 },
          { pavadinimas: 'Kas matuojama kvadratiniais centimetrais, kvadratiniais metrais?', generatorius: 'matavimo-vienetai', lygis: 2 },
          'Kaip apskaičiuoti stačiakampio plotą?',
          { pavadinimas: 'Kaip apskaičiuoti iš kvadratų ir stačiakampių sudarytos figūros plotą?', lygis: 2 },
          { pavadinimas: 'Kaip spręsti tekstinius uždavinius, kuriuose reikia apskaičiuoti plotą?', lygis: 2 },
          { pavadinimas: 'Kaip spręsti tekstinius uždavinius, kuriuose reikia apskaičiuoti plotą ir perimetrą?', generatorius: 'perimetras', lygis: 2 },
          { pavadinimas: 'Kaip remiantis planu apskaičiuoti patalpos plotą?', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 1,
      },
      {
        numeris: 4,
        sritis: { min: 0, max: 1000000 },
        pavadinimas: 'Skaičiai iki 1 000 000',
        potemes: [
          { pavadinimas: 'Kaip skaityti ir užrašyti skaičius iki 1 000 000?', generatorius: 'skaitmenys', lygis: 2 },
          { pavadinimas: 'Kokia yra skaičių iki 1 000 000 sandara?', generatorius: 'skaitmenys', lygis: 2 },
          { pavadinimas: 'Kaip skaičių užrašyti skyrių suma?', generatorius: 'skaitmenys', lygis: 2 },
          { pavadinimas: 'Ką reiškia skaičių trumpiniai „tūkst.“ ir „mln.“?', generatorius: 'skaitmenys', lygis: 2 },
          { pavadinimas: 'Kaip palyginti skaičius iki 1 000 000?', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Kaip apvalinti skaičius iki 1 000 000?', generatorius: 'apvalinimas', lygis: 2 },
          'Kaip sudėti skaičius iki 1 000 000?',
          'Kaip atimti skaičius iki 1 000 000?',
          { pavadinimas: 'Kaip dauginti skaičius iki 1 000 000?', generatorius: 'sveikieji', lygis: 2 },
          { pavadinimas: 'Kaip dalyti skaičius iki 1 000 000?', generatorius: 'sveikieji', lygis: 2 },
          { pavadinimas: 'Kaip pasirinkti patogų mintinio skaičiavimo būdą?', generatorius: 'veiksmu-tvarka', lygis: 2 },
          'Kaip patikrinti skaičiavimo rezultatą?',
          'Kaip iš perteklinės informacijos atrinkti uždaviniui reikalingus duomenis?',
          'Kaip išspręsti kelių žingsnių tekstinį uždavinį?',
          { pavadinimas: 'Kaip sudaryti reiškinį su skliaustais pagal tekstinio uždavinio sąlygą?', generatorius: 'veiksmu-tvarka', lygis: 2 },
          'Kaip sukurti matematinį klausimą pagal pateiktus duomenis?',
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 5,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Lygtys ir raidiniai reiškiniai',
        potemes: [
          { pavadinimas: 'Kas yra lygtis?', lygis: 1 },
          { pavadinimas: 'Kas yra lygties nežinomasis ir sprendinys?', lygis: 1 },
          'Kaip sudaryti lygtį pagal tekstinio uždavinio sąlygą?',
          'Kaip sudaryti lygtį pagal schemą?',
          { pavadinimas: 'Kaip išspręsti paprastą lygtį?', lygis: 1 },
          'Kaip patikrinti lygties sprendinį?',
          'Kaip tą pačią situaciją aprašyti skirtingomis lygtimis?',
          { pavadinimas: 'Kas yra raidinis reiškinys?', generatorius: 'raidiniai-reiskiniai', lygis: 1 },
          { pavadinimas: 'Kaip apskaičiuoti raidinio reiškinio reikšmę?', generatorius: 'raidiniai-reiskiniai', lygis: 1 },
          { pavadinimas: 'Kaip pagal tekstinio uždavinio sąlygą parašyti raidinį reiškinį?', generatorius: 'raidiniai-reiskiniai', lygis: 2 },
          { pavadinimas: 'Kaip susieti tekstinę sąlygą, schemą ir raidinį reiškinį?', generatorius: 'raidiniai-reiskiniai', lygis: 2 },
        ],
        generatorius: 'tiesines-lygtys',
        lygis: 2,
      },
      {
        numeris: 6,
        // Termometro rodmenys — vienintelė vieta, kur 4 klasėje reikia minuso.
        sritis: { min: -50, max: 100000 },
        pavadinimas: 'Matavimo prietaisai ir rodmenys',
        potemes: [
          'Kaip perskaityti svarstyklių rodmenis?',
          { pavadinimas: 'Kaip perskaityti laikrodžio rodmenis?', generatorius: 'laikas', lygis: 2 },
          { pavadinimas: 'Kaip perskaityti termometro rodmenis?', generatorius: 'neigiami', lygis: 1 },
          { pavadinimas: 'Kaip perskaityti odometro rodmenis?', generatorius: 'skaitmenys', lygis: 2 },
          'Kaip pasirinkti tinkamą matavimo vienetą?',
          'Kaip palyginti skirtingais vienetais išreikštus dydžius?',
          'Kaip spręsti uždavinius su masės, laiko ir temperatūros duomenimis?',
        ],
        generatorius: 'matavimo-vienetai',
        lygis: 2,
      },
      {
        numeris: 7,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Kelias, laikas ir greitis',
        potemes: [
          'Kas yra kelias?',
          'Kas yra greitis?',
          'Kaip susiję kelias, laikas ir greitis?',
          'Kaip apskaičiuoti nueitą arba nuvažiuotą kelią?',
          { pavadinimas: 'Kaip apskaičiuoti judėjimo laiką?', lygis: 2 },
          { pavadinimas: 'Kaip apskaičiuoti greitį?', lygis: 2 },
          { pavadinimas: 'Kas yra vidutinis greitis?', lygis: 2 },
          { pavadinimas: 'Kaip naudoti greičio matavimo vienetus km/h, m/min ir m/s?', generatorius: 'matavimo-vienetai', lygis: 2 },
          { pavadinimas: 'Kaip spręsti tekstinius judėjimo uždavinius?', lygis: 2 },
          { pavadinimas: 'Kaip patikrinti, ar apskaičiuotas greitis yra tikroviškas?', generatorius: 'logika', lygis: 2 },
        ],
        generatorius: 'greitis',
        lygis: 1,
      },
      {
        numeris: 8,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Finansiniai sprendimai',
        potemes: [
          { pavadinimas: 'Kaip perskaityti dešimtainiu skaičiumi užrašytą pinigų sumą?', generatorius: 'desimtaines', lygis: 1 },
          'Kaip palyginti prekių ir paslaugų kainas?',
          'Kaip apskaičiuoti bendrą pirkinio kainą?',
          { pavadinimas: 'Kaip apskaičiuoti kainos pokytį?', generatorius: 'procentai', lygis: 1 },
          'Kas yra pajamos ir išlaidos?',
          'Kaip apskaičiuoti, kiek pinigų liko?',
          'Kaip suplanuoti paprastą taupymą?',
          'Kaip įvertinti, ar pirkinio kaina yra priimtina?',
          { pavadinimas: 'Kaip pasirinkti finansiškai naudingesnį sprendimą?', generatorius: 'proporcijos', lygis: 1 },
          { pavadinimas: 'Kaip skaičiavimais pagrįsti finansinį pasirinkimą?', generatorius: 'proporcijos', lygis: 2 },
        ],
        generatorius: 'pinigai',
        lygis: 2,
      },
      {
        numeris: 9,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Konstravimas ir transformacijos',
        potemes: [
          { pavadinimas: 'Kaip nusakyti langelio vietą raidės ir skaičiaus pora?', generatorius: 'vieta', lygis: 2 },
          'Kaip nusakyti objekto vietą dviejų skaičių pora?',
          'Kaip rasti objektą pagal nurodytą vietą tinklelyje?',
          { pavadinimas: 'Kaip apibūdinti objekto judėjimą tinklelyje?', generatorius: 'simetrija', lygis: 2 },
          { pavadinimas: 'Kaip judėti šiaurės, pietų, rytų ir vakarų kryptimis?', generatorius: 'algoritmai', lygis: 2 },
          { pavadinimas: 'Kaip pagal komandų seką perkelti objektą?', generatorius: 'algoritmai', lygis: 2 },
          { pavadinimas: 'Kaip apibūdinti languotame popieriuje pavaizduotą ornamentą?', generatorius: 'ornamentai', lygis: 2 },
          { pavadinimas: 'Kas yra objekto posūkis?', generatorius: 'konstravimas', lygis: 1 },
          { pavadinimas: 'Kaip atpažinti posūkį apie nurodytą tašką?', generatorius: 'konstravimas', lygis: 2 },
          { pavadinimas: 'Kaip atpažinti posūkio kryptį?', generatorius: 'konstravimas', lygis: 2 },
          { pavadinimas: 'Kaip pavaizduoti posūkį stačiuoju kampu?', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Kaip sukurti ornamentą taikant postūmius ir posūkius?', generatorius: 'ornamentai', lygis: 2 },
        ],
        generatorius: 'koordinates',
        lygis: 1,
      },
      {
        numeris: 10,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Erdvės figūros ir tūris',
        potemes: [
          { pavadinimas: 'Kas yra tūris?', generatorius: 'plotas-turis', lygis: 2 },
          'Kaip statinio tūrį apibūdinti kubelių skaičiumi?',
          { pavadinimas: 'Kas yra kubinis centimetras?', generatorius: 'matavimo-vienetai', lygis: 2 },
          { pavadinimas: 'Kas yra kubinis metras?', generatorius: 'matavimo-vienetai', lygis: 2 },
          { pavadinimas: 'Kaip pasirinkti tinkamą tūrio matavimo vienetą?', generatorius: 'matavimo-vienetai', lygis: 2 },
          { pavadinimas: 'Kaip apskaičiuoti statinį sudarančių kubelių skaičių?', generatorius: 'plotas-turis', lygis: 2 },
          'Kuo kubas panašus į stačiakampį gretasienį?',
          'Kodėl kubas yra ypatingas stačiakampis gretasienis?',
          { pavadinimas: 'Kaip atpažinti prizmę ir piramidę?', lygis: 1 },
          { pavadinimas: 'Kaip atpažinti ritinį ir kūgį?', lygis: 1 },
          { pavadinimas: 'Kaip įvardyti erdvės figūros sienas, briaunas ir viršūnes?', lygis: 1 },
          'Kaip susieti erdvės figūrą su jos išklotine?',
          { pavadinimas: 'Kaip erdvės figūra atrodo iš viršaus?', generatorius: 'vieta', lygis: 2 },
          { pavadinimas: 'Kaip erdvės figūra atrodo iš priekio arba iš šono?', generatorius: 'vieta', lygis: 2 },
          { pavadinimas: 'Kaip sukonstruoti erdvės figūrą pagal jos išklotinę?', lygis: 2 },
        ],
        generatorius: 'erdvines-figuros',
        lygis: 2,
      },
      {
        numeris: 11,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Duomenys ir statistinis tyrimas',
        potemes: [
          'Kas yra statistinis klausimas?',
          'Kaip suplanuoti duomenų rinkimą?',
          'Kaip surinkti ir susisteminti duomenis?',
          'Kaip perskaityti linijinę diagramą?',
          'Kaip nubraižyti linijinę diagramą?',
          'Kaip perskaityti skritulinę diagramą?',
          { pavadinimas: 'Kaip sudaryti paprastą skritulinę diagramą?', generatorius: 'dalies-radimas', lygis: 2 },
          'Kaip pagal diagramą atsakyti į klausimus?',
          'Kaip pasirinkti tinkamą duomenų pateikimo būdą?',
          { pavadinimas: 'Kaip pristatyti statistinio tyrimo rezultatus?', generatorius: 'vidurkis', lygis: 1 },
          { pavadinimas: 'Kaip suformuluoti tyrimo išvadą?', generatorius: 'vidurkis', lygis: 1 },
          { pavadinimas: 'Kaip įvertinti, ar tyrimo išvada pagrįsta surinktais duomenimis?', generatorius: 'logika', lygis: 2 },
        ],
        generatorius: 'diagramos',
        lygis: 2,
      },
      {
        numeris: 12,
        sritis: { min: 0, max: 1000 },
        pavadinimas: 'Tikimybė',
        potemes: [
          'Kas yra bandymas ir jo baigtis?',
          { pavadinimas: 'Kaip išvardyti visas galimas bandymo baigtis?', generatorius: 'kombinatorika', lygis: 1 },
          'Kuri baigtis labiau tikėtina?',
          'Kuri baigtis mažiau tikėtina?',
          'Kada baigtys yra vienodai tikėtinos?',
          'Kaip atlikti bandymą su moneta?',
          'Kaip atlikti bandymą su kauliuku?',
          'Kaip atlikti bandymą su suktuku?',
          { pavadinimas: 'Kaip užrašyti bandymo rezultatus?', generatorius: 'diagramos', lygis: 2 },
          { pavadinimas: 'Kaip palyginti spėjimą su eksperimento rezultatais?', generatorius: 'diagramos', lygis: 2 },
          { pavadinimas: 'Kaip tikimybę užrašyti skaičiumi nuo 0 iki 1?', lygis: 2 },
          { pavadinimas: 'Kaip sukurti sąžiningą tikimybinį žaidimą?', lygis: 2 },
        ],
        generatorius: 'tikimybe',
        lygis: 1,
      },
      {
        numeris: 13,
        sritis: { min: 0, max: 10000 },
        pavadinimas: 'Dėsningumai, algoritmai ir programavimas',
        potemes: [
          { pavadinimas: 'Kaip pratęsti seką iš trupmenų?', generatorius: 'sekos', lygis: 2 },
          { pavadinimas: 'Kaip pratęsti seką iš dešimtainių skaičių?', generatorius: 'sekos', lygis: 2 },
          { pavadinimas: 'Kaip apibūdinti didėjančių arba mažėjančių objektų seką?', generatorius: 'ornamentai', lygis: 2 },
          { pavadinimas: 'Kaip sukurti seką pagal nurodytą taisyklę?', generatorius: 'sekos', lygis: 2 },
          'Kas yra kartojimo komanda?',
          'Kaip vykdyti komandų seką su kartojimo komanda?',
          { pavadinimas: 'Kaip vienoje programoje taikyti pasirinkimo ir kartojimo komandas?', lygis: 2 },
          'Kaip didelę užduotį suskaidyti į mažesnes dalis?',
          'Kaip sudaryti užduoties sprendimo algoritmą?',
          'Kaip patikrinti algoritmo teisingumą?',
          { pavadinimas: 'Kaip rasti ir ištaisyti algoritmo klaidą?', generatorius: 'logika', lygis: 2 },
          { pavadinimas: 'Kaip sukurti skirtingus algoritmus tam pačiam rezultatui pasiekti?', lygis: 2 },
        ],
        generatorius: 'algoritmai',
        lygis: 2,
      },
    ],
  },
  {
    klase: 5,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Natūralieji skaičiai',
        potemes: [
          { pavadinimas: 'Skaičius ir skaitmuo', lygis: 1 },
          { pavadinimas: 'Skaičiaus skaitmenų skyrių lentelė', lygis: 1 },
          { pavadinimas: 'Skaitmens reikšmė', lygis: 1 },
          { pavadinimas: 'Rašome natūraliuosius skaičius', lygis: 2 },
          { pavadinimas: 'Skaičių tiesė', generatorius: 'koordinates', lygis: 2 },
          { pavadinimas: 'Palyginame natūraliuosius skaičius', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Apvaliname iki dešimčių', generatorius: 'apvalinimas', lygis: 2 },
          { pavadinimas: 'Apvaliname iki nurodyto skyriaus', generatorius: 'apvalinimas', lygis: 2 },
          { pavadinimas: 'Romėniškieji skaitmenys', lygis: 2 },
          { pavadinimas: 'Rašome skaičius romėniškaisiais skaitmenimis', lygis: 2 },
        ],
        generatorius: 'skaitmenys',
        lygis: 2,
      },
      {
        numeris: 2,
        pavadinimas: 'Veiksmai su natūraliaisiais skaičiais',
        potemes: [
          { pavadinimas: 'Skaičių sudėtis. Sudėties perstatomumo dėsnis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Sudėties jungiamumo dėsnis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Skaičių atimtis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Atimties dėsniai', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Skaičių daugyba. Daugybos perstatomumo dėsnis', lygis: 2 },
          { pavadinimas: 'Daugybos jungiamumo dėsnis', lygis: 2 },
          { pavadinimas: 'Daugybos skirstomumo dėsnis', lygis: 2 },
          { pavadinimas: 'Skaičių dalyba. Dalyba kampu', lygis: 2 },
          { pavadinimas: 'Dalybos dėsniai. Pagrindinė dalmens savybė', lygis: 2 },
          { pavadinimas: 'Sumos (skirtumo) dalijimas iš natūraliojo skaičiaus', lygis: 2 },
          { pavadinimas: 'Kelio formulė', generatorius: 'greitis', lygis: 2 },
          { pavadinimas: 'Judėjimas iš tos pačios vietos', generatorius: 'greitis', lygis: 2 },
          { pavadinimas: 'Judėjimas iš skirtingų vietų', generatorius: 'greitis', lygis: 2 },
        ],
        generatorius: 'sveikieji',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Dalumas',
        potemes: [
          { pavadinimas: 'Dalijame iš 10 ir iš 100', lygis: 1 },
          { pavadinimas: 'Dalijame iš 5 ir iš 2', lygis: 1 },
          { pavadinimas: 'Dalijame iš 9 ir iš 3', lygis: 1 },
          { pavadinimas: 'Dalijame iš 4', lygis: 1 },
          { pavadinimas: 'Skaičiaus dalikliai', generatorius: 'dalumas', lygis: 2 },
          { pavadinimas: 'Pirminiai ir sudėtiniai skaičiai', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Skaidome pirminiais dauginamaisiais', lygis: 2 },
          { pavadinimas: 'Didžiausiasis bendrasis daliklis', generatorius: 'dalumas', lygis: 2 },
          { pavadinimas: 'Skaičiaus kartotiniai', generatorius: 'dalumas', lygis: 2 },
          { pavadinimas: 'Mažiausiasis bendrasis kartotinis', generatorius: 'dalumas', lygis: 2 },
        ],
        generatorius: 'dalumo-pozymiai',
        lygis: 2,
      },
      {
        numeris: 4,
        pavadinimas: 'Trupmeniniai skaičiai',
        potemes: [
          { pavadinimas: 'Taisyklingosios ir netaisyklingosios paprastosios trupmenos', lygis: 2 },
          { pavadinimas: 'Netaisyklingoji trupmena ir mišrusis skaičius', lygis: 2 },
          { pavadinimas: 'Pagrindinė paprastosios trupmenos savybė', lygis: 2 },
          { pavadinimas: 'Dešimtainiai skaičiai', generatorius: 'desimtaines', lygis: 2 },
          { pavadinimas: 'Lygūs dešimtainiai skaičiai', generatorius: 'desimtaines', lygis: 2 },
          { pavadinimas: 'Paprastoji trupmena ir dešimtainis skaičius', lygis: 2 },
          { pavadinimas: 'Procentai', generatorius: 'procentai', lygis: 2 },
          { pavadinimas: 'Paprastosios trupmenos, dešimtainiai skaičiai ir procentai', generatorius: 'procentai', lygis: 2 },
          { pavadinimas: 'Skaičiaus dalies radimas', generatorius: 'dalies-radimas', lygis: 2 },
          { pavadinimas: 'Skaičiaus radimas, kai žinoma jo dalis', generatorius: 'bendravardiklinimas', lygis: 2 },
          { pavadinimas: 'Finansiniai skaičiavimai: pirkimas, pardavimas ir nuolaidos', generatorius: 'palukanos', lygis: 2 },
        ],
        generatorius: 'trupmenu-sudetis',
        lygis: 2,
      },
      {
        numeris: 5,
        pavadinimas: 'Veiksmai su paprastosiomis trupmenomis ir mišriaisiais skaičiais',
        potemes: [
          { pavadinimas: 'Palyginame', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Sudedame paprastąsias trupmenas', lygis: 2 },
          { pavadinimas: 'Sudedame mišriuosius skaičius', lygis: 2 },
          { pavadinimas: 'Atimame paprastąją trupmeną', lygis: 2 },
          { pavadinimas: 'Natūraliųjų ir mišriųjų skaičių atimtis', lygis: 2 },
          { pavadinimas: 'Mišriųjų skaičių atimtis', lygis: 2 },
          { pavadinimas: 'Bendravardikliname', generatorius: 'bendravardiklinimas', lygis: 1 },
          { pavadinimas: 'Palyginame', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Sudedame', lygis: 2 },
          { pavadinimas: 'Atimame', lygis: 2 },
          { pavadinimas: 'Paprastosios trupmenos ir natūraliojo skaičiaus daugyba', generatorius: 'trupmenu-daugyba', lygis: 2 },
          { pavadinimas: 'Mišriojo ir natūraliojo skaičių daugyba', generatorius: 'sveikieji', lygis: 2 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Veiksmai su dešimtainiais skaičiais',
        potemes: [
          { pavadinimas: 'Palyginame', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Apvaliname iki vienetų', lygis: 2 },
          { pavadinimas: 'Apvaliname iki nurodyto skyriaus', lygis: 2 },
          { pavadinimas: 'Sudedame', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Atimame', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Dešimtainio ir natūraliojo skaičių daugyba', generatorius: 'desimtaines', lygis: 2 },
          { pavadinimas: 'Dauginame iš 10, 100, 1000, ...', generatorius: 'sveikieji', lygis: 2 },
        ],
        generatorius: 'apvalinimas',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Reiškiniai. Lygtys',
        potemes: [
          { pavadinimas: 'Skaitinis reiškinys ir jo reikšmė', generatorius: 'veiksmu-tvarka', lygis: 2 },
          { pavadinimas: 'Raidinis reiškinys', lygis: 2 },
          { pavadinimas: 'Raidinio reiškinio reikšmės', lygis: 2 },
          { pavadinimas: 'Dauginame ir dalijame iš skaičiaus', lygis: 2 },
          { pavadinimas: 'Panašieji nariai, jų sutraukimas', lygis: 2 },
          { pavadinimas: 'Skaitinių lygybių savybės', generatorius: 'tiesines-lygtys', lygis: 1 },
          { pavadinimas: 'Lygtis ir jos sprendinys', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Lygties sprendimas', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Tekstinių uždavinių sprendimas sudarant lygtis', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Skaičių sekos ir įvesties–išvesties lentelės', generatorius: 'rekurencios-sekos', lygis: 2 },
        ],
        generatorius: 'raidiniai-reiskiniai',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Kampai',
        potemes: [
          { pavadinimas: 'Kampas ir jo elementai', lygis: 2 },
          { pavadinimas: 'Kuris kampas didesnis?', lygis: 2 },
          { pavadinimas: 'Ištiestinis ir statusis kampai', lygis: 2 },
          { pavadinimas: 'Smailusis ir bukasis kampai', lygis: 2 },
          { pavadinimas: 'Pilnasis ir priešpilnis kampai', lygis: 2 },
          { pavadinimas: 'Laipsnis', lygis: 2 },
          { pavadinimas: 'Kampų palyginimas', lygis: 2 },
          { pavadinimas: 'Ištiestinio, stačiojo ir smailiojo kampų dydžiai', lygis: 2 },
          { pavadinimas: 'Bukojo, pilnojo ir priešpilnio kampų dydžiai', lygis: 2 },
          { pavadinimas: 'Matlankis. Matuojame kampus', generatorius: 'konstravimas', lygis: 2 },
          { pavadinimas: 'Braižome kampą. Kampo pusiaukampinė', generatorius: 'konstravimas', lygis: 1 },
          { pavadinimas: 'Gretutiniai kampai', lygis: 2 },
          { pavadinimas: 'Kryžminiai kampai', lygis: 2 },
        ],
        generatorius: 'kampai',
        lygis: 2,
      },
      {
        numeris: 9,
        pavadinimas: 'Trikampiai ir keturkampiai',
        potemes: [
          { pavadinimas: 'Daugiakampis', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Trikampio kampai', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Daugiakampio kampai', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Ilgio matavimo vienetai', generatorius: 'matavimo-vienetai', lygis: 2 },
          { pavadinimas: 'Trikampio perimetras', generatorius: 'perimetras', lygis: 2 },
          { pavadinimas: 'Keturkampio perimetras', generatorius: 'perimetras', lygis: 2 },
          { pavadinimas: 'Ploto matavimo vienetai', lygis: 2 },
          { pavadinimas: 'Stačiakampio ir kvadrato plotai', lygis: 2 },
          { pavadinimas: 'Stačiojo trikampio plotas', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 2,
      },
      {
        numeris: 10,
        pavadinimas: 'Simetrija. Posūkis. Postūmis',
        potemes: [
          { pavadinimas: 'Tiesės atžvilgiu simetriškos figūros', lygis: 2 },
          { pavadinimas: 'Figūros, turinčios simetrijos ašį', lygis: 2 },
          { pavadinimas: 'Posūkis apie tašką', lygis: 2 },
          { pavadinimas: 'Taško atžvilgiu simetriškos figūros', lygis: 2 },
          { pavadinimas: 'Figūros, turinčios simetrijos centrą', lygis: 2 },
          { pavadinimas: 'Lygiagretusis postūmis', lygis: 2 },
          { pavadinimas: 'Lygiagretainis, rombas, trapecija', generatorius: 'figuros', lygis: 2 },
        ],
        generatorius: 'simetrija',
        lygis: 2,
      },
      {
        numeris: 11,
        pavadinimas: 'Erdviniai kūnai',
        potemes: [
          { pavadinimas: 'Vaizduojame', generatorius: 'erdvines-figuros', lygis: 1 },
          { pavadinimas: 'Matmenys. Išklotinė', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Stačiakampio gretasienio paviršiaus plotas', lygis: 2 },
          { pavadinimas: 'Kubo paviršiaus plotas', lygis: 2 },
          { pavadinimas: 'Tūris', lygis: 2 },
          { pavadinimas: 'Stačiakampio gretasienio tūris', lygis: 2 },
          { pavadinimas: 'Kubo tūris', lygis: 2 },
          { pavadinimas: 'Talpa', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 2,
      },
      {
        numeris: 12,
        pavadinimas: 'Duomenys ir tikimybės',
        potemes: [
          { pavadinimas: 'Kokybiniai ir kiekybiniai duomenys', lygis: 2 },
          { pavadinimas: 'Imtis, imties vidurkis', lygis: 2 },
          { pavadinimas: 'Bandymas ir jo baigtys', generatorius: 'tikimybe', lygis: 2 },
          { pavadinimas: 'Įvykio tikimybė', generatorius: 'tikimybe', lygis: 2 },
        ],
        generatorius: 'vidurkis',
        lygis: 2,
      },
    ],
  },

  {
    klase: 6,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Skaičiai',
        potemes: [
          { pavadinimas: 'Skaičiai skaičių tiesėje', lygis: 2 },
          { pavadinimas: 'Vienas kitam priešingieji skaičiai', generatorius: 'saknu-ivertinimas', lygis: 2 },
          { pavadinimas: 'Skaičių palyginimas', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Natūralieji, sveikieji, racionalieji skaičiai', generatorius: 'saknu-ivertinimas', lygis: 2 },
          { pavadinimas: 'Koordinačių plokštuma', lygis: 2 },
        ],
        generatorius: 'koordinates',
        lygis: 2,
      },
      {
        numeris: 2,
        pavadinimas: 'Racionaliųjų skaičių sudėtis ir atimtis',
        potemes: [
          { pavadinimas: 'Sudedame skaičius su vienodais ženklais', lygis: 2 },
          { pavadinimas: 'Sudedame skaičius su skirtingais ženklais', lygis: 2 },
          { pavadinimas: 'Atimame', lygis: 2 },
          { pavadinimas: 'Algebrinė suma', lygis: 2 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Neneigiamųjų paprastųjų trupmenų daugyba ir dalyba',
        potemes: [
          { pavadinimas: 'Paprastosios trupmenos ir natūraliojo skaičiaus daugyba', lygis: 2 },
          { pavadinimas: 'Dauginame paprastąsias trupmenas', lygis: 2 },
          { pavadinimas: 'Paprastąją trupmeną dalijame iš natūraliojo skaičiaus', generatorius: 'trupmenu-sudetis', lygis: 2 },
          { pavadinimas: 'Dalijame iš paprastosios trupmenos', lygis: 2 },
        ],
        generatorius: 'trupmenu-daugyba',
        lygis: 2,
      },
      {
        numeris: 4,
        pavadinimas: 'Neneigiamųjų dešimtainių skaičių daugyba ir dalyba',
        potemes: [
          { pavadinimas: 'Dešimtainį skaičių dauginame iš natūraliojo', lygis: 2 },
          { pavadinimas: 'Dauginame dešimtainius skaičius', lygis: 2 },
          { pavadinimas: 'Dešimtainį skaičių dalijame iš natūraliojo', lygis: 2 },
          { pavadinimas: 'Periodinės trupmenos', generatorius: 'trupmenu-sudetis', lygis: 2 },
          { pavadinimas: 'Dalijame dešimtainius skaičius', lygis: 2 },
        ],
        generatorius: 'desimtaines',
        lygis: 2,
      },
      {
        numeris: 5,
        pavadinimas: 'Teigiamųjų ir neigiamųjų skaičių daugyba ir dalyba',
        potemes: [
          { pavadinimas: 'Dauginame', lygis: 2 },
          { pavadinimas: 'Dalijame', lygis: 2 },
          { pavadinimas: 'Dauginame ir dalijame', lygis: 2 },
          { pavadinimas: 'Taikome skirstomumo dėsnį', lygis: 2 },
          { pavadinimas: 'Skaičiuojame skaitinių reiškinių reikšmes', generatorius: 'veiksmu-tvarka', lygis: 2 },
        ],
        generatorius: 'sveikieji',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Procentai. Proporcija',
        potemes: [
          { pavadinimas: 'Trupmenos, dešimtainiai skaičiai, procentai', lygis: 2 },
          { pavadinimas: 'Ieškome skaičiaus dalies', generatorius: 'dalies-radimas', lygis: 2 },
          { pavadinimas: 'Ieškome viso skaičiaus', lygis: 2 },
          { pavadinimas: 'Pagrindinė proporcijos savybė', generatorius: 'proporcijos', lygis: 2 },
          { pavadinimas: 'Procentų uždavinių sprendimas sudarant proporciją', lygis: 2 },
          { pavadinimas: 'Dalijimas proporcingai', generatorius: 'proporcijos', lygis: 2 },
          { pavadinimas: 'Finansiniai skaičiavimai: nuolaidos, vieneto tarifai, biudžetas ir mokesčiai', generatorius: 'palukanos', lygis: 2 },
        ],
        generatorius: 'procentai',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Tiesioginis proporcingumas',
        potemes: [
          { pavadinimas: 'Formulės, lentelės', lygis: 2 },
          { pavadinimas: 'Grafikai', generatorius: 'funkcijos', lygis: 2 },
          { pavadinimas: 'Tiesiogiai proporcingi dydžiai', lygis: 2 },
          { pavadinimas: 'Tiesiogiai proporcingų dydžių priklausomybės grafikas', generatorius: 'funkcijos', lygis: 2 },
        ],
        generatorius: 'proporcijos',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Reiškiniai. Lygtys',
        potemes: [
          { pavadinimas: 'Raidinio reiškinio koeficientas', lygis: 2 },
          { pavadinimas: 'Panašiųjų narių sutraukimas', lygis: 2 },
          { pavadinimas: 'Atskliautimas', lygis: 2 },
          { pavadinimas: 'Sprendžiame paprastas lygtis', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Sprendžiame sudėtingesnes lygtis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Sprendžiame lygtis su skliaustais', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Tekstinių uždavinių sprendimas sudarant lygtis', generatorius: 'tiesines-lygtys', lygis: 2 },
        ],
        generatorius: 'raidiniai-reiskiniai',
        lygis: 2,
      },
      {
        numeris: 9,
        pavadinimas: 'Lygios plokštumos figūros',
        potemes: [
          { pavadinimas: 'Lygios plokštumos figūros', lygis: 2 },
          { pavadinimas: 'Trikampio kraštinės ir kampai', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Trikampių lygumo požymis pagal dvi kraštines ir kampą tarp jų', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Trikampių lygumo požymis pagal kraštinę ir du kampus prie jos', lygis: 2 },
          { pavadinimas: 'Trikampių lygumo požymis pagal tris kraštines', lygis: 2 },
          { pavadinimas: 'Braižome kampą, lygų duotam kampui', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Braižome trikampį, lygų duotam trikampiui', lygis: 2 },
          { pavadinimas: 'Trikampio nelygybė', generatorius: 'nelygybes', lygis: 2 },
        ],
        generatorius: 'figuros',
        lygis: 2,
      },
      {
        numeris: 10,
        pavadinimas: 'Panašiosios plokštumos figūros',
        potemes: [
          { pavadinimas: 'Didiname ir mažiname', lygis: 2 },
          { pavadinimas: 'Mastelis', generatorius: 'proporcijos', lygis: 2 },
          { pavadinimas: 'Panašiosios plokštumos figūros', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Trikampių panašumo požymiai', generatorius: 'figuros', lygis: 2 },
          { pavadinimas: 'Figūrų didinimas, mažinimas ir figūrų sekos', generatorius: 'rekurencios-sekos', lygis: 2 },
          { pavadinimas: 'Metrinė matavimo sistema ir vienetų keitimas', lygis: 2 },
        ],
        generatorius: 'trigonometrija',
        lygis: 2,
      },
      {
        numeris: 11,
        pavadinimas: 'Duomenys',
        potemes: [
          { pavadinimas: 'Dažnių lentelė', lygis: 2 },
          { pavadinimas: 'Stulpelinė diagrama', lygis: 2 },
          { pavadinimas: 'Linijinė diagrama', lygis: 2 },
          { pavadinimas: 'Imties vidurkis', generatorius: 'vidurkis', lygis: 2 },
          { pavadinimas: 'Imties mediana', generatorius: 'vidurkis', lygis: 2 },
          { pavadinimas: 'Imties moda', generatorius: 'vidurkis', lygis: 2 },
        ],
        generatorius: 'diagramos',
        lygis: 2,
      },
      {
        numeris: 12,
        pavadinimas: 'Tikimybės',
        potemes: [
          { pavadinimas: 'Galimybių medis', lygis: 2 },
          { pavadinimas: 'Galimybių lentelė', lygis: 2 },
          { pavadinimas: 'Daugybos taisyklė', lygis: 2 },
          { pavadinimas: 'Įvykis', generatorius: 'tikimybe', lygis: 2 },
          { pavadinimas: 'Įvykio tikimybė', generatorius: 'tikimybe', lygis: 2 },
          { pavadinimas: 'Įvykiui priešingas įvykis ir jo tikimybė', generatorius: 'tikimybe', lygis: 2 },
        ],
        generatorius: 'kombinatorika',
        lygis: 2,
      },
    ],
  },

  {
    klase: 7,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Teiginiai',
        potemes: [
          { pavadinimas: 'Teisingi ir klaidingi teiginiai', generatorius: 'logika' },
          { pavadinimas: 'Aksioma, apibrėžimas, teorema', generatorius: 'logika' },
          { pavadinimas: 'Įrodymas', generatorius: 'logika' },
        ],
      },
      {
        numeris: 2,
        pavadinimas: 'Laipsniai',
        potemes: [
          { pavadinimas: 'Keliame kvadratu ir kubu', lygis: 2 },
          { pavadinimas: 'Laipsnis su natūraliuoju rodikliu', lygis: 2 },
          { pavadinimas: 'Dauginame ir dalijame laipsnius su vienodais pagrindais', lygis: 2 },
          { pavadinimas: 'Dauginame ir dalijame laipsnius su vienodais rodikliais', lygis: 2 },
          { pavadinimas: 'Laipsnį keliame laipsniu', lygis: 2 },
          { pavadinimas: 'Laipsnis su sveikuoju neigiamuoju rodikliu', lygis: 2 },
          { pavadinimas: 'Laipsnio su sveikuoju neigiamuoju rodikliu savybės', lygis: 2 },
          { pavadinimas: 'Standartinė skaičiaus išraiška', lygis: 2 },
        ],
        generatorius: 'laipsniai',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Procentai',
        potemes: [
          { pavadinimas: 'Ieškome, kiek procentų pakito dydis', lygis: 2 },
          { pavadinimas: 'Ieškome dydžio, kai žinoma jo pradinė vertė ir pokytis procentais', lygis: 2 },
          { pavadinimas: 'Paprastosios palūkanos', generatorius: 'palukanos', lygis: 2 },
          { pavadinimas: 'Sudėtinės palūkanos', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Sudėtiniai procentai', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Biudžetas, finansiniai tikslai ir paskolų pasiūlymų palyginimas', generatorius: 'palukanos', lygis: 2 },
        ],
        generatorius: 'procentai',
        lygis: 2,
      },
      {
        numeris: 4,
        pavadinimas: 'Nelygybės',
        potemes: [
          { pavadinimas: 'Skaičių palyginimas', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Skaičių intervalai', lygis: 2 },
          { pavadinimas: 'Prie (iš) abiejų nelygybės pusių pridedame (atimame) tą patį skaičių', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Abi nelygybės puses dauginame (dalijame) iš to paties skaičiaus', lygis: 2 },
          { pavadinimas: 'Nelygybės sprendinys', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Sprendžiame vieno žingsnio nelygybes', lygis: 2 },
          { pavadinimas: 'Sprendžiame paprastas nelygybes', lygis: 2 },
          { pavadinimas: 'Sprendžiame sudėtingesnes nelygybes', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Dviejų nelygybių su vienu nežinomuoju sistema', lygis: 2 },
          { pavadinimas: 'Dvigubųjų nelygybių sprendimas', lygis: 2 },
          { pavadinimas: 'Sprendžiame tekstinius uždavinius', lygis: 2 },
        ],
        generatorius: 'nelygybes',
        lygis: 2,
      },
      {
        numeris: 5,
        pavadinimas: 'Atvirkštinis proporcingumas',
        potemes: [
          { pavadinimas: 'Tarpusavyje susiję dydžiai', lygis: 2 },
          { pavadinimas: 'Atvirkščiai proporcingi dydžiai', generatorius: 'atvirkstinis', lygis: 2 },
          { pavadinimas: 'Atvirkščiai proporcingų dydžių priklausomybės grafikas', generatorius: 'atvirkstinis', lygis: 2 },
          { pavadinimas: 'Tekstinių uždavinių sprendimas', lygis: 2 },
        ],
        generatorius: 'proporcijos',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Tiesės',
        potemes: [
          { pavadinimas: 'Taškas ir tiesė', lygis: 2 },
          { pavadinimas: 'Susikertančiosios tiesės', lygis: 2 },
          { pavadinimas: 'Lygiagrečiosios tiesės', lygis: 2 },
          { pavadinimas: 'Dviejų tiesių lygiagretumo požymiai', lygis: 2 },
          { pavadinimas: 'Kampų, susidariusių dvi lygiagrečiąsias tieses perkirtus kirstine, savybės', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Konstravimas ir transformacijos koordinačių plokštumoje', generatorius: 'simetrija', lygis: 2 },
        ],
        generatorius: 'trigonometrija',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Trikampiai ir keturkampiai',
        potemes: [
          { pavadinimas: 'Trikampių rūšys', lygis: 2 },
          { pavadinimas: 'Trikampio aukštinės', lygis: 2 },
          { pavadinimas: 'Trikampio pusiaukraštinės', lygis: 2 },
          { pavadinimas: 'Trikampio pusiaukampinės', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Lygiagretainis', lygis: 2 },
          { pavadinimas: 'Stačiakampis', generatorius: 'trigonometrija', lygis: 2 },
          { pavadinimas: 'Rombas', lygis: 2 },
          { pavadinimas: 'Kvadratas', generatorius: 'trigonometrija', lygis: 2 },
          { pavadinimas: 'Trapecija', lygis: 2 },
          { pavadinimas: 'Lygiašonė ir stačioji trapecijos', lygis: 2 },
          { pavadinimas: 'Daugiakampiai koordinačių plokštumoje', lygis: 2 },
        ],
        generatorius: 'figuros',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Trikampių ir keturkampių plotai',
        potemes: [
          { pavadinimas: 'Stačiakampio, kvadrato ir stačiojo trikampio plotų formulės', lygis: 2 },
          { pavadinimas: 'Trikampio ploto formulė', lygis: 2 },
          { pavadinimas: 'Lygiagretainio ploto formulė', lygis: 2 },
          { pavadinimas: 'Rombo ploto formulė', lygis: 2 },
          { pavadinimas: 'Trapecijos ploto formulė', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 2,
      },
      {
        numeris: 9,
        pavadinimas: 'Apskritimas ir skritulys',
        potemes: [
          { pavadinimas: 'Apskritimas', lygis: 2 },
          { pavadinimas: 'Apskritimo ilgis', lygis: 2 },
          { pavadinimas: 'Apskritimo lankas ir jo ilgis', lygis: 2 },
          { pavadinimas: 'Skritulys. Skritulio ir jo dalies plotai', lygis: 2 },
        ],
        generatorius: 'apskritimas',
        lygis: 2,
      },
      {
        numeris: 10,
        pavadinimas: 'Stačioji prizmė ir taisyklingoji piramidė',
        potemes: [
          { pavadinimas: 'Tiesės ir plokštumos erdvėje', lygis: 2 },
          { pavadinimas: 'Stačioji prizmė', generatorius: 'prizme', lygis: 2 },
          { pavadinimas: 'Stačiosios prizmės tūris', lygis: 2 },
          { pavadinimas: 'Piramidė', generatorius: 'piramide', lygis: 2 },
          { pavadinimas: 'Taisyklingoji piramidė ir jos tūris', lygis: 2 },
        ],
        generatorius: 'plotas-turis',
        lygis: 2,
      },
      {
        numeris: 11,
        pavadinimas: 'Ritinys ir kūgis',
        potemes: [
          { pavadinimas: 'Ritinys', lygis: 2 },
          { pavadinimas: 'Ritinio paviršiaus plotas ir tūris', lygis: 2 },
          { pavadinimas: 'Kūgis', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Kūgio paviršiaus plotas ir tūris', generatorius: 'plotas-turis', lygis: 2 },
        ],
        generatorius: 'apskritimas',
        lygis: 2,
      },
      {
        numeris: 12,
        pavadinimas: 'Duomenys',
        potemes: [
          { pavadinimas: 'Statistinis tyrimas. Populiacija', lygis: 2 },
          { pavadinimas: 'Imtis. Paprastoji atsitiktinė imtis', lygis: 2 },
          { pavadinimas: 'Sisteminė, sluoksninė, lizdinė atsitiktinės imtys', lygis: 2 },
          { pavadinimas: 'Statistinis kintamasis', lygis: 2 },
          { pavadinimas: 'Duomenų pateikimas skrituline diagrama', generatorius: 'apskritimas', lygis: 2 },
        ],
        generatorius: 'vidurkis',
        lygis: 2,
      },
    ],
  },

  {
    klase: 8,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Kvadratinė ir kubinė šaknys',
        potemes: [
          { pavadinimas: 'Kvadratinė šaknis', generatorius: 'saknys', lygis: 2 },
          { pavadinimas: 'Kubinė šaknis', generatorius: 'saknys', lygis: 2 },
          { pavadinimas: 'Iracionalieji skaičiai', lygis: 2 },
          { pavadinimas: 'Palyginame', generatorius: 'skaiciu-palyginimas', lygis: 2 },
          { pavadinimas: 'Sudedame ir atimame', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Šaknis iš sandaugos', lygis: 2 },
          { pavadinimas: 'Šaknis iš trupmenos', lygis: 2 },
          { pavadinimas: 'Iškeliame prieš šaknies ženklą, įkeliame į pošaknį', lygis: 2 },
          { pavadinimas: 'Skaitinių reiškinių su šaknimis pertvarkiai', lygis: 2 },
          { pavadinimas: 'Raidinių reiškinių su šaknimis pertvarkiai', lygis: 2 },
        ],
        generatorius: 'saknu-ivertinimas',
        lygis: 2,
      },
      {
        numeris: 2,
        pavadinimas: 'Skaičių aibės',
        potemes: [
          { pavadinimas: 'Skaičių aibės', lygis: 2 },
          { pavadinimas: 'Skaičių aibės poaibis', lygis: 2 },
          { pavadinimas: 'Realieji skaičiai', lygis: 2 },
          { pavadinimas: 'Veiksmai su realiaisiais skaičiais', lygis: 2 },
        ],
        generatorius: 'saknu-ivertinimas',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Finansiniai skaičiavimai',
        potemes: [
          { pavadinimas: 'Valiutų kursai', lygis: 2 },
          { pavadinimas: 'Paprastosios ir sudėtinės palūkanos', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Paprastosios palūkanos ir grafikai', lygis: 2 },
          { pavadinimas: 'Pirkimas išsimokėtinai', lygis: 2 },
          { pavadinimas: 'Mažėjančiosios palūkanos', lygis: 2 },
        ],
        generatorius: 'palukanos',
        lygis: 2,
      },
      {
        numeris: 4,
        pavadinimas: 'Reiškiniai',
        potemes: [
          { pavadinimas: 'Vienanaris ir daugianaris', generatorius: 'raidiniai-reiskiniai', lygis: 2 },
          { pavadinimas: 'Atskliautimas', generatorius: 'raidiniai-reiskiniai', lygis: 2 },
          { pavadinimas: 'Daugianarių daugyba', generatorius: 'raidiniai-reiskiniai', lygis: 2 },
          { pavadinimas: 'Dvinario kėlimas kvadratu', lygis: 2 },
          { pavadinimas: 'Dviejų narių sumos dauginimas iš tų narių skirtumo', lygis: 2 },
          { pavadinimas: 'Bendrojo dauginamojo iškėlimas prieš skliaustus', lygis: 2 },
          { pavadinimas: 'Skaidymas dauginamaisiais grupavimo būdu', lygis: 2 },
          { pavadinimas: 'Skaidymas dauginamaisiais taikant greitosios daugybos formules', lygis: 2 },
          { pavadinimas: 'Dvinario kvadrato išskyrimas', lygis: 2 },
        ],
        generatorius: 'greitosios-formules',
        lygis: 2,
      },
      {
        numeris: 5,
        pavadinimas: 'Tiesinių lygčių sistemos',
        potemes: [
          { pavadinimas: 'Tiesinė lygtis su dviem nežinomaisiais', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Tiesinės lygties su dviem nežinomaisiais grafikas', generatorius: 'funkcijos', lygis: 2 },
          { pavadinimas: 'Tiesinių lygčių su dviem nežinomaisiais sistema', lygis: 2 },
          { pavadinimas: 'Tiesinių lygčių sistemos sprendinių skaičius', lygis: 2 },
          { pavadinimas: 'Sprendžiame tiesinių lygčių sistemas keitimo būdu', lygis: 2 },
          { pavadinimas: 'Sprendžiame tiesinių lygčių sistemas sulyginimo būdu', lygis: 2 },
          { pavadinimas: 'Sprendžiame tiesinių lygčių sistemas sudėties būdu', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Judėjimo uždaviniai', lygis: 2 },
          { pavadinimas: 'Įvairūs tekstiniai uždaviniai', lygis: 2 },
          { pavadinimas: 'Tiesinis sąryšis: lentelė, formulė ir grafikas', generatorius: 'funkcijos', lygis: 2 },
        ],
        generatorius: 'lygciu-sistemos',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Vektoriai',
        potemes: [
          { pavadinimas: 'Vektoriaus sąvoka', lygis: 2 },
          { pavadinimas: 'Vektorių lygumas', lygis: 2 },
          { pavadinimas: 'Vektorių sudėtis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Vektorių atimtis', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Vektoriaus daugyba iš skaičiaus', lygis: 2 },
        ],
        generatorius: 'vektoriai',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Plokštumos figūros',
        potemes: [
          { pavadinimas: 'Pitagoro teorema', generatorius: 'pitagoras', lygis: 2 },
          { pavadinimas: 'Atvirkštinė Pitagoro teorema', generatorius: 'atvirkstinis', lygis: 2 },
          { pavadinimas: 'Atstumas tarp dviejų koordinačių plokštumos taškų', generatorius: 'pitagoras', lygis: 2 },
          { pavadinimas: 'Stačiojo trikampio statinis, esantis prieš 30° kampą', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Lygiašonis ir lygiakraštis trikampiai', lygis: 2 },
          { pavadinimas: 'Trikampio vidurio linija', lygis: 2 },
          { pavadinimas: 'Trapecijos vidurio linija', lygis: 2 },
        ],
        generatorius: 'figuros',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Erdviniai kūnai',
        potemes: [
          { pavadinimas: 'Stačioji prizmė', generatorius: 'prizme', lygis: 2 },
          { pavadinimas: 'Taisyklingoji piramidė', generatorius: 'piramide', lygis: 2 },
          { pavadinimas: 'Ritinys', generatorius: 'apskritimas', lygis: 2 },
          { pavadinimas: 'Kūgis', lygis: 2 },
          { pavadinimas: 'Rutulys ir sfera', lygis: 2 },
          { pavadinimas: 'Objekto vaizdai iš viršaus, priekio ir šono bei mastelis', generatorius: 'proporcijos', lygis: 2 },
        ],
        generatorius: 'erdvines-figuros',
        lygis: 2,
      },
      {
        numeris: 9,
        pavadinimas: 'Duomenys',
        potemes: [
          { pavadinimas: 'Empirinis skirstinys', generatorius: 'sklaida', lygis: 2 },
          { pavadinimas: 'Sukauptasis ir sukauptasis santykinis dažniai', lygis: 2 },
          { pavadinimas: 'Sugrupuotų duomenų stulpelinė diagrama', lygis: 2 },
          { pavadinimas: 'Histograma', lygis: 2 },
          { pavadinimas: 'Imties skaitinės charakteristikos', generatorius: 'vidurkis', lygis: 2 },
          { pavadinimas: 'Kvartiliai', generatorius: 'sklaida', lygis: 2 },
          { pavadinimas: 'Stačiakampė diagrama su „ūsais“', lygis: 2 },
        ],
        generatorius: 'diagramos',
        lygis: 2,
      },
      {
        numeris: 10,
        pavadinimas: 'Progimnazijos kurso kartojimo medžiaga',
        potemes: [
          { pavadinimas: 'Skaičių aibės', generatorius: 'saknu-ivertinimas', lygis: 2 },
          { pavadinimas: 'Skaičių dalumas', generatorius: 'dalumo-pozymiai', lygis: 2 },
          { pavadinimas: 'Aritmetiniai veiksmai su skaičiais', generatorius: 'skaitmenys', lygis: 2 },
          { pavadinimas: 'Paprastosios trupmenos', generatorius: 'trupmenu-sudetis', lygis: 2 },
          { pavadinimas: 'Proporcingumas', generatorius: 'proporcijos', lygis: 2 },
          { pavadinimas: 'Procentai', generatorius: 'procentai', lygis: 2 },
          { pavadinimas: 'Laipsniai. Šaknys', generatorius: 'laipsniai', lygis: 2 },
          { pavadinimas: 'Raidininiai reiškiniai', generatorius: 'raidiniai-reiskiniai', lygis: 2 },
          { pavadinimas: 'Lygtys, lygčių sistemos', generatorius: 'lygciu-sistemos', lygis: 2 },
          { pavadinimas: 'Nelygybės, nelygybių sistemos', generatorius: 'nelygybes', lygis: 2 },
          { pavadinimas: 'Kampai', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Trikampiai', lygis: 2 },
          { pavadinimas: 'Keturkampiai. Daugiakampiai', lygis: 2 },
          { pavadinimas: 'Apskritimas. Skritulys', generatorius: 'apskritimas', lygis: 2 },
          { pavadinimas: 'Vektoriai', generatorius: 'vektoriai', lygis: 2 },
          { pavadinimas: 'Simetrija. Posūkis. Postūmis', generatorius: 'simetrija', lygis: 2 },
          { pavadinimas: 'Erdviniai kūnai', generatorius: 'erdvines-figuros', lygis: 2 },
          { pavadinimas: 'Rinkinių skaičius. Statistika', generatorius: 'kombinatorika', lygis: 2 },
          { pavadinimas: 'Tikimybės', generatorius: 'tikimybe', lygis: 2 },
        ],
        generatorius: 'pupp',
        lygis: 2,
      },
    ],
  },

  {
    klase: 9,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Funkcijos, sekos',
        potemes: [
          { pavadinimas: 'Tarpusavyje susiję dydžiai', lygis: 2 },
          { pavadinimas: 'Funkcija ir jos grafikas', lygis: 2 },
          { pavadinimas: 'Funkcijos savybės', lygis: 2 },
          { pavadinimas: 'Skaičių seka', generatorius: 'rekurencios-sekos', lygis: 2 },
          { pavadinimas: 'Skaičių sekos, išreikštos rekurentiškai', generatorius: 'rekurencios-sekos', lygis: 2 },
          { pavadinimas: 'Funkcijos apibrėžimo ir reikšmių sritys', lygis: 2 },
        ],
        generatorius: 'funkcijos',
        lygis: 2,
      },
      {
        numeris: 2,
        pavadinimas: 'Tiesinė funkcija',
        potemes: [
          { pavadinimas: 'Tiesioginio proporcingumo funkcija', lygis: 2 },
          { pavadinimas: 'Tiesinė funkcija', lygis: 2 },
          { pavadinimas: 'Tiesinės funkcijos savybės', lygis: 2 },
          { pavadinimas: 'Dviejų tiesių tarpusavio padėtis', lygis: 2 },
        ],
        generatorius: 'funkcijos',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Kvadratinė lygtis',
        potemes: [
          { pavadinimas: 'Kvadratinės lygties samprata', lygis: 2 },
          { pavadinimas: 'Nepilnosios kvadratinės lygtys', generatorius: 'kvadratines-lygtys', lygis: 2 },
          { pavadinimas: 'Pilnoji kvadratinė lygtis', generatorius: 'tiesines-lygtys', lygis: 2 },
          { pavadinimas: 'Kvadratinės lygties sprendinių formulės', generatorius: 'kvadratines-lygtys', lygis: 2 },
          { pavadinimas: 'Kvadratinio trinario skaidymas dauginamaisiais', generatorius: 'greitosios-formules', lygis: 2 },
          { pavadinimas: 'Vijeto teorema', lygis: 2 },
        ],
        generatorius: 'vijeto',
        lygis: 2,
      },
      {
        numeris: 4,
        pavadinimas: 'Kvadratinė funkcija',
        potemes: [
          { pavadinimas: 'Kvadratinės funkcijos samprata', lygis: 2 },
          { pavadinimas: 'Grafiko transformacijos', generatorius: 'funkcijos', lygis: 2 },
          { pavadinimas: 'Kvadratinės funkcijos grafikas ir savybės', lygis: 2 },
        ],
        generatorius: 'kvadratines-lygtys',
        lygis: 2,
      },
      {
        numeris: 5,
        pavadinimas: 'Trupmeniniai racionalieji reiškiniai',
        potemes: [
          { pavadinimas: 'Trupmeninio racionaliojo reiškinio samprata', generatorius: 'trupmenu-sudetis', lygis: 2 },
          { pavadinimas: 'Trupmeninių racionaliųjų reiškinių daugyba, dalyba ir kėlimas laipsniu', generatorius: 'laipsniai', lygis: 2 },
          { pavadinimas: 'Trupmeninių racionaliųjų reiškinių sudėtis ir atimtis', lygis: 2 },
          { pavadinimas: 'Sudėtingesnių uždavinių sprendimas', lygis: 2 },
        ],
        generatorius: 'sudetis-atimtis',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Lygčių sistemos',
        potemes: [
          { pavadinimas: 'Lygčių sistemų sprendimas algebriniais būdais', lygis: 2 },
          { pavadinimas: 'Lygčių sistemų sprendimas grafiniu būdu', lygis: 2 },
          { pavadinimas: 'Sudėtingesnių lygčių sistemų sprendimas', generatorius: 'sudetis-atimtis', lygis: 2 },
        ],
        generatorius: 'lygciu-sistemos',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Įvadas į trigonometriją',
        potemes: [
          { pavadinimas: 'Smailiojo kampo sinusas, kosinusas ir tangentas', lygis: 2 },
          { pavadinimas: 'Trigonometrinių santykių reikšmės', lygis: 2 },
          { pavadinimas: 'Skaičiuojame skaičiuotuvu', lygis: 2 },
          { pavadinimas: 'Trigonometrinės formulės', lygis: 2 },
          { pavadinimas: 'Stačiųjų trikampių sprendimas', generatorius: 'figuros', lygis: 2 },
        ],
        generatorius: 'trigonometrija',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Apskritimas ir skritulys',
        potemes: [
          { pavadinimas: 'Apskritimo liestinė ir kirstinė', lygis: 2 },
          { pavadinimas: 'Apskritimo centrinis ir įbrėžtinis kampai', lygis: 2 },
          { pavadinimas: 'Apskritimo stygų savybės', lygis: 2 },
          { pavadinimas: 'Skritulio išpjova ir nuopjova', lygis: 2 },
          { pavadinimas: 'Kirstinių, liestinių, stygų proporcingos atkarpos ir sudaromi kampai', generatorius: 'kampai', lygis: 2 },
        ],
        generatorius: 'apskritimas',
        lygis: 2,
      },
      {
        numeris: 9,
        pavadinimas: 'Duomenys ir jų interpretavimas',
        potemes: [
          { pavadinimas: 'Sklaidos diagrama', generatorius: 'diagramos', lygis: 2 },
          { pavadinimas: 'Tiesinė koreliacija', lygis: 2 },
          { pavadinimas: 'Tiesė sklaidos diagramo', generatorius: 'diagramos', lygis: 2 },
          { pavadinimas: 'Imties dydžio ir atsitiktinumo įtaka išvadoms', lygis: 2 },
          { pavadinimas: 'Koreliacija nėra priežastinis ryšys', lygis: 2 },
        ],
        generatorius: 'vidurkis',
        lygis: 2,
      },
    ],
  },

  {
    klase: 10,
    temos: [
      {
        numeris: 1,
        pavadinimas: 'Trupmeninė racionalioji lygtis',
        potemes: [
          { pavadinimas: 'Trupmeninės racionaliosios lygties samprata', generatorius: 'trupmenu-sudetis', lygis: 2 },
          { pavadinimas: 'Lygčių sprendimas taikant trupmenos, lygios nuliui, savybę', lygis: 2 },
          { pavadinimas: 'Kiti trupmeninių lygčių sprendimo būdai', lygis: 2 },
          { pavadinimas: 'Judėjimo uždaviniai', lygis: 2 },
          { pavadinimas: 'Darbo uždaviniai', lygis: 2 },
          { pavadinimas: 'Mišiniai', generatorius: 'misiniai', lygis: 2 },
        ],
        generatorius: 'tiesines-lygtys',
        lygis: 2,
      },
      {
        numeris: 2,
        pavadinimas: 'Trigonometrijos pagrindai',
        potemes: [
          { pavadinimas: 'Posūkio kampo sinusas, kosinusas ir tangentas', lygis: 2 },
          { pavadinimas: 'Sinuso, kosinuso ir tangento reikšmės', lygis: 2 },
          { pavadinimas: 'Trikampio ploto skaičiavimo formulė', generatorius: 'plotas-turis', lygis: 2 },
          { pavadinimas: 'Sinusų teorema', lygis: 2 },
          { pavadinimas: 'Kosinusų teorema', lygis: 2 },
        ],
        generatorius: 'trigonometrija',
        lygis: 2,
      },
      {
        numeris: 3,
        pavadinimas: 'Lygčių su dviem nežinomaisiais sistemos',
        potemes: [
          { pavadinimas: 'Lygčių su dviem nežinomaisiais sistema ir jos sprendiniai', lygis: 2 },
          { pavadinimas: 'Atvirkštinio proporcingumo funkcija', generatorius: 'atvirkstinis', lygis: 2 },
          { pavadinimas: 'Lygčių sistemų sprendimas grafiniu būdu', lygis: 2 },
          { pavadinimas: 'Lygčių sistemų sprendimas algebriniais būdais', lygis: 2 },
          { pavadinimas: 'Uždavinių sprendimas, sudarant lygčių sistemas', lygis: 2 },
          { pavadinimas: 'Lygčių sistemų sprendimas, įvedant keitinius', lygis: 2 },
        ],
        generatorius: 'lygciu-sistemos',
        lygis: 2,
      },
      {
        numeris: 4,
        pavadinimas: 'Nelygybės ir jų sistemos',
        potemes: [
          { pavadinimas: 'Kvadratinės nelygybės samprata', lygis: 2 },
          { pavadinimas: 'Kvadratinės nelygybės sprendimas, remiantis parabolės savybėmis', lygis: 2 },
          { pavadinimas: 'Kvadratinės nelygybės keitimas nelygybių sistemomis', lygis: 2 },
          { pavadinimas: 'Kvadratinių nelygybių taikymas', lygis: 2 },
          { pavadinimas: 'Nelygybių sistemos ir dvigubosios nelygybės', lygis: 2 },
          { pavadinimas: 'Trupmeninių nelygybių sprendimas', lygis: 2 },
        ],
        generatorius: 'nelygybes',
        lygis: 2,
      },
      {
        numeris: 5,
        pavadinimas: 'Dėsningumai, santykiai ir procentai',
        potemes: [
          { pavadinimas: 'Probleminės situacijos ir trūkstamos informacijos nustatymas', lygis: 2 },
          { pavadinimas: 'Proporcingoji dalyba į dvi nelygias dalis', generatorius: 'sveikieji', lygis: 2 },
          { pavadinimas: 'Fibonačio skaičių seka', lygis: 2 },
          { pavadinimas: 'Aukso pjūvio skaičius ir aukso pjūvio seka', lygis: 2 },
          { pavadinimas: 'Sudėtiniai procentai', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Džiovinimo ir drėkinimo uždaviniai', lygis: 2 },
          { pavadinimas: 'Lydiniai, mišiniai, tirpalai ir koncentracija', generatorius: 'misiniai', lygis: 2 },
        ],
        generatorius: 'rekurencios-sekos',
        lygis: 2,
      },
      {
        numeris: 6,
        pavadinimas: 'Plokštumos figūros',
        potemes: [
          { pavadinimas: 'Panašiųjų figūrų perimetrų ir plotų santykiai', generatorius: 'perimetras', lygis: 2 },
          { pavadinimas: 'Trikampio pusiaukampinių savybės', generatorius: 'kampai', lygis: 2 },
          { pavadinimas: 'Trikampio pusiaukraštinių savybės', lygis: 2 },
          { pavadinimas: 'Į trikampį įbrėžtas apskritimas', generatorius: 'apskritimas', lygis: 2 },
          { pavadinimas: 'Apie trikampį apibrėžtas apskritimas', generatorius: 'apskritimas', lygis: 2 },
          { pavadinimas: 'Trikampio ploto formulės S = rp ir S = abc/(4R)', generatorius: 'plotas-turis', lygis: 2 },
          { pavadinimas: 'Įbrėžtiniai ir apibrėžtiniai keturkampiai', lygis: 2 },
          { pavadinimas: 'Geometrinių teiginių įrodymas', generatorius: 'trigonometrija', lygis: 2 },
        ],
        generatorius: 'figuros',
        lygis: 2,
      },
      {
        numeris: 7,
        pavadinimas: 'Duomenys ir jų interpretavimas',
        potemes: [
          { pavadinimas: 'Populiacija, imtis ir pagrįstos išvados', generatorius: 'vidurkis', lygis: 2 },
          { pavadinimas: 'Duomenų kintamumas ir pasiskirstymas', generatorius: 'vidurkis', lygis: 2 },
          { pavadinimas: 'Dispersija ir standartinis nuokrypis', lygis: 2 },
          { pavadinimas: 'Normalusis, simetriškasis ir asimetriškasis skirstiniai', generatorius: 'simetrija', lygis: 2 },
          { pavadinimas: 'Duomenų centro ir sklaidos charakteristikų interpretavimas', lygis: 2 },
          { pavadinimas: 'Statistinis patikimumas', lygis: 2 },
        ],
        generatorius: 'sklaida',
        lygis: 2,
      },
      {
        numeris: 8,
        pavadinimas: 'Rinkiniai, kombinatorika ir tikimybės',
        potemes: [
          { pavadinimas: 'Kelių elementų rinkiniai', lygis: 2 },
          { pavadinimas: 'Elementų tvarka rinkinyje', lygis: 2 },
          { pavadinimas: 'Rinkinių skaičiaus apskaičiavimas', lygis: 2 },
          { pavadinimas: 'Kombinatorikos sudėties taisyklė', generatorius: 'sudetis-atimtis', lygis: 2 },
          { pavadinimas: 'Kombinatorikos daugybos taisyklė', lygis: 2 },
          { pavadinimas: 'Teorinė ir eksperimentinė tikimybė', generatorius: 'tikimybe', lygis: 2 },
          { pavadinimas: 'Ilgalaikis santykinis dažnis', generatorius: 'diagramos', lygis: 2 },
        ],
        generatorius: 'kombinatorika',
        lygis: 2,
      },
    ],
  },
]

/** Kiek programos temų jau turi uždavinių generatorių. */
export function padengimas(): { isViso: number; suGeneratoriumi: number } {
  const visos = programa.flatMap((k) => k.temos)
  return {
    isViso: visos.length,
    suGeneratoriumi: visos.filter((t) => t.generatorius).length,
  }
}
