/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    naudotojai: NaudotojaiAuthOperations;
  };
  blocks: {};
  collections: {
    straipsniai: Straipsniai;
    failai: Failai;
    naudotojai: Naudotojai;
    mokiniai: Mokiniai;
    grupes: Grupe;
    zurnalas: Zurnala;
    saskaitos: Saskaito;
    rezervacijos: Rezervacijo;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    straipsniai: StraipsniaiSelect<false> | StraipsniaiSelect<true>;
    failai: FailaiSelect<false> | FailaiSelect<true>;
    naudotojai: NaudotojaiSelect<false> | NaudotojaiSelect<true>;
    mokiniai: MokiniaiSelect<false> | MokiniaiSelect<true>;
    grupes: GrupesSelect<false> | GrupesSelect<true>;
    zurnalas: ZurnalasSelect<false> | ZurnalasSelect<true>;
    saskaitos: SaskaitosSelect<false> | SaskaitosSelect<true>;
    rezervacijos: RezervacijosSelect<false> | RezervacijosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'lt' | 'lt'[];
  globals: {
    nustatymai: Nustatymai;
    priminimai: Priminimai;
    tvarkarastis: Tvarkarasti;
    atsiskaitymai: Atsiskaitymai;
  };
  globalsSelect: {
    nustatymai: NustatymaiSelect<false> | NustatymaiSelect<true>;
    priminimai: PriminimaiSelect<false> | PriminimaiSelect<true>;
    tvarkarastis: TvarkarastisSelect<false> | TvarkarastisSelect<true>;
    atsiskaitymai: AtsiskaitymaiSelect<false> | AtsiskaitymaiSelect<true>;
  };
  locale: 'lt';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Naudotojai;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface NaudotojaiAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tinklaraščio įrašai. Juodraščiai svetainėje nerodomi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "straipsniai".
 */
export interface Straipsniai {
  id: number;
  pavadinimas: string;
  /**
   * Pvz. „kaip-mokytis-daugybos“. Paskelbus nebekeisti.
   */
  nuoroda: string;
  /**
   * Rodoma sąraše ir paieškos rezultatuose. Iki 200 ženklų.
   */
  santrauka: string;
  virselis?: (number | null) | Failai;
  turinys: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  busena: 'juodrastis' | 'paskelbta';
  paskelbta?: string | null;
  klases?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10')[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Failai;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "failai".
 */
export interface Failai {
  id: number;
  /**
   * Ką matyti paveikslėlyje. Būtina dėl prieinamumo ir SEO.
   */
  alt: string;
  kategorija?: ('straipsnis' | 'nmpp' | 'pupp' | 'kita') | null;
  /**
   * Kuriai klasei skirta užduotis.
   */
  klase?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    perzvalga?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    virselis?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "naudotojai".
 */
export interface Naudotojai {
  id: number;
  vardas: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'naudotojai';
}
/**
 * Kam siunčiami priminimai. Pamokos kartojasi kas savaitę; pakeitimai galioja nuo kito siuntimo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mokiniai".
 */
export interface Mokiniai {
  id: number;
  vardas: string;
  klase?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
  tevoVardas?: string | null;
  /**
   * Šiuo adresu eina priminimai. Be jo siųsti nėra kur.
   */
  tevoPastas: string;
  /**
   * Nuolatinė šio vaiko kambario nuoroda, pvz. https://meet.google.com/abc-defg-hij. Tėvams siunčiama ne ji, o vardiklis.lt nuoroda, kuri atveda čia — todėl pakeitus ją, tėvams pranešti nereikia. Grupinėms pamokoms nuoroda imama iš grupės, ne iš čia.
   */
  meetNuoroda: string;
  /**
   * Kartojasi, kol nuimta „Aktyvus“ arba pamoka ištrinta. Nepalikus nė vienos eilutės, priminimų šiam mokiniui nebus. Grupinių pamokų čia rašyti nereikia — jos gyvena „Grupėse“.
   */
  pamokos?:
    | {
        kartojimas: 'savaite' | 'menuo';
        /**
         * Formatas 17:00, Lietuvos laiku.
         */
        laikas: string;
        trukmeMin?: number | null;
        savaitesDiena?: ('1' | '2' | '3' | '4' | '5' | '6' | '7') | null;
        kasKiek?: ('1' | '2' | '3' | '4') | null;
        /**
         * Nuo jos skaičiuojamos „kas antra“ savaitės. Būtina, kai pasirinkta rečiau nei kas savaitę.
         */
        nuoDatos?: string | null;
        /**
         * Pvz. 15 — pamoka kas mėnesio 15 dieną. Mėnesiais, kuriuose tokios dienos nėra, pamokos nebus.
         */
        menesioDiena?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Nuėmus varnelę priminimai nustoja eiti, o įrašas lieka.
   */
  aktyvus?: boolean | null;
  /**
   * Įjungta — laiške paminima pirmos pamokos nuolaida. Pažymėjus žurnale „Įvyko“, varnelė nusiima pati.
   */
  pirmaPamoka?: boolean | null;
  /**
   * Atostogoms. Iki šios dienos imtinai priminimai nesiunčiami.
   */
  pauzeIki?: string | null;
  sutikimas?: boolean | null;
  priminimoKada?: ('' | 'rytas' | 'vakaras') | null;
  /**
   * Pvz. 07:30. Palikus tuščią — kaip bendruose nustatymuose.
   */
  priminimoValanda?: string | null;
  pastabos?: string | null;
  /**
   * Iš jo sudaroma nuoroda vardiklis.lt/p/… Nekeičiamas.
   */
  raktas?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelių vaikų pamokos vienu metu. Kaina grupinei pamokai — iš „Sąskaitų nustatymų“.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grupes".
 */
export interface Grupe {
  id: number;
  /**
   * Pvz. „8 klasė, penktadieniais“. Tėvai jo nemato.
   */
  pavadinimas: string;
  /**
   * Nuėmus varnelę priminimai nustoja eiti, o įrašas lieka.
   */
  aktyvi?: boolean | null;
  /**
   * Kiekvienam nariui priminimas eina atskirai, jo tėvų adresu — su šios grupės nuoroda.
   */
  nariai: (number | Mokiniai)[];
  /**
   * Bendras šios grupės kambarys. Tėvams siunčiama ne ji, o kiekvieno vaiko vardiklis.lt/p/… nuoroda, kuri grupinės pamokos metu atveda būtent čia.
   */
  meetNuoroda: string;
  /**
   * Kartojasi, kol nuimta „Aktyvi“ arba pamoka ištrinta. Šie laikai kalendoriuje užima langą lygiai taip pat, kaip individualūs.
   */
  pamokos?:
    | {
        kartojimas: 'savaite' | 'menuo';
        /**
         * Formatas 17:00, Lietuvos laiku.
         */
        laikas: string;
        trukmeMin?: number | null;
        savaitesDiena?: ('1' | '2' | '3' | '4' | '5' | '6' | '7') | null;
        kasKiek?: ('1' | '2' | '3' | '4') | null;
        /**
         * Nuo jos skaičiuojamos „kas antra“ savaitės. Būtina, kai pasirinkta rečiau nei kas savaitę.
         */
        nuoDatos?: string | null;
        /**
         * Pvz. 15 — pamoka kas mėnesio 15 dieną. Mėnesiais, kuriuose tokios dienos nėra, pamokos nebus.
         */
        menesioDiena?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Atostogoms visai grupei. Atskiro vaiko pauzė nurodoma jo kortelėje ir galioja ir čia.
   */
  pauzeIki?: string | null;
  pastabos?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ką sistema išsiuntė ir kas iš to išėjo. Įrašus kuria pati sistema.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zurnalas".
 */
export interface Zurnala {
  id: number;
  /**
   * Sudaroma automatiškai.
   */
  santrauka?: string | null;
  data: string;
  laikas?: string | null;
  mokinys?: (number | null) | Mokiniai;
  /**
   * Įrašoma siuntimo metu — kad ištrynus grupę istorija liktų teisinga.
   */
  tipas?: ('individuali' | 'grupine') | null;
  /**
   * Tuščia, kai pamoka individuali.
   */
  grupe?: (number | null) | Grupe;
  /**
   * „Atidarė nuorodą“ užsideda pati. „Įvyko“ / „Neįvyko“ pažymima iš laiško arba čia.
   */
  busena?: ('suplanuota' | 'atidare' | 'ivyko' | 'neivyko') | null;
  issiusta?: string | null;
  atidaryta?: string | null;
  /**
   * Įrašoma siuntimo metu — kad kaina istorijoje nepasikeistų atgaline data.
   */
  pirmaPamoka?: boolean | null;
  /**
   * Užfiksuojama siuntimo metu iš „Sąskaitų nustatymų“. Tušti seni įrašai kainuoja tiek, kiek nustatymuose šiandien.
   */
  kaina?: number | null;
  /**
   * Užpildyta — pamoka jau apmokestinta. Būtent tai neleidžia jos įtraukti į dvi sąskaitas. Ištrynus sąskaitą, laukas išsivalo ir pamoka vėl laukia eilėje.
   */
  saskaita?: (number | null) | Saskaito;
  /**
   * Užpildyta tik tada, kai laiško išsiųsti nepavyko.
   */
  klaida?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sąskaitos tėvams. Juodraščius sudaro skydelis iš pamokų žurnalo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saskaitos".
 */
export interface Saskaito {
  id: number;
  /**
   * Sudaroma automatiškai.
   */
  santrauka?: string | null;
  /**
   * Suteikiamas išrašant. Juodraštis numerio dar neturi.
   */
  numeris?: string | null;
  busena?: ('juodrastis' | 'israsyta' | 'issiusta' | 'apmoketa' | 'anuliuota') | null;
  /**
   * YYYY-MM-DD, Vilniaus para.
   */
  data?: string | null;
  terminas?: string | null;
  /**
   * Mėnuo, už kurį išrašyta.
   */
  laikotarpisNuo?: string | null;
  laikotarpisIki?: string | null;
  /**
   * Vienas tėvas su keliais vaikais gauna vieną sąskaitą.
   */
  mokiniai?: (number | Mokiniai)[] | null;
  pirkejoVardas?: string | null;
  pirkejoPastas?: string | null;
  /**
   * Nebūtina. Tuščias — i.SAF eina „ND“ (nežinomas).
   */
  pirkejoKodas?: string | null;
  /**
   * Fiziniai asmenys jo neturi — palikite tuščią.
   */
  pirkejoPvmKodas?: string | null;
  pirkejoAdresas?: string | null;
  /**
   * Pakeitus kiekį ar kainą, sumos perskaičiuojamos išsaugant.
   */
  eilutes?:
    | {
        /**
         * Pvz. „Matematikos pamoka (individuali) — Jonas“.
         */
        aprasymas: string;
        /**
         * Kurių dienų pamokos į šią eilutę suėjo. Rodoma smulkiu tekstu.
         */
        detales?: string | null;
        kiekis: number;
        matoVnt?: string | null;
        /**
         * Tokia, kokia rodoma tėvams: su PVM arba be — pagal sąskaitos žymą „Kainos su PVM“.
         */
        kaina: number;
        /**
         * Iš „Sąskaitų nustatymų“, pvz. PVM1.
         */
        pvmKodas?: string | null;
        pvmProc?: number | null;
        /**
         * Kiekis × kaina. Perskaičiuojama išsaugant.
         */
        suma?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Nurašoma iš „Sąskaitų nustatymų“ išrašymo metu. Nuo jos priklauso, ar PVM iš sumos išskaičiuojamas, ar prie jos pridedamas — todėl vėliau nebekeičiama.
   */
  kainosSuPvm?: boolean | null;
  sumaBePvm?: number | null;
  pvmSuma?: number | null;
  sumaIsViso?: number | null;
  pastaba?: string | null;
  issiusta?: string | null;
  /**
   * Žymima ranka — banko sąskaitos sistema nemato.
   */
  apmoketa?: string | null;
  /**
   * Užpildyta tik tada, kai laiško išsiųsti nepavyko.
   */
  siuntimoKlaida?: string | null;
  isafBusena?: ('neteikta' | 'ikelta' | 'pateikta' | 'klaida') | null;
  isafAtnaujinta?: string | null;
  isafTrackingNumber?: string | null;
  isafRegistryNumber?: string | null;
  isafKlaida?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ką lankytojai užsisakė svetainės kalendoriuje.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rezervacijos".
 */
export interface Rezervacijo {
  id: number;
  /**
   * Sudaroma automatiškai.
   */
  santrauka?: string | null;
  /**
   * „Nauja“ ir „Patvirtinta“ laiką kalendoriuje laiko užimtą. „Atmesta“ jį vėl atlaisvina.
   */
  busena?: ('nauja' | 'patvirtinta' | 'atmesta') | null;
  data: string;
  laikas: string;
  tevoVardas: string;
  vaikoVardas: string;
  klase?: string | null;
  elPastas: string;
  telefonas?: string | null;
  saltinis?: string | null;
  pastabos?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'straipsniai';
        value: number | Straipsniai;
      } | null)
    | ({
        relationTo: 'failai';
        value: number | Failai;
      } | null)
    | ({
        relationTo: 'naudotojai';
        value: number | Naudotojai;
      } | null)
    | ({
        relationTo: 'mokiniai';
        value: number | Mokiniai;
      } | null)
    | ({
        relationTo: 'grupes';
        value: number | Grupe;
      } | null)
    | ({
        relationTo: 'zurnalas';
        value: number | Zurnala;
      } | null)
    | ({
        relationTo: 'saskaitos';
        value: number | Saskaito;
      } | null)
    | ({
        relationTo: 'rezervacijos';
        value: number | Rezervacijo;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'naudotojai';
    value: number | Naudotojai;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'naudotojai';
    value: number | Naudotojai;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "straipsniai_select".
 */
export interface StraipsniaiSelect<T extends boolean = true> {
  pavadinimas?: T;
  nuoroda?: T;
  santrauka?: T;
  virselis?: T;
  turinys?: T;
  busena?: T;
  paskelbta?: T;
  klases?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "failai_select".
 */
export interface FailaiSelect<T extends boolean = true> {
  alt?: T;
  kategorija?: T;
  klase?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        perzvalga?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        virselis?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "naudotojai_select".
 */
export interface NaudotojaiSelect<T extends boolean = true> {
  vardas?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mokiniai_select".
 */
export interface MokiniaiSelect<T extends boolean = true> {
  vardas?: T;
  klase?: T;
  tevoVardas?: T;
  tevoPastas?: T;
  meetNuoroda?: T;
  pamokos?:
    | T
    | {
        kartojimas?: T;
        laikas?: T;
        trukmeMin?: T;
        savaitesDiena?: T;
        kasKiek?: T;
        nuoDatos?: T;
        menesioDiena?: T;
        id?: T;
      };
  aktyvus?: T;
  pirmaPamoka?: T;
  pauzeIki?: T;
  sutikimas?: T;
  priminimoKada?: T;
  priminimoValanda?: T;
  pastabos?: T;
  raktas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grupes_select".
 */
export interface GrupesSelect<T extends boolean = true> {
  pavadinimas?: T;
  aktyvi?: T;
  nariai?: T;
  meetNuoroda?: T;
  pamokos?:
    | T
    | {
        kartojimas?: T;
        laikas?: T;
        trukmeMin?: T;
        savaitesDiena?: T;
        kasKiek?: T;
        nuoDatos?: T;
        menesioDiena?: T;
        id?: T;
      };
  pauzeIki?: T;
  pastabos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zurnalas_select".
 */
export interface ZurnalasSelect<T extends boolean = true> {
  santrauka?: T;
  data?: T;
  laikas?: T;
  mokinys?: T;
  tipas?: T;
  grupe?: T;
  busena?: T;
  issiusta?: T;
  atidaryta?: T;
  pirmaPamoka?: T;
  kaina?: T;
  saskaita?: T;
  klaida?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saskaitos_select".
 */
export interface SaskaitosSelect<T extends boolean = true> {
  santrauka?: T;
  numeris?: T;
  busena?: T;
  data?: T;
  terminas?: T;
  laikotarpisNuo?: T;
  laikotarpisIki?: T;
  mokiniai?: T;
  pirkejoVardas?: T;
  pirkejoPastas?: T;
  pirkejoKodas?: T;
  pirkejoPvmKodas?: T;
  pirkejoAdresas?: T;
  eilutes?:
    | T
    | {
        aprasymas?: T;
        detales?: T;
        kiekis?: T;
        matoVnt?: T;
        kaina?: T;
        pvmKodas?: T;
        pvmProc?: T;
        suma?: T;
        id?: T;
      };
  kainosSuPvm?: T;
  sumaBePvm?: T;
  pvmSuma?: T;
  sumaIsViso?: T;
  pastaba?: T;
  issiusta?: T;
  apmoketa?: T;
  siuntimoKlaida?: T;
  isafBusena?: T;
  isafAtnaujinta?: T;
  isafTrackingNumber?: T;
  isafRegistryNumber?: T;
  isafKlaida?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rezervacijos_select".
 */
export interface RezervacijosSelect<T extends boolean = true> {
  santrauka?: T;
  busena?: T;
  data?: T;
  laikas?: T;
  tevoVardas?: T;
  vaikoVardas?: T;
  klase?: T;
  elPastas?: T;
  telefonas?: T;
  saltinis?: T;
  pastabos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Rodoma po kiekvienu straipsniu: kainos, nuolaida ir registracijos forma.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nustatymai".
 */
export interface Nustatymai {
  id: number;
  /**
   * Išjungus, straipsnių apačioje nebeliks nei kainų, nei formos.
   */
  rodyti?: boolean | null;
  kainuAntraste?: string | null;
  /**
   * Nepalikus nė vienos eilutės, lentelė nerodoma visai.
   */
  kainos?:
    | {
        /**
         * Pvz. „Individuali pamoka nuotoliu“.
         */
        pavadinimas: string;
        /**
         * Pvz. „60 min.“
         */
        trukme?: string | null;
        /**
         * Rašoma taip, kaip turi atrodyti: „25 €“.
         */
        kaina: string;
        /**
         * Pvz. „nuo 4 pamokų per mėnesį“.
         */
        prierasas?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Rodomas oranžine juostele virš lentelės. Palikus tuščią — nerodomas.
   */
  nuolaida?: string | null;
  kainuPastaba?: string | null;
  formosAntraste?: string | null;
  formosTekstas?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Kada ir ar išvis siunčiami automatiniai priminimai tėvams.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priminimai".
 */
export interface Priminimai {
  id: number;
  /**
   * Nuėmus varnelę siuntimas sustoja visiems, nieko kito keisti nereikia.
   */
  ijungta?: boolean | null;
  kada: 'rytas' | 'vakaras';
  /**
   * Formatas 07:30, Lietuvos laiku.
   */
  valanda: string;
  /**
   * Įterpiamas kiekvieno laiško gale, prieš parašą. Pvz. priminimas apie namų darbus.
   */
  prierasas?: string | null;
  /**
   * Kelios eilutės po brūkšneliu. Palikus tuščią, naudojamas numatytasis — vardas, pareigos, telefonas ir vardiklis.lt. Laiškai paprasto teksto, tad paveikslėlių ar spalvų čia nebus.
   */
  parasas?: string | null;
  /**
   * Vienas laiškas su tos dienos pamokomis ir mygtukais „Buvo / Nebuvo“ — kad žurnalo nereikėtų pildyti panelėje.
   */
  santraukaSau?: boolean | null;
  /**
   * Kad ta pati santrauka neišeitų kelis kartus per dieną.
   */
  paskutineSantrauka?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Kalendorius po registracijos forma. Užimtumas imamas iš „Mokinių“.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tvarkarastis".
 */
export interface Tvarkarasti {
  id: number;
  rodyti?: boolean | null;
  antraste?: string | null;
  /**
   * Anksčiausia pamoka pirmadienį–penktadienį.
   */
  nuo: string;
  /**
   * Anksčiausia pamoka šeštadienį ir sekmadienį.
   */
  nuoSavaitgali: string;
  /**
   * Vėliausia pamokos pradžia. Ši eilutė lentelėje dar rodoma.
   */
  iki: string;
  zingsnis?: ('30' | '60') | null;
  dienos?: ('1' | '2' | '3' | '4' | '5' | '6' | '7')[] | null;
  /**
   * Tiek savaičių lankytojas galės pervartyti pirmyn. 26 — maždaug pusmetis, 52 — metai.
   */
  savaiciu?: number | null;
  /**
   * Išjungus, kalendorius lieka, bet tampa tik informacinis — laikai nebespaudžiami.
   */
  leistiRegistruotis?: boolean | null;
  /**
   * Arčiau nei prieš tiek valandų užsiregistruoti nebegalima — kad neatsirastų užsakymas pamokai po dvidešimties minučių.
   */
  ispejimasVal?: number | null;
  /**
   * Galioja PO to, kai užimtumas suskaičiuojamas iš mokinių sąrašo, tad gali ir uždaryti laisvą langą, ir atlaisvinti užstatytą.
   */
  pakeitimai?:
    | {
        tipas: 'savaite' | 'data';
        savaitesDiena?: ('1' | '2' | '3' | '4' | '5' | '6' | '7') | null;
        /**
         * Pvz. rugsėjo 18 — galioja tik tą vieną dieną.
         */
        data?: string | null;
        nuo: string;
        iki: string;
        busena: 'uzimta' | 'laisva';
        /**
         * Svetainėje nerodoma. Kad po mėnesio būtų aišku, kam tai buvo.
         */
        pastaba?: string | null;
        id?: string | null;
      }[]
    | null;
  pastabaLaikai?: string | null;
  pastabaGrupine?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Pardavėjo rekvizitai, kainos, PVM ir i.SAF teikimas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "atsiskaitymai".
 */
export interface Atsiskaitymai {
  id: number;
  /**
   * Pvz. „Modesta Pavardenė“.
   */
  pardavejoVardas?: string | null;
  /**
   * Asmens arba įmonės kodas. Šis skaičius keliauja į i.SAF rinkmenos „RegistrationNumber“ — be jo teikti negalima.
   */
  pardavejoKodas?: string | null;
  /**
   * Pvz. LT100001234567.
   */
  pardavejoPvmKodas?: string | null;
  /**
   * Nebūtina. Įrašyta — rodoma sąskaitoje.
   */
  veiklosPazyma?: string | null;
  pardavejoAdresas?: string | null;
  /**
   * Į ją tėvai perves pinigus. Be jos sąskaita neapmokama.
   */
  iban?: string | null;
  bankas?: string | null;
  /**
   * Sąskaitos numeris sudaromas kaip SERIJA-0001.
   */
  serija?: string | null;
  /**
   * Padidėja pats kaskart išrašius. Ranka keisti verta tik pradedant nuo tam tikro skaičiaus — numeriai turi eiti be spragų.
   */
  kitasNumeris?: number | null;
  terminoDienos?: number | null;
  individualiKaina?: number | null;
  grupineKaina?: number | null;
  /**
   * Atimama nuo pirmos pamokos kainos — ir individualios, ir grupinės.
   */
  pirmosNuolaida?: number | null;
  pvmKodas: 'PVM1' | 'PVM2' | 'PVM3' | 'PVM5';
  /**
   * Pasirinkus PVM5 — įrašykite 0.
   */
  pvmProc?: number | null;
  /**
   * Įjungta (įprastai taip): 25 € yra galutinė kaina tėvams, o PVM iš jos išskaičiuojamas — 20,66 € + 4,34 €. Išjungus, prie 25 € PVM būtų pridėtas ir tėvai mokėtų 30,25 €.
   */
  kainosSuPvm?: boolean | null;
  /**
   * Prie temos automatiškai prirašomas sąskaitos numeris.
   */
  laiskoTema?: string | null;
  laiskoTekstas?: string | null;
  /**
   * Palikus tuščią — toks pat, kaip priminimų laiškuose.
   */
  saskaituParasas?: string | null;
  /**
   * Įjunkite tik gavę i.MAS kliento sertifikatą ir įrašę jo kelią į aplinkos kintamuosius.
   */
  isafIjungta?: boolean | null;
  /**
   * Keliauja į rinkmenos lauką „SoftwareName“.
   */
  programosPavadinimas?: string | null;
  programosVersija?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nustatymai_select".
 */
export interface NustatymaiSelect<T extends boolean = true> {
  rodyti?: T;
  kainuAntraste?: T;
  kainos?:
    | T
    | {
        pavadinimas?: T;
        trukme?: T;
        kaina?: T;
        prierasas?: T;
        id?: T;
      };
  nuolaida?: T;
  kainuPastaba?: T;
  formosAntraste?: T;
  formosTekstas?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priminimai_select".
 */
export interface PriminimaiSelect<T extends boolean = true> {
  ijungta?: T;
  kada?: T;
  valanda?: T;
  prierasas?: T;
  parasas?: T;
  santraukaSau?: T;
  paskutineSantrauka?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tvarkarastis_select".
 */
export interface TvarkarastisSelect<T extends boolean = true> {
  rodyti?: T;
  antraste?: T;
  nuo?: T;
  nuoSavaitgali?: T;
  iki?: T;
  zingsnis?: T;
  dienos?: T;
  savaiciu?: T;
  leistiRegistruotis?: T;
  ispejimasVal?: T;
  pakeitimai?:
    | T
    | {
        tipas?: T;
        savaitesDiena?: T;
        data?: T;
        nuo?: T;
        iki?: T;
        busena?: T;
        pastaba?: T;
        id?: T;
      };
  pastabaLaikai?: T;
  pastabaGrupine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "atsiskaitymai_select".
 */
export interface AtsiskaitymaiSelect<T extends boolean = true> {
  pardavejoVardas?: T;
  pardavejoKodas?: T;
  pardavejoPvmKodas?: T;
  veiklosPazyma?: T;
  pardavejoAdresas?: T;
  iban?: T;
  bankas?: T;
  serija?: T;
  kitasNumeris?: T;
  terminoDienos?: T;
  individualiKaina?: T;
  grupineKaina?: T;
  pirmosNuolaida?: T;
  pvmKodas?: T;
  pvmProc?: T;
  kainosSuPvm?: T;
  laiskoTema?: T;
  laiskoTekstas?: T;
  saskaituParasas?: T;
  isafIjungta?: T;
  programosPavadinimas?: T;
  programosVersija?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}