/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    naudotojai: NaudotojaiAuthOperations;
  };
  blocks: {};
  collections: {
    straipsniai: Straipsniai;
    failai: Failai;
    naudotojai: Naudotojai;
    mokiniai: Mokiniai;
    zurnalas: Zurnala;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    straipsniai: StraipsniaiSelect<false> | StraipsniaiSelect<true>;
    failai: FailaiSelect<false> | FailaiSelect<true>;
    naudotojai: NaudotojaiSelect<false> | NaudotojaiSelect<true>;
    mokiniai: MokiniaiSelect<false> | MokiniaiSelect<true>;
    zurnalas: ZurnalasSelect<false> | ZurnalasSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'lt' | 'lt'[];
  globals: {
    nustatymai: Nustatymai;
    priminimai: Priminimai;
  };
  globalsSelect: {
    nustatymai: NustatymaiSelect<false> | NustatymaiSelect<true>;
    priminimai: PriminimaiSelect<false> | PriminimaiSelect<true>;
  };
  locale: 'lt';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Naudotojai;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface NaudotojaiAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tinklaraščio įrašai. Juodraščiai svetainėje nerodomi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "straipsniai".
 */
export interface Straipsniai {
  id: number;
  pavadinimas: string;
  /**
   * Pvz. „kaip-mokytis-daugybos“. Paskelbus nebekeisti.
   */
  nuoroda: string;
  /**
   * Rodoma sąraše ir paieškos rezultatuose. Iki 200 ženklų.
   */
  santrauka: string;
  virselis?: (number | null) | Failai;
  turinys: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  busena: 'juodrastis' | 'paskelbta';
  paskelbta?: string | null;
  klases?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10')[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Failai;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "failai".
 */
export interface Failai {
  id: number;
  /**
   * Ką matyti paveikslėlyje. Būtina dėl prieinamumo ir SEO.
   */
  alt: string;
  kategorija?: ('straipsnis' | 'nmpp' | 'pupp' | 'kita') | null;
  /**
   * Kuriai klasei skirta užduotis.
   */
  klase?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    perzvalga?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    virselis?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "naudotojai".
 */
export interface Naudotojai {
  id: number;
  vardas: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'naudotojai';
}
/**
 * Kam siunčiami priminimai. Pamokos kartojasi kas savaitę; pakeitimai galioja nuo kito siuntimo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mokiniai".
 */
export interface Mokiniai {
  id: number;
  vardas: string;
  klase?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
  tevoVardas?: string | null;
  /**
   * Šiuo adresu eina priminimai. Be jo siųsti nėra kur.
   */
  tevoPastas: string;
  /**
   * Nuolatinė šio vaiko kambario nuoroda, pvz. https://meet.google.com/abc-defg-hij. Tėvams siunčiama ne ji, o vardiklis.lt nuoroda, kuri atveda čia — todėl pakeitus ją, tėvams pranešti nereikia.
   */
  meetNuoroda: string;
  /**
   * Kartojasi kas savaitę. Nepalikus nė vienos eilutės, priminimų šiam mokiniui nebus.
   */
  pamokos?:
    | {
        savaitesDiena: '1' | '2' | '3' | '4' | '5' | '6' | '7';
        /**
         * Formatas 17:00, Lietuvos laiku.
         */
        laikas: string;
        trukmeMin?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Nuėmus varnelę priminimai nustoja eiti, o įrašas lieka.
   */
  aktyvus?: boolean | null;
  /**
   * Įjungta — laiške paminima pirmos pamokos nuolaida. Pažymėjus žurnale „Įvyko“, varnelė nusiima pati.
   */
  pirmaPamoka?: boolean | null;
  /**
   * Atostogoms. Iki šios dienos imtinai priminimai nesiunčiami.
   */
  pauzeIki?: string | null;
  sutikimas?: boolean | null;
  priminimoKada?: ('' | 'rytas' | 'vakaras') | null;
  /**
   * Pvz. 07:30. Palikus tuščią — kaip bendruose nustatymuose.
   */
  priminimoValanda?: string | null;
  pastabos?: string | null;
  /**
   * Iš jo sudaroma nuoroda vardiklis.lt/p/… Nekeičiamas.
   */
  raktas?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ką sistema išsiuntė ir kas iš to išėjo. Įrašus kuria pati sistema.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zurnalas".
 */
export interface Zurnala {
  id: number;
  /**
   * Sudaroma automatiškai.
   */
  santrauka?: string | null;
  data: string;
  laikas?: string | null;
  mokinys?: (number | null) | Mokiniai;
  /**
   * „Atidarė nuorodą“ užsideda pati. „Įvyko“ / „Neįvyko“ pažymima iš laiško arba čia.
   */
  busena?: ('suplanuota' | 'atidare' | 'ivyko' | 'neivyko') | null;
  issiusta?: string | null;
  atidaryta?: string | null;
  /**
   * Įrašoma siuntimo metu — kad kaina istorijoje nepasikeistų atgaline data.
   */
  pirmaPamoka?: boolean | null;
  /**
   * Užpildyta tik tada, kai laiško išsiųsti nepavyko.
   */
  klaida?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'straipsniai';
        value: number | Straipsniai;
      } | null)
    | ({
        relationTo: 'failai';
        value: number | Failai;
      } | null)
    | ({
        relationTo: 'naudotojai';
        value: number | Naudotojai;
      } | null)
    | ({
        relationTo: 'mokiniai';
        value: number | Mokiniai;
      } | null)
    | ({
        relationTo: 'zurnalas';
        value: number | Zurnala;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'naudotojai';
    value: number | Naudotojai;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'naudotojai';
    value: number | Naudotojai;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "straipsniai_select".
 */
export interface StraipsniaiSelect<T extends boolean = true> {
  pavadinimas?: T;
  nuoroda?: T;
  santrauka?: T;
  virselis?: T;
  turinys?: T;
  busena?: T;
  paskelbta?: T;
  klases?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "failai_select".
 */
export interface FailaiSelect<T extends boolean = true> {
  alt?: T;
  kategorija?: T;
  klase?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        perzvalga?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        virselis?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "naudotojai_select".
 */
export interface NaudotojaiSelect<T extends boolean = true> {
  vardas?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mokiniai_select".
 */
export interface MokiniaiSelect<T extends boolean = true> {
  vardas?: T;
  klase?: T;
  tevoVardas?: T;
  tevoPastas?: T;
  meetNuoroda?: T;
  pamokos?:
    | T
    | {
        savaitesDiena?: T;
        laikas?: T;
        trukmeMin?: T;
        id?: T;
      };
  aktyvus?: T;
  pirmaPamoka?: T;
  pauzeIki?: T;
  sutikimas?: T;
  priminimoKada?: T;
  priminimoValanda?: T;
  pastabos?: T;
  raktas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zurnalas_select".
 */
export interface ZurnalasSelect<T extends boolean = true> {
  santrauka?: T;
  data?: T;
  laikas?: T;
  mokinys?: T;
  busena?: T;
  issiusta?: T;
  atidaryta?: T;
  pirmaPamoka?: T;
  klaida?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Rodoma po kiekvienu straipsniu: kainos, nuolaida ir registracijos forma.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nustatymai".
 */
export interface Nustatymai {
  id: number;
  /**
   * Išjungus, straipsnių apačioje nebeliks nei kainų, nei formos.
   */
  rodyti?: boolean | null;
  kainuAntraste?: string | null;
  /**
   * Nepalikus nė vienos eilutės, lentelė nerodoma visai.
   */
  kainos?:
    | {
        /**
         * Pvz. „Individuali pamoka nuotoliu“.
         */
        pavadinimas: string;
        /**
         * Pvz. „60 min.“
         */
        trukme?: string | null;
        /**
         * Rašoma taip, kaip turi atrodyti: „25 €“.
         */
        kaina: string;
        /**
         * Pvz. „nuo 4 pamokų per mėnesį“.
         */
        prierasas?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Rodomas oranžine juostele virš lentelės. Palikus tuščią — nerodomas.
   */
  nuolaida?: string | null;
  kainuPastaba?: string | null;
  formosAntraste?: string | null;
  formosTekstas?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Kada ir ar išvis siunčiami automatiniai priminimai tėvams.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priminimai".
 */
export interface Priminimai {
  id: number;
  /**
   * Nuėmus varnelę siuntimas sustoja visiems, nieko kito keisti nereikia.
   */
  ijungta?: boolean | null;
  kada: 'rytas' | 'vakaras';
  /**
   * Formatas 07:30, Lietuvos laiku.
   */
  valanda: string;
  /**
   * Įterpiamas kiekvieno laiško gale, prieš parašą. Pvz. priminimas apie namų darbus.
   */
  prierasas?: string | null;
  /**
   * Kelios eilutės po brūkšneliu. Palikus tuščią, naudojamas numatytasis — vardas, pareigos, telefonas ir vardiklis.lt. Laiškai paprasto teksto, tad paveikslėlių ar spalvų čia nebus.
   */
  parasas?: string | null;
  /**
   * Vienas laiškas su tos dienos pamokomis ir mygtukais „Buvo / Nebuvo“ — kad žurnalo nereikėtų pildyti panelėje.
   */
  santraukaSau?: boolean | null;
  /**
   * Kad ta pati santrauka neišeitų kelis kartus per dieną.
   */
  paskutineSantrauka?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nustatymai_select".
 */
export interface NustatymaiSelect<T extends boolean = true> {
  rodyti?: T;
  kainuAntraste?: T;
  kainos?:
    | T
    | {
        pavadinimas?: T;
        trukme?: T;
        kaina?: T;
        prierasas?: T;
        id?: T;
      };
  nuolaida?: T;
  kainuPastaba?: T;
  formosAntraste?: T;
  formosTekstas?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priminimai_select".
 */
export interface PriminimaiSelect<T extends boolean = true> {
  ijungta?: T;
  kada?: T;
  valanda?: T;
  prierasas?: T;
  parasas?: T;
  santraukaSau?: T;
  paskutineSantrauka?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}