/**
 * SUGENERUOTA AUTOMATIŠKAI — ranka neredaguoti.
 * Perkurti:  npm run schema
 *
 * Pradinė duomenų bazės schema. Serveryje paleidžiama kaip `prodMigrations`,
 * nes produkcijos režimu Payload lentelių pats nekuria.
 */

export const PRADINE_SCHEMA: string[] = [
  "CREATE TABLE IF NOT EXISTS `_straipsniai_v` ( `id` integer PRIMARY KEY NOT NULL, `parent_id` integer, `version_pavadinimas` text, `version_nuoroda` text, `version_santrauka` text, `version_virselis_id` integer, `version_turinys` text, `version_busena` text DEFAULT 'juodrastis', `version_paskelbta` text, `version_updated_at` text, `version_created_at` text, `version__status` text DEFAULT 'draft', `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `snapshot` integer, `published_locale` text, `latest` integer, FOREIGN KEY (`parent_id`) REFERENCES `straipsniai`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`version_virselis_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE set null )",
  "CREATE TABLE IF NOT EXISTS `_straipsniai_v_locales` ( `version_meta_title` text, `version_meta_description` text, `version_meta_image_id` integer, `id` integer PRIMARY KEY NOT NULL, `_locale` text NOT NULL, `_parent_id` integer NOT NULL, FOREIGN KEY (`version_meta_image_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `_straipsniai_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `_straipsniai_v_version_klases` ( `order` integer NOT NULL, `parent_id` integer NOT NULL, `value` text, `id` integer PRIMARY KEY NOT NULL, FOREIGN KEY (`parent_id`) REFERENCES `_straipsniai_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `failai` ( `id` integer PRIMARY KEY NOT NULL, `alt` text NOT NULL, `kategorija` text DEFAULT 'kita', `klase` numeric, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `url` text, `thumbnail_u_r_l` text, `filename` text, `mime_type` text, `filesize` numeric, `width` numeric, `height` numeric, `focal_x` numeric, `focal_y` numeric, `sizes_perzvalga_url` text, `sizes_perzvalga_width` numeric, `sizes_perzvalga_height` numeric, `sizes_perzvalga_mime_type` text, `sizes_perzvalga_filesize` numeric, `sizes_perzvalga_filename` text, `sizes_virselis_url` text, `sizes_virselis_width` numeric, `sizes_virselis_height` numeric, `sizes_virselis_mime_type` text, `sizes_virselis_filesize` numeric, `sizes_virselis_filename` text )",
  "CREATE TABLE IF NOT EXISTS `naudotojai` ( `id` integer PRIMARY KEY NOT NULL, `vardas` text NOT NULL, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `email` text NOT NULL, `reset_password_token` text, `reset_password_expiration` text, `salt` text, `hash` text, `login_attempts` numeric DEFAULT 0, `lock_until` text )",
  "CREATE TABLE IF NOT EXISTS `naudotojai_sessions` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `created_at` text, `expires_at` text NOT NULL, FOREIGN KEY (`_parent_id`) REFERENCES `naudotojai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `payload_kv` ( `id` integer PRIMARY KEY NOT NULL, `key` text NOT NULL, `data` text NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `payload_locked_documents` ( `id` integer PRIMARY KEY NOT NULL, `global_slug` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `payload_locked_documents_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `straipsniai_id` integer, `failai_id` integer, `naudotojai_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `payload_locked_documents`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`straipsniai_id`) REFERENCES `straipsniai`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`failai_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`naudotojai_id`) REFERENCES `naudotojai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `payload_migrations` ( `id` integer PRIMARY KEY NOT NULL, `name` text, `batch` numeric, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `payload_preferences` ( `id` integer PRIMARY KEY NOT NULL, `key` text, `value` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `payload_preferences_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `naudotojai_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `payload_preferences`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`naudotojai_id`) REFERENCES `naudotojai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `straipsniai` ( `id` integer PRIMARY KEY NOT NULL, `pavadinimas` text, `nuoroda` text, `santrauka` text, `virselis_id` integer, `turinys` text, `busena` text DEFAULT 'juodrastis', `paskelbta` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `_status` text DEFAULT 'draft', FOREIGN KEY (`virselis_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE set null )",
  "CREATE TABLE IF NOT EXISTS `straipsniai_klases` ( `order` integer NOT NULL, `parent_id` integer NOT NULL, `value` text, `id` integer PRIMARY KEY NOT NULL, FOREIGN KEY (`parent_id`) REFERENCES `straipsniai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `straipsniai_locales` ( `meta_title` text, `meta_description` text, `meta_image_id` integer, `id` integer PRIMARY KEY NOT NULL, `_locale` text NOT NULL, `_parent_id` integer NOT NULL, FOREIGN KEY (`meta_image_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `straipsniai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_created_at_idx` ON `_straipsniai_v` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_latest_idx` ON `_straipsniai_v` (`latest`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `_straipsniai_v_locales_locale_parent_id_unique` ON `_straipsniai_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_parent_idx` ON `_straipsniai_v` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_published_locale_idx` ON `_straipsniai_v` (`published_locale`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_snapshot_idx` ON `_straipsniai_v` (`snapshot`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_updated_at_idx` ON `_straipsniai_v` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_klases_order_idx` ON `_straipsniai_v_version_klases` (`order`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_klases_parent_idx` ON `_straipsniai_v_version_klases` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_meta_version_meta_image_idx` ON `_straipsniai_v_locales` (`version_meta_image_id`,`_locale`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version__status_idx` ON `_straipsniai_v` (`version__status`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version_created_at_idx` ON `_straipsniai_v` (`version_created_at`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version_nuoroda_idx` ON `_straipsniai_v` (`version_nuoroda`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version_updated_at_idx` ON `_straipsniai_v` (`version_updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version_virselis_idx` ON `_straipsniai_v` (`version_virselis_id`)",
  "CREATE INDEX IF NOT EXISTS `failai_created_at_idx` ON `failai` (`created_at`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `failai_filename_idx` ON `failai` (`filename`)",
  "CREATE INDEX IF NOT EXISTS `failai_sizes_perzvalga_sizes_perzvalga_filename_idx` ON `failai` (`sizes_perzvalga_filename`)",
  "CREATE INDEX IF NOT EXISTS `failai_sizes_virselis_sizes_virselis_filename_idx` ON `failai` (`sizes_virselis_filename`)",
  "CREATE INDEX IF NOT EXISTS `failai_updated_at_idx` ON `failai` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `naudotojai_created_at_idx` ON `naudotojai` (`created_at`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `naudotojai_email_idx` ON `naudotojai` (`email`)",
  "CREATE INDEX IF NOT EXISTS `naudotojai_sessions_order_idx` ON `naudotojai_sessions` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `naudotojai_sessions_parent_id_idx` ON `naudotojai_sessions` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `naudotojai_updated_at_idx` ON `naudotojai` (`updated_at`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `payload_kv_key_idx` ON `payload_kv` (`key`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_created_at_idx` ON `payload_locked_documents` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_global_slug_idx` ON `payload_locked_documents` (`global_slug`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_failai_id_idx` ON `payload_locked_documents_rels` (`failai_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_naudotojai_id_idx` ON `payload_locked_documents_rels` (`naudotojai_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_order_idx` ON `payload_locked_documents_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_parent_idx` ON `payload_locked_documents_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_path_idx` ON `payload_locked_documents_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_straipsniai_id_idx` ON `payload_locked_documents_rels` (`straipsniai_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_updated_at_idx` ON `payload_locked_documents` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_migrations_created_at_idx` ON `payload_migrations` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_migrations_updated_at_idx` ON `payload_migrations` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_created_at_idx` ON `payload_preferences` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_key_idx` ON `payload_preferences` (`key`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_naudotojai_id_idx` ON `payload_preferences_rels` (`naudotojai_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_order_idx` ON `payload_preferences_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_parent_idx` ON `payload_preferences_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_path_idx` ON `payload_preferences_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_updated_at_idx` ON `payload_preferences` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai__status_idx` ON `straipsniai` (`_status`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_created_at_idx` ON `straipsniai` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_klases_order_idx` ON `straipsniai_klases` (`order`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_klases_parent_idx` ON `straipsniai_klases` (`parent_id`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `straipsniai_locales_locale_parent_id_unique` ON `straipsniai_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_meta_meta_image_idx` ON `straipsniai_locales` (`meta_image_id`,`_locale`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `straipsniai_nuoroda_idx` ON `straipsniai` (`nuoroda`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_updated_at_idx` ON `straipsniai` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_virselis_idx` ON `straipsniai` (`virselis_id`)",
]
