/**
 * SUGENERUOTA AUTOMATIŠKAI — ranka neredaguoti.
 * Perkurti:  npm run schema
 *
 * Pradinė duomenų bazės schema. Serveryje paleidžiama kaip `prodMigrations`,
 * nes produkcijos režimu Payload lentelių pats nekuria.
 */

export const PRADINE_SCHEMA: string[] = [
  "CREATE TABLE IF NOT EXISTS `_straipsniai_v` ( `id` integer PRIMARY KEY NOT NULL, `parent_id` integer, `version_pavadinimas` text, `version_nuoroda` text, `version_santrauka` text, `version_virselis_id` integer, `version_turinys` text, `version_busena` text DEFAULT 'juodrastis', `version_paskelbta` text, `version_updated_at` text, `version_created_at` text, `version__status` text DEFAULT 'draft', `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `snapshot` integer, `published_locale` text, `latest` integer, `autosave` integer, FOREIGN KEY (`parent_id`) REFERENCES `straipsniai`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`version_virselis_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE set null )",
  "CREATE TABLE IF NOT EXISTS `_straipsniai_v_locales` ( `version_meta_title` text, `version_meta_description` text, `version_meta_image_id` integer, `id` integer PRIMARY KEY NOT NULL, `_locale` text NOT NULL, `_parent_id` integer NOT NULL, FOREIGN KEY (`version_meta_image_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `_straipsniai_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `_straipsniai_v_version_klases` ( `order` integer NOT NULL, `parent_id` integer NOT NULL, `value` text, `id` integer PRIMARY KEY NOT NULL, FOREIGN KEY (`parent_id`) REFERENCES `_straipsniai_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `atsiskaitymai` ( `id` integer PRIMARY KEY NOT NULL, `pardavejo_vardas` text, `pardavejo_kodas` text, `pardavejo_pvm_kodas` text, `veiklos_pazyma` text, `pardavejo_adresas` text, `iban` text, `bankas` text, `serija` text DEFAULT 'MOD', `kitas_numeris` numeric DEFAULT 1, `termino_dienos` numeric DEFAULT 14, `individuali_kaina` numeric DEFAULT 25, `grupine_kaina` numeric DEFAULT 20, `pirmos_nuolaida` numeric DEFAULT 5, `pvm_kodas` text DEFAULT 'PVM1' NOT NULL, `pvm_proc` numeric DEFAULT 21, `kainos_su_pvm` integer DEFAULT true, `laisko_tema` text DEFAULT 'Sąskaita už matematikos pamokas', `laisko_tekstas` text DEFAULT 'Siunčiu sąskaitą už praėjusio mėnesio pamokas. Sąskaita prisegta PDF formatu.', `saskaitu_parasas` text, `isaf_ijungta` integer DEFAULT false, `programos_pavadinimas` text DEFAULT 'Vardiklis', `programos_versija` text DEFAULT '1.0', `updated_at` text, `created_at` text )",
  "CREATE TABLE IF NOT EXISTS `failai` ( `id` integer PRIMARY KEY NOT NULL, `alt` text NOT NULL, `kategorija` text DEFAULT 'kita', `klase` numeric, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `url` text, `thumbnail_u_r_l` text, `filename` text, `mime_type` text, `filesize` numeric, `width` numeric, `height` numeric, `focal_x` numeric, `focal_y` numeric, `sizes_perzvalga_url` text, `sizes_perzvalga_width` numeric, `sizes_perzvalga_height` numeric, `sizes_perzvalga_mime_type` text, `sizes_perzvalga_filesize` numeric, `sizes_perzvalga_filename` text, `sizes_virselis_url` text, `sizes_virselis_width` numeric, `sizes_virselis_height` numeric, `sizes_virselis_mime_type` text, `sizes_virselis_filesize` numeric, `sizes_virselis_filename` text )",
  "CREATE TABLE IF NOT EXISTS `grupes` ( `id` integer PRIMARY KEY NOT NULL, `pavadinimas` text NOT NULL, `aktyvi` integer DEFAULT true, `meet_nuoroda` text NOT NULL, `pauze_iki` text, `pastabos` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `grupes_pamokos` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `kartojimas` text DEFAULT 'savaite' NOT NULL, `laikas` text NOT NULL, `trukme_min` numeric DEFAULT 60, `savaites_diena` text, `kas_kiek` text DEFAULT '1', `nuo_datos` text, `menesio_diena` numeric, FOREIGN KEY (`_parent_id`) REFERENCES `grupes`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `grupes_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `mokiniai_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `grupes`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`mokiniai_id`) REFERENCES `mokiniai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `mokiniai` ( `id` integer PRIMARY KEY NOT NULL, `vardas` text NOT NULL, `klase` text, `tevo_vardas` text, `tevo_pastas` text NOT NULL, `meet_nuoroda` text NOT NULL, `aktyvus` integer DEFAULT true, `pirma_pamoka` integer DEFAULT true, `pauze_iki` text, `sutikimas` integer DEFAULT true, `priminimo_kada` text DEFAULT '', `priminimo_valanda` text, `pastabos` text, `raktas` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `mokiniai_pamokos` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `kartojimas` text DEFAULT 'savaite' NOT NULL, `laikas` text NOT NULL, `trukme_min` numeric DEFAULT 60, `savaites_diena` text, `kas_kiek` text DEFAULT '1', `nuo_datos` text, `menesio_diena` numeric, FOREIGN KEY (`_parent_id`) REFERENCES `mokiniai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `naudotojai` ( `id` integer PRIMARY KEY NOT NULL, `vardas` text NOT NULL, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `email` text NOT NULL, `reset_password_token` text, `reset_password_expiration` text, `salt` text, `hash` text, `login_attempts` numeric DEFAULT 0, `lock_until` text )",
  "CREATE TABLE IF NOT EXISTS `naudotojai_sessions` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `created_at` text, `expires_at` text NOT NULL, FOREIGN KEY (`_parent_id`) REFERENCES `naudotojai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `nustatymai` ( `id` integer PRIMARY KEY NOT NULL, `rodyti` integer DEFAULT true, `kainu_antraste` text DEFAULT 'Individualios pamokos', `nuolaida` text DEFAULT 'Pirmai pamokai — nuolaida', `kainu_pastaba` text, `formos_antraste` text DEFAULT 'Registracija į pamoką', `formos_tekstas` text DEFAULT 'Parašykite, kelintoje klasėje vaikas ir kas nesiseka — susisieksiu dėl laiko.', `updated_at` text, `created_at` text )",
  "CREATE TABLE IF NOT EXISTS `nustatymai_kainos` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `pavadinimas` text NOT NULL, `trukme` text, `kaina` text NOT NULL, `prierasas` text, FOREIGN KEY (`_parent_id`) REFERENCES `nustatymai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `payload_kv` ( `id` integer PRIMARY KEY NOT NULL, `key` text NOT NULL, `data` text NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `payload_locked_documents` ( `id` integer PRIMARY KEY NOT NULL, `global_slug` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS \"payload_locked_documents_rels\" ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `straipsniai_id` integer, `failai_id` integer, `naudotojai_id` integer, `mokiniai_id` integer, `grupes_id` integer, `zurnalas_id` integer, `saskaitos_id` integer, `rezervacijos_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `payload_locked_documents`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`straipsniai_id`) REFERENCES `straipsniai`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`failai_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`naudotojai_id`) REFERENCES `naudotojai`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`mokiniai_id`) REFERENCES `mokiniai`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`grupes_id`) REFERENCES `grupes`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`zurnalas_id`) REFERENCES `zurnalas`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`saskaitos_id`) REFERENCES `saskaitos`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`rezervacijos_id`) REFERENCES `rezervacijos`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `payload_migrations` ( `id` integer PRIMARY KEY NOT NULL, `name` text, `batch` numeric, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `payload_preferences` ( `id` integer PRIMARY KEY NOT NULL, `key` text, `value` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `payload_preferences_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `naudotojai_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `payload_preferences`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`naudotojai_id`) REFERENCES `naudotojai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `priminimai` ( `id` integer PRIMARY KEY NOT NULL, `ijungta` integer DEFAULT true, `kada` text DEFAULT 'rytas' NOT NULL, `valanda` text DEFAULT '07:30' NOT NULL, `prierasas` text, `santrauka_sau` integer DEFAULT true, `paskutine_santrauka` text, `updated_at` text, `created_at` text , `parasas` text)",
  "CREATE TABLE IF NOT EXISTS `rezervacijos` ( `id` integer PRIMARY KEY NOT NULL, `santrauka` text, `busena` text DEFAULT 'nauja', `data` text NOT NULL, `laikas` text NOT NULL, `tevo_vardas` text NOT NULL, `vaiko_vardas` text NOT NULL, `klase` text, `el_pastas` text NOT NULL, `telefonas` text, `saltinis` text, `pastabos` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `saskaitos` ( `id` integer PRIMARY KEY NOT NULL, `santrauka` text, `numeris` text, `busena` text DEFAULT 'juodrastis', `data` text, `terminas` text, `laikotarpis_nuo` text, `laikotarpis_iki` text, `pirkejo_vardas` text, `pirkejo_pastas` text, `pirkejo_kodas` text, `pirkejo_pvm_kodas` text, `pirkejo_adresas` text, `kainos_su_pvm` integer DEFAULT true, `suma_be_pvm` numeric, `pvm_suma` numeric, `suma_is_viso` numeric, `pastaba` text, `issiusta` text, `apmoketa` text, `siuntimo_klaida` text, `isaf_busena` text DEFAULT 'neteikta', `isaf_atnaujinta` text, `isaf_tracking_number` text, `isaf_registry_number` text, `isaf_klaida` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )",
  "CREATE TABLE IF NOT EXISTS `saskaitos_eilutes` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `aprasymas` text NOT NULL, `detales` text, `kiekis` numeric DEFAULT 1 NOT NULL, `mato_vnt` text DEFAULT 'vnt.', `kaina` numeric NOT NULL, `pvm_kodas` text, `pvm_proc` numeric DEFAULT 21, `suma` numeric, FOREIGN KEY (`_parent_id`) REFERENCES `saskaitos`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `saskaitos_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `mokiniai_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `saskaitos`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`mokiniai_id`) REFERENCES `mokiniai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `straipsniai` ( `id` integer PRIMARY KEY NOT NULL, `pavadinimas` text, `nuoroda` text, `santrauka` text, `virselis_id` integer, `turinys` text, `busena` text DEFAULT 'juodrastis', `paskelbta` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `_status` text DEFAULT 'draft', FOREIGN KEY (`virselis_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE set null )",
  "CREATE TABLE IF NOT EXISTS `straipsniai_klases` ( `order` integer NOT NULL, `parent_id` integer NOT NULL, `value` text, `id` integer PRIMARY KEY NOT NULL, FOREIGN KEY (`parent_id`) REFERENCES `straipsniai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `straipsniai_locales` ( `meta_title` text, `meta_description` text, `meta_image_id` integer, `id` integer PRIMARY KEY NOT NULL, `_locale` text NOT NULL, `_parent_id` integer NOT NULL, FOREIGN KEY (`meta_image_id`) REFERENCES `failai`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `straipsniai`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `tvarkarastis` ( `id` integer PRIMARY KEY NOT NULL, `rodyti` integer DEFAULT true, `antraste` text DEFAULT 'Laisvi laikai', `nuo` text DEFAULT '13:00' NOT NULL, `nuo_savaitgali` text DEFAULT '10:00' NOT NULL, `iki` text DEFAULT '21:00' NOT NULL, `zingsnis` text DEFAULT '60', `savaiciu` numeric DEFAULT 26, `leisti_registruotis` integer DEFAULT true, `ispejimas_val` numeric DEFAULT 12, `pastaba_laikai` text DEFAULT 'Laikai gali kisti, todėl visuomet rekomenduoju kreiptis.', `pastaba_grupine` text DEFAULT 'Nors laikas gali būti pažymėtas kaip užimtas, gali būti, kad tuo metu vyksta grupinė pamoka ir joje dar yra laisvų vietų — pasiteiraukite.', `updated_at` text, `created_at` text )",
  "CREATE TABLE IF NOT EXISTS `tvarkarastis_dienos` ( `order` integer NOT NULL, `parent_id` integer NOT NULL, `value` text, `id` integer PRIMARY KEY NOT NULL, FOREIGN KEY (`parent_id`) REFERENCES `tvarkarastis`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS `tvarkarastis_pakeitimai` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `tipas` text DEFAULT 'savaite' NOT NULL, `savaites_diena` text, `data` text, `nuo` text NOT NULL, `iki` text NOT NULL, `busena` text DEFAULT 'uzimta' NOT NULL, `pastaba` text, FOREIGN KEY (`_parent_id`) REFERENCES `tvarkarastis`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE TABLE IF NOT EXISTS \"zurnalas\" ( `id` integer PRIMARY KEY NOT NULL, `santrauka` text, `data` text NOT NULL, `laikas` text, `mokinys_id` integer, `tipas` text DEFAULT 'individuali', `grupe_id` integer, `busena` text DEFAULT 'suplanuota', `issiusta` text, `atidaryta` text, `pirma_pamoka` integer, `kaina` numeric, `saskaita_id` integer, `klaida` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, FOREIGN KEY (`mokinys_id`) REFERENCES `mokiniai`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`grupe_id`) REFERENCES `grupes`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`saskaita_id`) REFERENCES `saskaitos`(`id`) ON UPDATE no action ON DELETE set null )",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_autosave_idx` ON `_straipsniai_v` (`autosave`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_created_at_idx` ON `_straipsniai_v` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_latest_idx` ON `_straipsniai_v` (`latest`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `_straipsniai_v_locales_locale_parent_id_unique` ON `_straipsniai_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_parent_idx` ON `_straipsniai_v` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_published_locale_idx` ON `_straipsniai_v` (`published_locale`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_snapshot_idx` ON `_straipsniai_v` (`snapshot`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_updated_at_idx` ON `_straipsniai_v` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_klases_order_idx` ON `_straipsniai_v_version_klases` (`order`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_klases_parent_idx` ON `_straipsniai_v_version_klases` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_meta_version_meta_image_idx` ON `_straipsniai_v_locales` (`version_meta_image_id`,`_locale`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version__status_idx` ON `_straipsniai_v` (`version__status`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version_created_at_idx` ON `_straipsniai_v` (`version_created_at`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version_nuoroda_idx` ON `_straipsniai_v` (`version_nuoroda`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version_updated_at_idx` ON `_straipsniai_v` (`version_updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_straipsniai_v_version_version_virselis_idx` ON `_straipsniai_v` (`version_virselis_id`)",
  "CREATE INDEX IF NOT EXISTS `failai_created_at_idx` ON `failai` (`created_at`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `failai_filename_idx` ON `failai` (`filename`)",
  "CREATE INDEX IF NOT EXISTS `failai_sizes_perzvalga_sizes_perzvalga_filename_idx` ON `failai` (`sizes_perzvalga_filename`)",
  "CREATE INDEX IF NOT EXISTS `failai_sizes_virselis_sizes_virselis_filename_idx` ON `failai` (`sizes_virselis_filename`)",
  "CREATE INDEX IF NOT EXISTS `failai_updated_at_idx` ON `failai` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `grupes_created_at_idx` ON `grupes` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `grupes_pamokos_order_idx` ON `grupes_pamokos` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `grupes_pamokos_parent_id_idx` ON `grupes_pamokos` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `grupes_rels_mokiniai_id_idx` ON `grupes_rels` (`mokiniai_id`)",
  "CREATE INDEX IF NOT EXISTS `grupes_rels_order_idx` ON `grupes_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `grupes_rels_parent_idx` ON `grupes_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `grupes_rels_path_idx` ON `grupes_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `grupes_updated_at_idx` ON `grupes` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `mokiniai_created_at_idx` ON `mokiniai` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `mokiniai_pamokos_order_idx` ON `mokiniai_pamokos` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `mokiniai_pamokos_parent_id_idx` ON `mokiniai_pamokos` (`_parent_id`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `mokiniai_raktas_idx` ON `mokiniai` (`raktas`)",
  "CREATE INDEX IF NOT EXISTS `mokiniai_updated_at_idx` ON `mokiniai` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `naudotojai_created_at_idx` ON `naudotojai` (`created_at`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `naudotojai_email_idx` ON `naudotojai` (`email`)",
  "CREATE INDEX IF NOT EXISTS `naudotojai_sessions_order_idx` ON `naudotojai_sessions` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `naudotojai_sessions_parent_id_idx` ON `naudotojai_sessions` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `naudotojai_updated_at_idx` ON `naudotojai` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `nustatymai_kainos_order_idx` ON `nustatymai_kainos` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `nustatymai_kainos_parent_id_idx` ON `nustatymai_kainos` (`_parent_id`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `payload_kv_key_idx` ON `payload_kv` (`key`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_created_at_idx` ON `payload_locked_documents` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_global_slug_idx` ON `payload_locked_documents` (`global_slug`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_failai_id_idx` ON `payload_locked_documents_rels` (`failai_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_grupes_id_idx` ON `payload_locked_documents_rels` (`grupes_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_mokiniai_id_idx` ON `payload_locked_documents_rels` (`mokiniai_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_naudotojai_id_idx` ON `payload_locked_documents_rels` (`naudotojai_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_order_idx` ON `payload_locked_documents_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_parent_idx` ON `payload_locked_documents_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_path_idx` ON `payload_locked_documents_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_rezervacijos_id_idx` ON `payload_locked_documents_rels` (`rezervacijos_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_saskaitos_id_idx` ON `payload_locked_documents_rels` (`saskaitos_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_straipsniai_id_idx` ON `payload_locked_documents_rels` (`straipsniai_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_zurnalas_id_idx` ON `payload_locked_documents_rels` (`zurnalas_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_updated_at_idx` ON `payload_locked_documents` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_migrations_created_at_idx` ON `payload_migrations` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_migrations_updated_at_idx` ON `payload_migrations` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_created_at_idx` ON `payload_preferences` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_key_idx` ON `payload_preferences` (`key`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_naudotojai_id_idx` ON `payload_preferences_rels` (`naudotojai_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_order_idx` ON `payload_preferences_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_parent_idx` ON `payload_preferences_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_path_idx` ON `payload_preferences_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_updated_at_idx` ON `payload_preferences` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `rezervacijos_created_at_idx` ON `rezervacijos` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `rezervacijos_data_idx` ON `rezervacijos` (`data`)",
  "CREATE INDEX IF NOT EXISTS `rezervacijos_updated_at_idx` ON `rezervacijos` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_created_at_idx` ON `saskaitos` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_data_idx` ON `saskaitos` (`data`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_eilutes_order_idx` ON `saskaitos_eilutes` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_eilutes_parent_id_idx` ON `saskaitos_eilutes` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_laikotarpis_nuo_idx` ON `saskaitos` (`laikotarpis_nuo`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `saskaitos_numeris_idx` ON `saskaitos` (`numeris`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_rels_mokiniai_id_idx` ON `saskaitos_rels` (`mokiniai_id`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_rels_order_idx` ON `saskaitos_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_rels_parent_idx` ON `saskaitos_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_rels_path_idx` ON `saskaitos_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `saskaitos_updated_at_idx` ON `saskaitos` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai__status_idx` ON `straipsniai` (`_status`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_created_at_idx` ON `straipsniai` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_klases_order_idx` ON `straipsniai_klases` (`order`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_klases_parent_idx` ON `straipsniai_klases` (`parent_id`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `straipsniai_locales_locale_parent_id_unique` ON `straipsniai_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_meta_meta_image_idx` ON `straipsniai_locales` (`meta_image_id`,`_locale`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `straipsniai_nuoroda_idx` ON `straipsniai` (`nuoroda`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_updated_at_idx` ON `straipsniai` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `straipsniai_virselis_idx` ON `straipsniai` (`virselis_id`)",
  "CREATE INDEX IF NOT EXISTS `tvarkarastis_dienos_order_idx` ON `tvarkarastis_dienos` (`order`)",
  "CREATE INDEX IF NOT EXISTS `tvarkarastis_dienos_parent_idx` ON `tvarkarastis_dienos` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `tvarkarastis_pakeitimai_order_idx` ON `tvarkarastis_pakeitimai` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `tvarkarastis_pakeitimai_parent_id_idx` ON `tvarkarastis_pakeitimai` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `zurnalas_created_at_idx` ON `zurnalas` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `zurnalas_data_idx` ON `zurnalas` (`data`)",
  "CREATE INDEX IF NOT EXISTS `zurnalas_grupe_idx` ON `zurnalas` (`grupe_id`)",
  "CREATE INDEX IF NOT EXISTS `zurnalas_mokinys_idx` ON `zurnalas` (`mokinys_id`)",
  "CREATE INDEX IF NOT EXISTS `zurnalas_saskaita_idx` ON `zurnalas` (`saskaita_id`)",
  "CREATE INDEX IF NOT EXISTS `zurnalas_updated_at_idx` ON `zurnalas` (`updated_at`)",
]
